const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
const record={DOI:'10.1234/a',title:'A reliable retinal study with a complete title',year:'2020',author:'Smith'},article={doi:record.DOI,title:record.title,pubYear:'2020',source:'MED',id:'123',abstractText:'<h4>Methods</h4><p>We measured retinal cells &amp; tissue.</p><h4>Results</h4><p>Results were heterogeneous.</p>',authorList:{author:[{lastName:'Smith'}]}};
function setup(transport=async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:url.includes('esearch')?{esearchresult:{idlist:[]}}:{message:{items:[]}})){
 const prefs=new Map(),ctx={CiteLensCore:C,Zotero:{getMainWindow:()=>({setTimeout,clearTimeout}),Prefs:{get:k=>prefs.get(k),set:(k,v)=>prefs.set(k,v),clear:k=>prefs.delete(k)}}};vm.createContext(ctx);for(const file of ['authors','abstracts'])vm.runInContext(fs.readFileSync(require.resolve('../addon/'+file+'.js'),'utf8'),ctx);const S={state:{settings:{autoAuthors:false}},active:2,waiting:[],dead:false,locate:async()=>[],persist:async()=>{}};ctx.CiteLensAbstracts.transport=transport;return {A:ctx.CiteLensAbstracts,S,prefs};
}
test('existing library abstract takes precedence without online requests',async()=>{let calls=0;const {A,S}=setup(async()=>{calls++;throw Error();});S.locate=async()=>[{item:{getField:()=>'<p>Local abstract.</p>'}}];const r=await A.lookup(S,record);assert.equal(r.text,'Local abstract.');assert.equal(r.source,'本地文献库');assert.equal(calls,0);});
test('published abstract is sanitized, deduplicated and independent of full background queues',async()=>{let calls=0;const {A,S}=setup(async url=>{calls++;return JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});});const [a,b]=await Promise.all([A.lookup(S,record),A.lookup(S,record)]);assert.equal(a.status,'available');assert.equal(a.text,b.text);assert.ok(a.text.includes('Methods\n\nWe measured'));assert.ok(a.text.includes('tissue.\n\nResults\n\nResults'));assert.equal(calls,2);await A.lookup(S,record);assert.equal(calls,2);assert.equal(A.text('<script>evil()</script><p>Safe &alpha;</p>'),'Safe α');assert.equal(S.waiting.length,0);});
test('conflicting DOI, title, authors and years cannot contribute an abstract',async()=>{for(const bad of [{...article,doi:'10.1234/b'},{...article,title:'Unrelated geology and mineral study'},{...article,pubYear:'1990'},{...article,authorList:{author:[{lastName:'Jones'}]}}]){const {A,S}=setup(async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[bad]}}:url.includes('esearch')?{esearchresult:{idlist:[]}}:{message:{DOI:'10.1234/b',title:['Not this paper']}}));assert.equal((await A.lookup(S,record)).status,'missing');}});
test('ambiguous title-only matches cannot contribute an abstract',()=>{const {A}=setup();assert.equal(A.select({title:record.title,year:'2020',author:'Smith'},[{...record,DOI:'10.1234/x'},{...record,DOI:'10.1234/y'}]),null);});
test('unresponsive providers and library cannot leave preview loading indefinitely',async()=>{const {A,S}=setup(()=>new Promise(()=>{}));S.locate=()=>new Promise(()=>{});const start=Date.now(),r=await A.lookup(S,record,{budget:30});assert.equal(r.status,'offline');assert.ok(Date.now()-start<250);assert.equal(r.text,undefined);});
test('force retry ignores transient failure cache',async()=>{const {A,S}=setup(async()=>{throw Error('offline');});assert.equal((await A.lookup(S,record)).status,'offline');A.transport=async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});assert.equal((await A.lookup(S,record,{force:true})).status,'available');});
test('conflicting library abstracts do not arbitrarily select the first copy',async()=>{const {A,S}=setup();S.locate=async()=>['First local','Second local'].map(text=>({item:{getField:()=>text}}));assert.equal((await A.lookup(S,record)).source,'Europe PMC');});
test('API key stays in local preferences and NCBI POST body, never URLs or state',async()=>{const calls=[],{A,S}=setup(async(url,opts)=>{calls.push([url,opts]);return JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});}),secret='synthetic-test-key-12345678';A.apiKey(secret);await A.lookup(S,record);assert.ok(calls.some(([url,o])=>url.includes('ncbi')&&o.body.includes('api_key='+secret)));assert.ok(calls.every(([url,o])=>!url.includes(secret)&&(!url.includes('europepmc')||!o.body)));assert.ok(!JSON.stringify(S.state).includes(secret));A.apiKey('');assert.equal(A.apiKey(),'');});
test('abstract side placement is joined, bounded and nonoverlapping',()=>{const {A}=setup();for(const width of [360,620,900,1400])for(const x of [8,180,width-428]){if(x<0||x+420>width)continue;const anchor={left:x,right:x+420,top:450},p=A.placement(anchor,{width,height:700},450,380);if(p.side==='inline')continue;assert.ok(p.left>=8&&p.left+p.width<=width-8);assert.ok(p.left+p.width<=anchor.left||p.left>=anchor.right);assert.ok(p.top>=42&&p.top+Math.min(380,p.maxHeight)<=692);}});

test('cached abstract is rechecked against a changed title or year sharing the DOI',async()=>{const {A,S}=setup();assert.equal((await A.lookup(S,record)).status,'available');A.transport=async url=>JSON.stringify(url.includes('esearch')?{esearchresult:{idlist:[]}}:url.includes('europepmc')?{resultList:{result:[]}}:{message:{DOI:record.DOI,title:[record.title],abstract:'Old abstract',published:{'date-parts':[[2020]]},author:[{family:'Smith'}]}});assert.equal((await A.lookup(S,{...record,title:'Completely different geological and volcanic findings',year:'1990'})).status,'missing');});
test('title-only abstract lookup reaches Europe PMC and revalidates title author and year',async()=>{const queries=[],{A,S}=setup(async(url)=>{queries.push(url);return JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});});const r=await A.lookup(S,{title:record.title,year:'2020',author:'Smith'});assert.equal(r.status,'available');assert.equal(r.record.PMID,'123');assert.ok(queries.some(url=>decodeURIComponent(url).includes('TITLE:"'+record.title+'"')));assert.ok(r.url.endsWith('/MED/123'));});
test('NCBI title clauses preserve phrases rather than ANDing unindexed stopwords',async()=>{const calls=[],{A,S}=setup(async(url,opts)=>{calls.push([url,opts]);return JSON.stringify(url.includes('europepmc')?{resultList:{result:[]}}:url.includes('esearch')?{esearchresult:{idlist:[]}}:{message:{items:[]}});});await A.lookup(S,{title:'Causes and consequences of RNA polymerase II stalling during transcript elongation',year:'2021',author:'Noe Gonzalez'});const terms=calls.filter(([u])=>u.includes('esearch')).map(([,o])=>new URLSearchParams(o.body).get('term'));assert.equal(terms.length,2);assert.ok(terms[0].startsWith('"Causes'));assert.ok(terms.every(t=>!t.includes('during[Title]'))&&terms[1].includes(' AND '));});
test('negative caches from the old query strategy are bypassed after the query fix',async()=>{const {A,S}=setup();S.state.abstractCache={['doi:'+record.DOI]:{version:2,expires:Date.now()+86400000,value:{status:'missing'}}};assert.equal((await A.lookup(S,record)).status,'available');assert.equal(S.state.abstractCache['doi:'+record.DOI].version,3);});

test('E-utilities connection test supports no key and sends configured credentials only via POST',async()=>{const calls=[],{A}=setup(async(u,o)=>{calls.push([u,o]);return JSON.stringify({einforesult:{dbinfo:[{dbname:'pubmed'}]}});});assert.equal((await A.testConnection()).ok,true);assert.ok(!calls[0][1].body.includes('api_key'));A.apiKey('synthetic-test-key-12345678');assert.equal((await A.testConnection()).ok,true);assert.ok(calls[1][1].body.includes('api_key=synthetic'));assert.ok(!calls[1][0].includes('synthetic'));});
test('E-utilities test rejects error payloads and unexpected data without disclosing credentials',async()=>{for(const response of [{error:'API key invalid synthetic-test-key-12345678'},{einforesult:{}},{einforesult:{dbinfo:[{dbname:'gene'}]}}]){const {A}=setup(async()=>JSON.stringify(response));await assert.rejects(A.testConnection(),e=>!e.message.includes('synthetic')&&/NCBI/.test(e.message));}});
test('E-utilities connection deadline also aborts an unresponsive transport',async()=>{let aborted=false;const {A}=setup(async(u,o)=>{o.signal.add(()=>aborted=true);return new Promise(()=>{});});const start=Date.now();await assert.rejects(A.testConnection({budget:20}),/连接失败/);assert.ok(Date.now()-start<250);assert.ok(aborted);});

test('drag docking joins either edge only when it fits and overlaps the reference vertically',()=>{const {A}=setup(),anchor={left:500,right:900,top:100,bottom:340},viewport={width:1400,height:800},size={width:440,height:260};for(const [left,side,expected] of [[70,'left',54],[885,'right',906],[300,'bottom',300]]){const p=A.dragPlacement(anchor,viewport,size,{left,top:115});assert.equal(p.side,side);assert.equal(p.left,expected);if(['left','right'].includes(side))assert.equal(p.top,100);}assert.equal(A.dragPlacement(anchor,viewport,size,{left:900,top:420}).side,'free');const constrained=A.dragPlacement(anchor,{width:1120,height:800},size,{left:900,top:115});assert.ok(['top','bottom','left'].includes(constrained.side));});
test('dragging remains reachable on small viewports and can detach from either edge',()=>{const {A}=setup(),anchor={left:8,right:300,top:50,bottom:200};for(const width of [320,620,1400])for(const point of [{left:-300,top:-500},{left:2000,top:3000}]){const p=A.dragPlacement(anchor,{width,height:480},{width:440,height:600},point,false);assert.equal(p.side,'free');assert.ok(p.left>=8&&p.left+p.width<=width-8);assert.ok(p.top>=8&&p.top+p.maxHeight<=472);}});

test('overlap docks to the longest crossed edge, including top and bottom',()=>{const {A}=setup(),anchor={left:450,right:850,top:300,bottom:500},viewport={width:1400,height:900},size={width:440,height:220};for(const [point,side] of [[{left:450,top:160},'top'],[{left:450,top:420},'bottom'],[{left:40,top:310},'left'],[{left:825,top:310},'right']]){const p=A.dragPlacement(anchor,viewport,size,point);assert.equal(p.side,side);assert.ok(p.left+p.width<=anchor.left||p.left>=anchor.right||p.top+Math.min(size.height,p.maxHeight)<=anchor.top||p.top>=anchor.bottom);}});
test('a window with no usable exterior space uses inline placement instead of hiding the article',()=>{const {A}=setup();assert.equal(A.dragPlacement({left:8,right:312,top:8,bottom:472},{width:320,height:480},{width:304,height:320},{left:8,top:70}).side,'inline');});
test('resizing keeps opposite edges fixed and respects the viewport and minimum reading size',()=>{const {A}=setup(),box={left:100,top:100,right:540,bottom:400},v={width:1000,height:700};for(const edge of ['n','e','s','w','ne','nw','se','sw']){const p=A.resizePlacement(box,v,edge,40,30);assert.ok(p.width>=240&&p.height>=120);assert.ok(p.left>=8&&p.top>=8&&p.left+p.width<=992&&p.top+p.height<=692);}const p=A.resizePlacement(box,v,'nw',-999,-999);assert.equal(p.left,8);assert.equal(p.top,8);assert.equal(p.left+p.width,540);assert.equal(p.top+p.height,400);});
