const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
const record={DOI:'10.1234/a',title:'A reliable retinal study with a complete title',year:'2020',author:'Smith'},article={doi:record.DOI,title:record.title,pubYear:'2020',source:'MED',id:'123',abstractText:'<h4>Methods</h4><p>We measured retinal cells &amp; tissue.</p><h4>Results</h4><p>Results were heterogeneous.</p>',authorList:{author:[{lastName:'Smith'}]}};
function setup(transport=async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:url.includes('esearch')?{esearchresult:{idlist:[]}}:{message:{items:[]}})){
 const prefs=new Map(),ctx={CiteLensCore:C,Zotero:{getMainWindow:()=>({setTimeout,clearTimeout}),Prefs:{get:k=>prefs.get(k),set:(k,v)=>prefs.set(k,v),clear:k=>prefs.delete(k)}}};vm.createContext(ctx);for(const file of ['authors','abstracts'])vm.runInContext(fs.readFileSync(require.resolve('../addon/'+file+'.js'),'utf8'),ctx);const S={state:{settings:{autoAuthors:false}},active:2,waiting:[],dead:false,locate:async()=>[],persist:async()=>{}};ctx.CiteLensAbstracts.transport=transport;return {A:ctx.CiteLensAbstracts,S,prefs};
}
test('existing library abstract takes precedence without online requests',async()=>{let calls=0;const {A,S}=setup(async()=>{calls++;throw Error();});S.locate=async()=>[{item:{getField:()=>'<p>Local abstract.</p>'}}];const r=await A.lookup(S,record);assert.equal(r.text,'Local abstract.');assert.equal(r.source,'本地文献库');assert.equal(calls,0);});
test('published abstract is sanitized, deduplicated and independent of full background queues',async()=>{let calls=0;const {A,S}=setup(async url=>{calls++;return JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});});const [a,b]=await Promise.all([A.lookup(S,record),A.lookup(S,record)]);assert.equal(a.status,'available');assert.equal(a.text,b.text);assert.ok(a.text.includes('Methods\n\nWe measured'));assert.ok(a.text.includes('tissue.\n\nResults\n\nResults'));assert.equal(calls,2);await A.lookup(S,record);assert.equal(calls,2);assert.equal(A.text('<script>evil()</script><p>Safe &alpha;</p>'),'Safe α');assert.equal(S.waiting.length,0);});
test('conflicting DOI, title, authors and years cannot contribute an abstract',async()=>{for(const bad of [{...article,doi:'10.1234/b'},{...article,title:'Unrelated geology and mineral study'},{...article,pubYear:'1990'},{...article,authorList:{author:[{lastName:'Jones'}]}}]){const {A,S}=setup(async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[bad]}}:url.includes('esearch')?{esearchresult:{idlist:[]}}:{message:{DOI:'10.1234/b',title:['Not this paper']}}));assert.equal((await A.lookup(S,record)).status,'missing');}});
test('ambiguous title-only matches cannot contribute an abstract',()=>{const {A}=setup();assert.equal(A.select({title:record.title,year:'2020',author:'Smith'},[{...record,DOI:'10.1234/x'},{...record,DOI:'10.1234/y'}]),null);});
test('unresponsive providers and library cannot leave preview loading indefinitely',async()=>{const {A,S}=setup(()=>new Promise(()=>{}));S.locate=()=>new Promise(()=>{});const start=Date.now(),r=await A.lookup(S,record,{budget:30});assert.equal(r.status,'offline');assert.ok(Date.now()-start<250);assert.equal(r.text,undefined);});
test('force retry ignores transient failure cache',async()=>{const {A,S}=setup(async()=>{throw Error('offline');});assert.equal((await A.lookup(S,record)).status,'offline');A.transport=async url=>JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});assert.equal((await A.lookup(S,record,{force:true})).status,'available');});
test('conflicting library abstracts do not arbitrarily select the first copy',async()=>{const {A,S}=setup();S.locate=async()=>['First local','Second local'].map(text=>({item:{getField:()=>text}}));assert.equal((await A.lookup(S,record)).source,'Europe PMC');});
test('API key stays in local preferences and NCBI POST body, never URLs or state',async()=>{const calls=[],{A,S}=setup(async(url,opts)=>{calls.push([url,opts]);return JSON.stringify(url.includes('europepmc')?{resultList:{result:[article]}}:{esearchresult:{idlist:[]}});}),secret='synthetic-test-key-12345678';A.apiKey(secret);await A.lookup(S,record);assert.ok(calls.some(([url,o])=>url.includes('ncbi')&&o.body.includes('api_key='+secret)));assert.ok(calls.every(([url,o])=>!url.includes(secret)&&(!url.includes('europepmc')||!o.body)));assert.ok(!JSON.stringify(S.state).includes(secret));A.apiKey('');assert.equal(A.apiKey(),'');});
test('abstract side placement is joined, bounded and nonoverlapping',()=>{const {A}=setup();for(const width of [360,620,900,1400])for(const x of [8,180,width-428]){if(x<0||x+420>width)continue;const anchor={left:x,right:x+420,top:450},p=A.placement(anchor,{width,height:700},450,380);if(p.side==='inline')continue;assert.ok(p.left>=8&&p.left+p.width<=width-8);assert.ok(p.left+p.width<=anchor.left||p.left>=anchor.right);assert.ok(p.top>=42&&p.top+Math.min(380,p.maxHeight)<=692);}});

test('cached abstract is rechecked against a changed title or year sharing the DOI',async()=>{const {A,S}=setup();assert.equal((await A.lookup(S,record)).status,'available');A.transport=async url=>JSON.stringify(url.includes('esearch')?{esearchresult:{idlist:[]}}:url.includes('europepmc')?{resultList:{result:[]}}:{message:{DOI:record.DOI,title:[record.title],abstract:'Old abstract',published:{'date-parts':[[2020]]},author:[{family:'Smith'}]}});assert.equal((await A.lookup(S,{...record,title:'Completely different geological and volcanic findings',year:'1990'})).status,'missing');});
