const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
function setup(http){const ctx={CiteLensCore:C,PathUtils:{},Zotero:{HTTP:{request:http},logError(){}},IOUtils:{writeUTF8:async()=>{}}};vm.createContext(ctx);for(const f of ['authors','services'])vm.runInContext(fs.readFileSync(require.resolve('../addon/'+f+'.js'),'utf8'),ctx);return {S:ctx.CiteLensServices,A:ctx.CiteLensAuthors};}
const doi='10.1234/a',title='An example reference with an accurate full title',record={DOI:doi,title,type:'journalArticle'},result={resultList:{result:[{doi,title,source:'MED',id:'123',authorList:{author:[{firstName:'First',lastName:'Person'},{firstName:'Last',lastName:'Person'}]}}]}};
test('author query deduplicates, preserves order, caches successful lists',async()=>{let count=0;const {S}=setup(async()=>{count++;await new Promise(r=>setTimeout(r,5));return {response:result};});const [a,b]=await Promise.all([S.authors(record),S.authors(record)]);assert.equal(count,1);assert.equal(a.authors[0].firstName,'First');assert.equal(a.authors[1].firstName,'Last');assert.equal(b.status,'available');assert.equal((await S.authors(record)).status,'available');assert.equal(count,1);assert.ok(S.state.authorCache['doi:'+doi].expires-Date.now()>29*86400000);});
test('six slots use first three and last three without overlap',()=>{const {A}=setup();for(const n of [0,1,2,3,5,6,7,10,100]){const authors=Array.from({length:n},(_,i)=>({lastName:'Author'+i})),slots=A.visible(authors);assert.deepEqual(Array.from(slots,s=>s.index),n<=6?Array.from({length:n},(_,i)=>i):[0,1,2,n-3,n-2,n-1]);assert.equal(slots.filter(s=>s.gapAfter).length,n>6?1:0);}});
test('initials keep compound names and non-Latin surnames readable',()=>{const {A}=setup();assert.equal(A.shortName({firstName:'Adriana K.',lastName:'Alexander'}),'A.K. Alexander');assert.equal(A.shortName({lastName:'研究协作组'}),'研究协作组');assert.equal(A.name({firstName:'Paula E.',lastName:'Cohen'}),'Paula E. Cohen');});
test('provider result must match identifiers and not contradict title',()=>{const {A}=setup();assert.equal(A.selectPMC({...record,DOI:'10.1234/other'},result),null);assert.equal(A.selectPMC({...record,title:'This totally unrelated study about retinal cell development'},result),null);assert.equal(A.matches({DOI:doi,PMID:'1'},{DOI:doi,PMID:'2'}),false);});
test('conflicting index records are not arbitrarily selected',()=>{const {A}=setup();assert.equal(A.selectPMC(record,{resultList:{result:[...result.resultList.result,{...result.resultList.result[0],id:'124'}]}}),null);});
test('no-identifier ambiguity does not query author endpoints',async()=>{let calls=0;const {S}=setup(async()=>{calls++;throw Error();});S.lookup=async()=>({status:'review',ranked:[]});const r=await S.authors({title,author:'Person',year:'2020'});assert.equal(r.status,'review');assert.equal(calls,0);});
test('network failure gets short backoff, never a successful empty list',async()=>{const {S}=setup(async()=>{throw {status:503};});const r=await S.authors(record);assert.equal(r.status,'offline');assert.equal(r.authors.length,0);assert.ok(S.state.authorCache['doi:'+doi].expires-Date.now()<=300000);});
test('disabled service and books do not issue requests',async()=>{let calls=0;const {S}=setup(async()=>{calls++;});S.state.settings.autoAuthors=false;assert.equal((await S.authors(record)).status,'disabled');S.state.settings.autoAuthors=true;assert.equal((await S.authors({...record,type:'book'})).status,'not-applicable');await S.stop();assert.equal((await S.authors(record)).status,'disabled');assert.equal(calls,0);});
test('author requests respect the shared two-request concurrency cap',async()=>{let active=0,max=0;const {S}=setup(async(method,url)=>{max=Math.max(max,++active);await new Promise(r=>setTimeout(r,10));active--;const n=Number(decodeURIComponent(url).match(/10\.1234\/(\d+)/)?.[1]);return {response:{resultList:{result:[{...result.resultList.result[0],doi:'10.1234/'+n}]}}};});await Promise.all(Array.from({length:7},(_,i)=>S.authors({...record,DOI:'10.1234/'+i})));assert.equal(max,2);});
test('revoking while request runs prevents subsequent calls and persistent writes',async()=>{let release,calls=0;const {S}=setup(()=>{calls++;return new Promise(r=>release=r);});const pending=S.authors(record);S.state.settings.autoAuthors=false;S.authorGeneration=1;release({response:{resultList:{result:[]}}});await pending;assert.equal(Object.keys(S.state.authorCache||{}).length,0);assert.equal(calls,1);});
test('failed refresh preserves a prior author list',async()=>{let fail=false;const {S}=setup(async()=>{if(fail)throw {status:503};return {response:result};});await S.authors(record);fail=true;const r=await S.authors(record,{force:true});assert.equal(r.status,'offline');assert.equal(r.authors[0].firstName,'First');});
