const {test}=require('node:test'),assert=require('node:assert/strict');global.CiteLensCore=require('../addon/core.js');const B=require('../addon/bibliography.js');
const item=(str,x,y)=>({str,transform:[8,0,0,8,x,y],width:str.length*3,height:8});
test('requires explicit bibliography heading',()=>{assert.deepEqual(B.parse([{pageIndex:0,width:600,height:800,items:[item('Smith, A., 2020. A long paper title. Science 1, 1.',40,400)]}]),[]);});
test('hanging indentation joins continuation and preserves coordinates',()=>{const refs=B.parse([{pageIndex:8,width:600,height:800,items:[item('References',40,700),item('Müller, H., 1856. Anatomisch-physiologische',40,680),item('Untersuchungen über die Retina. Zeitschrift 8, 1.',50,668),item('Polyak, S.L., 1957. The Vertebrate Visual System.',40,645),item('University of Chicago Press, Chicago.',50,633)]}]);assert.equal(refs.length,2);assert.equal(refs[0].author,'Müller');assert.equal(refs[1].type,'book');assert.equal(refs[0].position.pageIndex,8);assert.equal(refs[0].position.rects.length,2);});
test('merging respects different works with same author and year',()=>{const C=global.CiteLensCore,a=C.parse('Smith, A., 2020. Development of the retina. Science 1, 1.'),same={...a},other=C.parse('Smith, A., 2020. Chromatin structure during cell division. Cell 1, 1.');assert.equal(B.merge([a],[same,other]).length,2);});
test('single column inline journal fragments do not create a second column',()=>{
 const items=[item('LITERATURE CITED',46,700)];for(let i=0;i<6;i++){items.push({...item('Smith AB, Jones CD. 2020. Microglial development in the human brain.',46,680-i*30),width:385},item('Journal',270,670-i*30),item('12:34–45',310,670-i*30));}
 const refs=B.parse([{pageIndex:0,width:531,height:800,items}]);assert.equal(refs.length,6);assert.ok(refs.every(r=>r.raw.includes('Journal 12:34–45')));
});
test('alternating page margins and methods boundaries preserve only bibliography records',()=>{
 const pages=[{pageIndex:0,width:531,height:800,items:[item('Literature Cited',46,700),item('Smith AB, Jones CD. 2020. Microglial development.',46,680),item('Brain 10:20–30',64,668)]},{pageIndex:1,width:531,height:800,items:[item('Watson AB, Green CD. 2021. Neuronal specification.',121,730),item('Science 20:30–40',140,718),item('444',46,30)]},{pageIndex:2,width:531,height:800,items:[item('STAR+METHODS',46,730),item('24 hours of culture (Jones, 2020). Experimental procedure.',46,710)]}];const refs=B.parse(pages);assert.equal(refs.length,2);assert.equal(refs[1].author,'Watson');assert.doesNotMatch(refs[1].raw,/444|METHODS|culture/);
});
test('author list wrapping at the left margin does not drop first authors',()=>{
 const refs=B.parse([{pageIndex:0,width:600,height:800,items:[item('REFERENCES',40,730),item('Smith, A., Jones, B., White, C., and',40,710),item('Green, D. (2020). Local translation in axons.',40,699),item('Nature 10, 20–30.',40,688),item('Liu, H., and Wu, C. (2017). Rab7 Signaling? Int. J. Mol. Sci. 18, 324.',40,670)]}]);assert.equal(refs.length,2);assert.equal(refs[0].author,'Smith');assert.equal(refs[0].creators.length,4);assert.equal(refs[1].creators[1].lastName,'Wu');assert.equal(refs[1].title,'Rab7 Signaling?');assert.equal(CiteLensCore.findCitations('Liu and Wu, 2017',refs).length,1);
});
