const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Core=require('../addon/core.js');
function setup(){let requests=0;const ctx={CiteLensCore:Core,PathUtils:{join:(...x)=>x.join('/'),parent:()=>'/cache'},CiteLensServices:{path:'/cache/state.json'},IOUtils:{stat:async()=>{throw Error('absent');},makeDirectory:async()=>{},writeUTF8:async()=>{},getChildren:async()=>[]},Zotero:{logError(){},HTTP:{request:async()=>{requests++;return {response:{}};}}}};vm.createContext(ctx);for(const file of ['network-core.js','career.js'])vm.runInContext(fs.readFileSync(require.resolve('../addon/'+file),'utf8'),ctx);return {C:ctx.CiteLensCareer,ctx,requests:()=>requests};}
const date=(year,month,day)=>({year:{value:String(year)},...(month?{month:{value:String(month)}}:{}),...(day?{day:{value:String(day)}}:{})});
const work=(id,title,year,doi)=>({'put-code':id,title:{title:{value:title}},'publication-date':date(year),'external-ids':{'external-id':[{ 'external-id-type':'doi','external-id-value':doi,'external-id-relationship':'self'}]},source:{'source-name':{value:'Publisher'}},visibility:'public'});
test('career dates retain precision and never invent missing months, days or current positions',()=>{const {C}=setup();assert.equal(C.date(date(2020)).label,'2020');assert.equal(C.date(date(2020,2)).label,'2020.02');assert.equal(C.date(date(2020,2,29)).label,'2020.02.29');assert.equal(C.date(date(2021,2,29)).precision,'month');assert.equal(C.date({month:{value:'5'}}),null);const value=C.parse('id',{}, {employments:{'affiliation-group':[{summaries:[{'employment-summary':{'put-code':1,organization:{name:'University'},'role-title':'Professor','start-date':date(2000)}}]}]}});assert.equal(value.events[0].end,null);});
test('career deduplicates DOI records and preserves provenance without using record edit date as event date',()=>{const {C}=setup(),a=work(1,'Paper',2020,'10.1234/a'),b={...a,'put-code':2,source:{'source-name':{value:'Researcher'}}};const value=C.parse('id',{}, {works:{group:[{'work-summary':[a,b]},{'work-summary':[b]},{'work-summary':[{...work(3,'Undated',2021,'10.1234/b'),'publication-date':null,'last-modified-date':{value:Date.now()}}]}]}});assert.equal(value.events.length,2);assert.equal(value.events[0].sources.length,2);assert.equal(value.events[1].year,null);assert.equal(C.groups(value.events,{descending:true}).at(-1).year,0);});
test('career respects private records and sanitizes outbound links',()=>{const {C}=setup(),w=work(1,'Private',2020,'10.1234/private');w.visibility='limited';assert.equal(C.parse('id',{}, {works:{group:[{'work-summary':[w]}]}}).events.length,0);for(const url of ['javascript:alert(1)','file:///etc/passwd','https://user:pass@example.org','https://a.org/\nscript'])assert.equal(C.safeURL(url),'');assert.equal(C.safeURL('https://example.org/path'),'https://example.org/path');});
test('career groups sparse, paper-only and undated records without empty category placeholders',()=>{const {C}=setup();assert.equal(C.groups([]).length,0);const value=C.parse('id',{}, {works:{group:[{'work-summary':[work(1,'Paper A',2020,'10.1234/a')]},{'work-summary':[work(2,'Paper B',2022,'10.1234/b')]}]}});assert.equal(C.groups(value.events,{kind:'education'}).length,0);assert.deepEqual(Array.from(C.groups(value.events),x=>x.year),[2020,2022]);assert.deepEqual(Array.from(C.groups(value.events,{descending:true}),x=>x.year),[2022,2020]);});
test('career loads only on demand, shares requests, caches results and retains them offline',async()=>{const {C,ctx,requests}=setup();assert.equal(requests(),0);const [a,b]=await Promise.all([C.load('0000-0001-6232-9969'),C.load('0000-0001-6232-9969')]);assert.equal(requests(),2);assert.equal(a,b);await C.load(a.orcid);assert.equal(requests(),2);ctx.Zotero.HTTP.request=async()=>{throw Error('offline');};const old=await C.load(a.orcid,{force:true});assert.equal(old.stale,true);assert.equal(old.fetchedAt,a.fetchedAt);C.stop();await assert.rejects(C.load(a.orcid),/关闭/);});

test('career excludes peer reviews from fresh records and older local caches',async()=>{const {C,ctx}=setup(),oid='0000-0001-6232-9969';const activities={'peer-reviews':{group:[{'peer-review-group':[{'peer-review-summary':[{'put-code':1,'review-group-id':'Journal','completion-date':date(2020)}]}]}]}};assert.equal(C.parse(oid,{},activities).events.length,0);ctx.IOUtils.stat=async()=>({size:100});ctx.IOUtils.readUTF8=async()=>JSON.stringify({schema:2,orcid:oid,profile:{name:'Name',links:[],keywords:[]},events:[{id:'1',title:'Review',kind:'review'},{id:'2',title:'Degree',kind:'education'}],fetchedAt:Date.now()});assert.deepEqual(Array.from((await C.load(oid)).events,e=>e.kind),['education']);});

test('provider duplicates merge conservatively and preferred assertions gain missing metadata',()=>{const {C}=setup(),title='Secondary structural complementarity between DNA and proteins',a=work(1,title,1977,'10.1073/pnas.74.4.1458'),b=work(2,title,1977,undefined);a['journal-title']={value:'PNAS'};b['journal-title']={value:'PNAS'};b['external-ids']={'external-id':[{'external-id-type':'eid','external-id-value':'scopus:123','external-id-relationship':'self'}]};let v=C.parse('id',{}, {works:{group:[{'work-summary':[a]},{'work-summary':[b]}]}});assert.equal(v.events.length,1);assert.equal(v.events[0].DOI,'10.1073/pnas.74.4.1458');const other={...a,'put-code':3,'external-ids':work(3,title,1977,'10.1234/different')['external-ids']};v=C.parse('id',{}, {works:{group:[{'work-summary':[a]},{'work-summary':[other]},{'work-summary':[b]}]}});assert.equal(v.events.length,3);const preferred=work(4,title,1977,undefined);preferred['display-index']='2';v=C.parse('id',{}, {works:{group:[{'work-summary':[preferred,a]}]}});assert.equal(v.events.length,1);assert.equal(v.events[0].journal,'PNAS');assert.equal(v.events[0].DOI,a['external-ids']['external-id'][0]['external-id-value']);});
test('descending chronology reverses dates within the year too',()=>{const {C}=setup(),events=[{year:2020,start:C.date(date(2020,2))},{year:2020,start:C.date(date(2020,11))}];assert.equal(C.groups(events,{descending:true})[0].events[0].start.month,11);});
test('concurrent profiles never exceed two requests and stop rejects queued work',async()=>{const {C,ctx}=setup();let active=0,peak=0,releases=[];ctx.Zotero.HTTP.request=async()=>{active++;peak=Math.max(peak,active);await new Promise(r=>releases.push(r));active--;return {response:{}};};const a=C.load('0000-0001-6232-9969'),b=C.load('0000-0002-9053-5249');await new Promise(r=>setImmediate(r));assert.equal(active,2);for(let i=0;i<3;i++){releases.splice(0).forEach(r=>r());await new Promise(r=>setImmediate(r));}await Promise.all([a,b]);assert.equal(peak,2);const c=C.load('0000-0001-6232-9969',{force:true});const d=C.load('0000-0002-9053-5249',{force:true});const stopped=Promise.allSettled([c,d]);await new Promise(r=>setImmediate(r));C.stop();releases.splice(0).forEach(r=>r());assert.ok((await stopped).every(x=>x.status==='rejected'));});
