const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../addon/core.js'),ctx={CiteLensCore:C};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/citation-format.js'),'utf8'),ctx);const F=ctx.CiteLensCitationFormat;
test('CSL data preserves authors, years, journal, pagination and DOI without library writes',()=>{const r=F.item({title:'<i>Retinal</i> development',creators:[{firstName:'Jane',lastName:'Smith'},{name:'Retina Consortium'}],year:'2020',journal:'Development',volume:'147',issue:'3',pages:'1–9',DOI:'https://doi.org/10.1234/test'});assert.equal(r.title,'Retinal development');assert.equal(r.author[0].given,'Jane');assert.equal(r.author[1].literal,'Retina Consortium');assert.equal(r.issued['date-parts'][0][0],2020);assert.equal(r.DOI,'10.1234/test');assert.equal(r.page,'1–9');assert.equal(r.type,'article-journal');});
test('CSL never invents a year or given names and handles books and chapters',()=>{const r=F.item({title:'Research methods',type:'bookSection',publisher:'University Press',author:'Smith'});assert.equal(r.type,'chapter');assert.equal(r.publisher,'University Press');assert.equal(r.issued,undefined);assert.equal(r.author[0].literal,'Smith');});
test('official styles use safe IDs and include requested general and biomedical presets',()=>{assert.throws(()=>F.id('../../private'));assert.throws(()=>F.id('https://evil.example/style'));const ids=F.presets.map(p=>p[0]);for(const key of ['apa','american-medical-association','modern-language-association','nlm-citation-sequence','nlm-name-year','nature','science','cell','pnas','investigative-ophthalmology-and-visual-science'])assert.ok(ids.includes(key));assert.equal(new Set(ids).size,ids.length);});
test('CSL preserves publisher abbreviation and book publication fields',()=>{
 const article=F.item({title:'Müller Cell Alignment in Bird Fovea',journal:'Journal of Neuroscience and Neuroengineering',journalAbbreviation:'J Neurosci Neuroengng'});assert.equal(article['container-title-short'],'J Neurosci Neuroengng');
 const book=F.item({type:'book',title:'Retinal Methods',journal:'Retinal Methods',edition:'2',place:'London',publisher:'Academic Press',ISBN:'9781234567890'});assert.equal(book['container-title'],'');assert.equal(book['publisher-place'],'London');assert.equal(book.edition,'2');
 const chapter=F.item({type:'bookSection',title:'Photoreceptors',bookTitle:'Retinal Methods',pages:'12–30'});assert.equal(chapter['container-title'],'Retinal Methods');assert.equal(chapter.page,'12–30');
});
