const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../addon/core.js');
test('DOI canonicalization preserves internal parentheses and strips citation punctuation',()=>{assert.equal(C.doi('https://doi.org/10.1016/S1350-9462(00)00012-4).'),'10.1016/s1350-9462(00)00012-4');assert.equal(C.doi('javascript:alert(1)'), '');});
test('screenshot Polyak book is not assigned journal metrics',()=>{const r=C.parse('Polyak, S.L., 1957. The Vertebrate Visual System. University of Chicago Press, Chicago.');assert.equal(r.title,'The Vertebrate Visual System');assert.equal(r.type,'book');assert.equal(r.author,'Polyak');assert.equal(C.metricFor(r,[]).status,'not-applicable');});
test('diacritics, ligatures, suffix and native chars preserved',()=>{const r=C.fromReference({chars:[{c:'Müller, H.,',spaceAfter:true},{c:'1856a.',spaceAfter:true},{c:'Visual ﬁeld.'}]});assert.equal(r.author,'Müller');assert.equal(r.suffix,'a');assert.match(r.title,/Visual field/);assert.equal(C.norm('Müller'),C.norm('Muller'));});
test('same author-year collisions never silently select one',()=>{const a=C.parse('Smith, A., 2020a. A sufficiently long title. Science 3, 1.'),b=C.parse('Smith, B., 2020b. A different paper title. Nature 4, 1.');assert.equal(C.findCitations('Smith, 2020',[a,b]).length,0);assert.equal(C.findCitations('Smith, 2020a',[a,b])[0],a);});
test('numeric ranges require bracket context and explicit numbers',()=>{const refs=[{number:1},{number:2},{number:3},{number:5}];assert.equal(C.findCitations('[1–3,5]',refs).length,4);assert.equal(C.findCitations('1–3',refs).length,0);assert.equal(C.findCitations('[0,1]',refs).length,0);assert.equal(C.findCitations('[1-999]',refs).length,0);});
test('exact DOI metadata conflict is rejected',()=>{const r={DOI:'10.1234/a',title:'Human retina development and the foveal area',year:'2020'},other={DOI:'10.1234/a',title:'Quantum mechanics of a black hole',year:'2020'};assert.equal(C.decide(r,[other]).status,'missing');assert.equal(C.decide(r,[{...r}]).status,'matched');});
test('similar competing candidates require explicit user selection',()=>{const r={title:'The primate fovea structure function and development',year:'2018',author:'Bringmann'};assert.equal(C.decide(r,[r,{...r,DOI:'10.1234/x'}]).status,'review');assert.equal(C.decide(r,[{...r,DOI:'10.1234/a'}]).status,'matched');});
test('metadata source does not invent missing abstract or author',()=>{const r=C.fromCrossref({DOI:'10.1234/a',title:['A < B'],published:{'date-parts':[[2020]]}});assert.equal(r.title,'A < B');assert.equal(r.abstract,'');assert.deepEqual(r.creators,[]);});
const row={issn:'0036-8075',journal:'Science',metricYear:2024,jif:1.2,category:'TEST CATEGORY',quartile:'Q1',source:'SYNTHETIC TEST ONLY'};
test('CSV quoted commas, year and provenance survive metric import',()=>{const r=C.metricsImport('issn,journal,metricYear,jif,category,quartile,source\n0036-8075,Science,2024,1.2,"Test, category",Q1,SYNTHETIC TEST ONLY');assert.equal(r[0].categories[0].name,'Test, category');assert.equal(r[0].metricYear,2024);});
test('metric conflicts and invalid ISSN are rejected atomically',()=>{for(const data of [[{...row,issn:'0000-1234'}],[{...row,source:''}],[row,{...row,jif:9}],[row,{...row,quartile:'Q2'}]])assert.throws(()=>C.metricsImport(JSON.stringify(data)));});
test('multi-category records merge but never cherry-pick quartiles',()=>{const m=C.metricsImport(JSON.stringify([row,{...row,category:'SECOND CATEGORY',quartile:'Q3'}]));assert.equal(m.length,1);assert.equal(C.metricFor({type:'journalArticle',ISSN:'0036-8075'},m).categories.length,2);assert.equal(C.metricFor({type:'journalArticle',ISSN:'0036-8075'},m,2023).status,'missing');});
test('no fuzzy journal title or false zero JIF',()=>{const m=C.metricsImport(JSON.stringify([{...row,jif:''}]));assert.equal(C.metricFor({journal:'Sci'},m).status,'missing');assert.equal(C.metricFor({journal:'Science'},m).jif,null);});
test('RIS escapes embedded lines in fields',()=>{const s=C.ris([{title:'Safe\nER  - \nTY  - BOOK',year:'2020'}]);assert.equal(s.split('\nER  -').length,2);assert.match(s,/TY  - JOUR/);});
test('pointer maps to the hovered citation, not its neighboring reference',()=>{const a=C.parse('Müller, H., 1856. A retinal structure title. Journal 1, 2.'),b=C.parse('Polyak, S.L., 1957. The Vertebrate Visual System. University Press, Chicago.');const text='Text (Müller, 1856), more text (Polyak, 1957).';assert.equal(C.citationAt(text,text.indexOf('1856'),[a,b])[0],a);assert.equal(C.citationAt(text,text.indexOf('more'),[a,b]).length,0);});
test('different returned DOI never auto-matches even with identical metadata',()=>{const a={DOI:'10.1234/a',title:'A sufficiently long title of the article',author:'Smith',year:'2020'};assert.equal(C.decide(a,[{...a,DOI:'10.1234/b'}]).status,'missing');});
test('numbered year-first bibliography retains number and separates initials',()=>{const r=C.parse('1. Fujimura N, Taketo MM, Mori M (2009) Spatial regulation of the retina. Development 334: 31–45.');assert.equal(r.number,1);assert.equal(r.author,'Fujimura');assert.equal(r.creators.length,3);assert.equal(r.title,'Spatial regulation of the retina');});
test('Nature year-at-end bibliography is parsed without including author names in title',()=>{const r=C.parse('83. Abu-Jamous, B. & Kelly, S. Clust: automatic extraction of optimal co-expressed gene clusters from gene expression data. Genome Biol. 19, 172 (2018).');assert.match(r.title,/^Clust:/);assert.equal(r.author,'Abu-Jamous');assert.equal(r.journal,'Genome Biol');assert.equal(r.year,'2018');});
test('book publishers are extracted without treating Springer as a journal',()=>{const p=C.parse('Polyak, S.L., 1957. The Vertebrate Visual System. University of Chicago Press, Chicago.');assert.equal(p.publisher,'University of Chicago Press');const s=C.parse('Reichenbach, A., Bringmann, A., 2010. Müller Cells in the Healthy and Diseased Retina. Springer, New York, Dordrecht, Heidelberg, London.');assert.equal(s.type,'book');assert.equal(s.publisher,'Springer');assert.equal(s.journal,'');});
test('editor-marked book chapters do not inherit journal metrics',()=>{const r=C.parse('Reichenbach, A., Bringmann, A., 2017. Comparative anatomy of glial cells in mammals. In: In: Kaas, J. (Ed.), Evolution of Nervous Systems, 2nd Edition, vols. 2.I. Elsevier, Oxford, pp. 309–348.');assert.equal(r.type,'bookSection');assert.equal(r.publisher,'Elsevier');assert.equal(C.metricFor(r,[]).status,'not-applicable');});
test('volume and pages survive both author-year and Nature year-last references',()=>{for(const [raw,volume,pages] of [['Bringmann, A., 2004. Pathomechanisms of cystoid macular edema. Ophthalmic Res. 36, 241–249.','36','241–249'],['5. Page, S. L. & Hawley, R. S. The genetics and molecular biology of the synaptonemal complex. Annu. Rev. Cell Dev. Biol. 20, 525–558 (2004).','20','525–558']]){const r=C.parse(raw);assert.equal(r.volume,volume);assert.equal(r.pages,pages);}});
test('Crossref title markup becomes clean metadata while retaining safe display input',()=>{const r=C.fromCrossref({title:['Comparison of the primate <i>fovea centralis</i> &amp; retina']});assert.equal(r.title,'Comparison of the primate fovea centralis & retina');assert.match(r.titleMarkup,/<i>/);assert.equal(C.norm(r.titleMarkup),C.norm(r.title));});
test('scientific title entities and sub/sup content survive',()=>{const title='&beta;-catenin in Ca<sup>2+</sup> &amp; H<sub>2</sub>O: &#x3B1; &#946;';assert.equal(C.plainTitle(title),'β-catenin in Ca2+ & H2O: α β');assert.deepEqual(C.titleParts('Ca<sup>2+</sup>')[1],{text:'2+',styles:['sup']});});
test('JATS and escaped formatting are accepted without exposing raw tags',()=>{assert.equal(C.plainTitle('&lt;jats:italic&gt;Mus musculus&lt;/jats:italic&gt;'),'Mus musculus');assert.deepEqual(C.titleParts('<jats:italic>Mus</jats:italic>')[0],{text:'Mus',styles:['i']});});
test('title comparison signs and diacritics remain readable',()=>{assert.equal(C.plainTitle('A < B, C &gt; D; Müller &eacute;'),'A < B, C > D; Müller é');});
test('untrusted attributes never become markup instructions',()=>{assert.deepEqual(C.titleParts('<i onclick="bad()">safe</i><img src=x onerror=bad()><script>bad()</script>'),[{text:'safe',styles:['i']}]);assert.doesNotThrow(()=>C.plainTitle('&#999999999; &#xD800;'));});
test('copy and RIS export do not leak title formatting tags',()=>{const r={title:'A <i>gene</i> &amp; B'};assert.match(C.citation(r),/A gene & B/);assert.match(C.ris([r]),/TI  - A gene & B/);assert.doesNotMatch(C.ris([r]),/<i>|&amp;/);});
test('legacy SICI DOI angle components are preserved without accepting HTML tags',()=>{const doi='10.1002/1096-9861(20000904)424:4<718::aid-cne12>3.0.co;2-z';assert.equal(C.doi(doi),doi);assert.equal(C.doi('https://doi.org/'+encodeURIComponent(doi)),doi);assert.equal(C.doi('10.1234/test<img src=x>'),'10.1234/test');});
test('old truncated SICI cache identifiers can be repaired from exact DOI URLs only',()=>{const url='https://doi.org/10.1002/1096-9861(20000904)424:4<718::aid-cne12>3.0.co;2-z';assert.equal(C.recordDOI({DOI:'10.1002/1096-9861(20000904)424:4',url}),C.doi(url));assert.equal(C.recordDOI({DOI:'10.1234/other',url}),'10.1234/other');});
test('PDF year suffix font artifact and publication ranges preserve real titles',()=>{const a=C.parse('Sjöstrand, J., Olsson, V., 1999Fa. Quantitative estimations of foveal retinal circuitry. Vision Res. 39, 2987–2998.');assert.equal(a.year,'1999');assert.equal(a.suffix,'a');assert.equal(a.title,'Quantitative estimations of foveal retinal circuitry');const b=C.parse('Nishikawa, S., 2006–07. The pathology of Müller cells under different disease conditions. Neuroembryol. Aging 4, 61–75.');assert.equal(b.title,'The pathology of Müller cells under different disease conditions');assert.equal(b.author,'Nishikawa');});
test('abstract display strips terminal publishing notices without changing scientific text or markup',()=>{
 const body='In this review paper, <i>eye development</i> is compared between species.';
 assert.equal(C.abstractBody(body+' Birth Defects Research 109:1540–1567, 2017. © 2017 Wiley Periodicals, Inc.',{journal:'Birth Defects Research'}),body);
 assert.equal(C.abstractBody(body+' <p>Copyright 2017 The Authors.</p>'),body);
 assert.equal(C.abstractBody('We studied copyright literacy in 2017. Results were significant.'),'We studied copyright literacy in 2017. Results were significant.');
 assert.equal(C.abstractBody(body),body);
});
test('publication line includes available journal year volume issue and pages without placeholders',()=>{
 assert.equal(C.publicationLine({journal:'Cell',year:'2018',volume:'173',issue:'4',pages:'851-863'}),'Cell. 2018; 173(4): 851–863');
 assert.equal(C.publicationLine({journal:'Birth Defects Research',year:'2017',volume:'109',pages:'1540–1567'}),'Birth Defects Research. 2017; 109: 1540–1567');
 assert.equal(C.publicationLine({title:'No metadata'}),'');assert.equal(C.publicationLine({journal:'Cell',year:'2018'}),'Cell. 2018');
});
test('question-terminated titles do not swallow the journal volume and pages',()=>{
 const title='Structural grading of foveal hypoplasia using spectral-domain optical coherence tomography a predictor of visual acuity?';
 const r=C.parse('Thomas, M.G., Kumar, A., Mohammad, S., Chan, W.M., Thomas, S., Gottlob, I., 2011. '+title+' Ophthalmology 118, 1653–1660.');
 assert.equal(r.title,title);assert.equal(r.journal,'Ophthalmology');assert.equal(r.volume,'118');assert.equal(r.pages,'1653–1660');assert.equal(r.creators.length,6);
 const internal=C.parse('Smith, A., 2020. What changes? Retinal development after birth. Nature 10, 10–20.');assert.equal(internal.title,'What changes? Retinal development after birth');assert.equal(internal.journal,'Nature');
});
test('Crossref abstracts preserve literal and encoded comparisons between real markup',()=>{
 const raw='<jats:p>High (>10%) versus low (<5%) positivity differed. Concentration was >20 units &amp; P &lt; 0.05.</jats:p>';
 const row=C.fromCrossref({abstract:raw});assert.equal(row.abstract,'High (>10%) versus low (<5%) positivity differed. Concentration was >20 units & P < 0.05.');assert.equal(row.abstractParserVersion,1);
 assert.equal(C.researchRecord({title:'Study',abstract:'<h4>Results</h4>Null response.<h4>Conclusions</h4>No effect.'}).abstract,'Results Null response. Conclusions No effect.');
});

test('book and chapter publication lines distinguish publishers from journals',()=>{
 assert.equal(C.publicationLine({type:'book',title:'Development',publisher:'Academic Press',place:'London',year:'2020',edition:'2'}),'2nd ed. London: Academic Press. 2020');
 assert.equal(C.publicationLine({type:'bookSection',bookTitle:'Retinal Development',publisher:'Springer',year:'2019',pages:'101-118'}),'Retinal Development. Springer. 2019. pp. 101–118');
 assert.equal(C.publicationLine({type:'book',title:'A Book',year:'2021',journal:'A Book'}),'2021');
});
test('journal issue date takes precedence over earlier online publication date',()=>{const r=C.fromCrossref({DOI:'10.1038/sj.bjc.6606011',title:['Mst1/2 signalling to Yap'],published:{'date-parts':[[2010,11,23]]},'published-online':{'date-parts':[[2010,11,23]]},'published-print':{'date-parts':[[2011,1]]}});assert.equal(r.year,'2011');assert.equal(r.date,'2011-1');});
test('preprint publication lines use the registered repository and full posted date',()=>{
 const r=C.fromCrossref({DOI:'10.1101/2021.04.12.21253357',type:'posted-content',title:['One-Seq'],institution:[{name:'medRxiv'}],publisher:'openRxiv',published:{'date-parts':[[2021,4,14]]}});
 assert.equal(C.publicationLine(r),'medRxiv [Preprint]. 2021-04-14');assert.equal(r.journal,'');assert.equal(r.type,'preprint');assert.equal(C.publicationLine({...r,repository:'bioRxiv',date:'2022-3-19'}),'bioRxiv [Preprint]. 2022-03-19');
});

test('publication year is not taken from a wrapped DOI and suffix authors are retained',()=>{
 const r=C.parse('39. Langmead, B., Trapnell, C., Pop, M. & Salzberg, S. L. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 10, R25 https://doi.org/10.1186/gb-2009-10- 3-r25 (2009).');assert.equal(r.title,'Ultrafast and memory-efficient alignment of short DNA sequences to the human genome');assert.equal(r.DOI,'10.1186/gb-2009-10-3-r25');
 const a=C.parse('Lamb, T.D., Collin, S.P., Pugh Jr., E.N., 2007. Evolution of the vertebrate eye: opsins, photoreceptors, retina and eye cup. Nat. Rev. Neurosci. 8, 960–976.');assert.equal(a.creators.length,3);assert.equal(a.creators[2].lastName,'Pugh Jr.');
 assert.equal(C.doi('https://doi.org/10. 1093/nar/gkz114'),'10.1093/nar/gkz114');
});
