const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
global.CiteLensCore=require('../addon/core.js');const E=require('../addon/epmetrics.js');
// Synthetic metrics only. These tests verify matching, not real journal scores.
function payload(){return {schema:1,provenance:{version:'test',importedAt:'2026-10-04'},aliases:[{journal:'Example J',issn:'0036-8075'}],history:{Example:{meta:{journalName:'Example Journal',issn:'0036-8075',eissn:'1095-9203'},dataByYear:[{jcrYear:'2024',jif:'0',category:[{category:'A',quartile:'Q1'},{category:'B',quartile:'Q3'}]},{jcrYear:'2025',jif:'N/A',category:[{category:'A',quartile:'N/A'}]}]}}};}
test('exact ISSN and eISSN match, with all category quartiles and true zero preserved',()=>{const i=E.build(payload());for(const ISSN of ['0036-8075','1095-9203']){const m=E.lookup({ISSN},i,2024);assert.equal(m.jif,0);assert.deepEqual(m.categories.map(x=>x.quartile),['Q1','Q3']);assert.equal(m.match,'ISSN / eISSN');}});
test('N/A remains unknown; dataset publication year never substitutes for metric year',()=>{const m=E.lookup({ISSN:'0036-8075'},E.build(payload()));assert.equal(m.metricYear,2025);assert.equal(m.jif,null);assert.equal(m.categories[0].quartile,null);assert.equal(m.history.length,2);});
test('unknown ISSN cannot fall through to a coincidentally matching title',()=>{assert.equal(E.lookup({ISSN:'0028-0836',journal:'Example Journal'},E.build(payload())).status,'missing');});
test('full journal and explicitly mapped abbreviation resolve; fuzzy fragments do not',()=>{const i=E.build(payload());assert.equal(E.lookup({journal:'example journal'},i).status,'available');assert.equal(E.lookup({journal:'Example J.'},i).status,'available');assert.equal(E.lookup({journal:'Example'},i).status,'available');assert.equal(E.lookup({journal:'Exampl J'},i).status,'missing');});
test('ambiguous abbreviation and conflicting identifiers are never silently selected',()=>{const p=payload();p.history.Other={meta:{journalName:'Other Journal',issn:'0028-0836'},dataByYear:p.history.Example.dataByYear};p.aliases.push({journal:'Example J',issn:'0028-0836'});const i=E.build(p);assert.equal(E.lookup({journal:'Example J'},i).status,'ambiguous');assert.equal(E.lookup({ISSN:'0036-8075, 0028-0836'},i).status,'ambiguous');});
test('explicit missing year and inapplicable publications are distinct',()=>{const i=E.build(payload());assert.equal(E.lookup({ISSN:'0036-8075'},i,2022).status,'missing');assert.equal(E.lookup({ISSN:'0036-8075',type:'book'},i).status,'not-applicable');});
test('malformed data fail safely and invalid records are counted',()=>{assert.throws(()=>E.build({schema:1}),/格式/);const p=payload();p.history.Bad={meta:{issn:'bad'},dataByYear:[]};const i=E.build(p);assert.equal(i.skipped,1);p.history.Example.dataByYear.push(p.history.Example.dataByYear[0]);assert.throws(()=>E.build(p),/重复/);});
test('latest metric year wins across enabled sources; ambiguous imports remain explicit',()=>{const ctx={CiteLensCore:global.CiteLensCore,CiteLensEPMetrics:E};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/services.js'),'utf8'),ctx);const S=ctx.CiteLensServices;S.epIndex=E.build(payload());const r={ISSN:'0036-8075'},local={issns:['0036-8075'],journal:'Example Journal',metricYear:2024,jif:9,categories:[],source:'User source'};S.state.metrics=[local];assert.equal(S.metricFor(r).metricYear,2025);S.state.metrics.push({...local});assert.equal(S.metricFor(r).status,'ambiguous');S.state.metrics=[];assert.equal(S.metricFor(r).provider,'easypubmed');S.state.settings.easyPubMedEnabled=false;assert.equal(S.metricFor(r).provider,'easypubmed');});

test('censored JIF remains <0.1 instead of zero or missing',()=>{const p=payload();p.history.Example.dataByYear[1].jif='<0.1';assert.equal(E.lookup({ISSN:'0036-8075'},E.build(p)).jif,'<0.1');});
