const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('destroyed Reader DOM cannot prevent teardown of hooks and state',()=>{const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/themes.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/main.js'),'utf8'),ctx);const P=ctx.CiteLens,reader={},dead=new Proxy({},{get(){throw Error("can't access dead object")}});let hooks=0,observers=0;P.readers.set(reader,{doc:dead,observer:{disconnect(){observers++;}},hooks:[()=>{throw Error('dead listener')},()=>hooks++]});P.panels.set(reader,dead);assert.doesNotThrow(()=>P.detach(reader));assert.equal(P.readers.size,0);assert.equal(P.panels.size,0);assert.equal(hooks,1);assert.equal(observers,1);assert.doesNotThrow(()=>P.detach(reader));});

test('late shutdown cannot unregister a replacement instance or delete its global owner',async()=>{
 const resources=new Map(),protocol={ALLOW_CONTENT_ACCESS:1,hasSubstitution:n=>resources.has(n),setSubstitutionWithFlags:(n,u)=>resources.set(n,u),setSubstitution:(n,u)=>u?resources.set(n,u):resources.delete(n)},Zotero={initializationPromise:Promise.resolve(),uiReadyPromise:Promise.resolve(),getMainWindow:()=>({setInterval:()=>1,clearInterval(){}}),getMainWindows:()=>[],Reader:{_readers:[],registerEventListener(){},unregisterEventListener(){}}};let serial=0;
 const create=()=>{let release;const ctx={Zotero,Services:{uuid:{generateUUID:()=>String(++serial)},io:{newURI:x=>x,getProtocolHandler:()=>({QueryInterface:()=>protocol})}},Components:{interfaces:{nsIResProtocolHandler:{}}},CiteLensServices:{state:{settings:{networkEnabled:false}},init:async()=>{},stop:async()=>{}},CiteLensTranslation:{init(){},stop(){}},CiteLensThemes:{initialize:async()=>{},stop(){}},CiteLensUpdater:{start:async()=>{},stop(){}},CiteLensCareer:{stop(){}},CiteLensNetwork:{cancelNetworkWork(){},setEnabled:async()=>{},start:async()=>{},scheduleWarmup(){},stop:()=>new Promise(r=>release=r)},CiteLensModels:{start:async()=>{},stop:async()=>{}},CiteLensSemantic:{start(){},stop:async()=>{}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/main.js'),'utf8'),ctx);Object.assign(ctx.CiteLens,{version:'1.0.5',rootURI:'file:///fixture/'});return {P:ctx.CiteLens,release:()=>release()};};
 const old=create();await old.P.start();const pending=old.P.stop();assert.equal(old.P.stop(),pending);const next=create();await next.P.start();old.release();await pending;assert.equal(Zotero.CiteLens,next.P);assert.equal(resources.has(next.P.assetResource),true);assert.equal(resources.has(old.P.assetResource),false);
 resources.delete(next.P.assetResource);next.P.ensureAssets();assert.equal(resources.has(next.P.assetResource),true);const final=next.P.stop();next.release();await final;assert.equal(resources.size,0);
});
test('pending reference task times out without blocking other UI tasks and can still finish',async()=>{const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/ui.js'),'utf8'),ctx);let timeout,cleared=0,done;const w={setTimeout:f=>(timeout=f,1),clearTimeout:()=>cleared++},pending=new Promise(r=>done=r);const bounded=ctx.CiteLensUI.waitFor(pending,w,50,'still loading');assert.equal(await ctx.CiteLensUI.waitFor(Promise.resolve('settings ready'),{setTimeout:()=>2,clearTimeout(){}},50,'error'),'settings ready');timeout();await assert.rejects(bounded,/still loading/);done([]);await new Promise(r=>setImmediate(r));assert.equal(cleared,1);});
test('citation views share one calculation, reuse completed results and retry failures only explicitly',async()=>{const C=require('../addon/core.js'),record={title:'Retinal development',author:'Smith',year:'2020',raw:'Smith 2020 retinal development'},key=C.identity(record),locations=[{position:{pageIndex:1}}];let calls=0,fail=true,stored;const ctx={Map,Set,Zotero:{logError(){}},CiteLensCore:C,CiteLensNetwork:{readCache:async()=>stored,writeCache:async(_kind,_key,value)=>{stored=value;},compute:async()=>{calls++;if(fail)throw Error('worker unavailable');return new Map([[key,locations]]);}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/main.js'),'utf8'),ctx);const P=ctx.CiteLens,reader={},state={citationPages:new Map(),referenceCacheKey:'pdf-fingerprint'};P.references=async()=>[record];P.compactCitationPages=async x=>x;P.readers.set(reader,state);await assert.rejects(P.citationLocations(reader,record),/unavailable/);await assert.rejects(P.citationLocations(reader,record),/unavailable/);assert.equal(calls,1);fail=false;const result=await Promise.all([P.citationLocations(reader,record,{retry:true}),P.citationLocations(reader,record)]);assert.equal(calls,2);assert.equal(result[0],locations);assert.equal(result[1],locations);await P.citationLocations(reader,record);assert.equal(calls,2);delete state.locationIndex;await P.citationLocations(reader,record);assert.equal(calls,2);assert.equal(state.locationIndex,stored);});
test('pending network and model initialization do not delay toolbar and window startup',async()=>{let hooks=0,intervals=0;const pending=new Promise(()=>{}),ctx={Zotero:{uiReadyPromise:Promise.resolve(),getMainWindow:()=>({setInterval:()=>++intervals}),getMainWindows:()=>[],Reader:{_readers:[],registerEventListener:()=>hooks++}},Services:{uuid:{generateUUID:()=> 'fixture'}},CiteLensServices:{state:{settings:{networkEnabled:false}},init:async()=>{}},CiteLensTranslation:{init(){}},CiteLensThemes:{initialize:async()=>{}},CiteLensSemantic:{start(){}},CiteLensUpdater:{start:async()=>{}},CiteLensNetwork:{cancelNetworkWork(){},setEnabled:async()=>{},start:()=>pending},CiteLensModels:{start:()=>pending}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/main.js'),'utf8'),ctx);const P=ctx.CiteLens;Object.assign(P,{version:'1.0.5',ensureAssets(){}});await P.start();assert.equal(hooks,1);assert.equal(intervals,1);assert.equal(ctx.Zotero.CiteLens,P);});
