const base=Zotero.CiteLensTestRoot,{CiteLens:P,CiteLensCore:C,CiteLensServices:S,CiteLensUI:U}=Zotero.CiteLensQA,r=Zotero.Reader._readers.find(x=>x._internalReader?._primaryView?._iframeWindow?.PDFViewerApplication?.pdfDocument.numPages===36),d=r._iframeWindow.document,report={run:'ui-behavior',checks:[]};const check=(name,ok,details={})=>{report.checks.push({name,ok,...details});if(!ok)throw Error(name);};
const lookup=S.lookup,settings={...S.state.settings};
try{
 S.state.settings.autoAuthors=false;
 await Zotero.Reader.open(r.itemID);await Zotero.Promise.delay(250);for(const n of d.querySelectorAll('.cl-overlay,.cl-floating'))n.remove();r._internalReader._primaryView._onSetOverlayPopup(null);let calls=0;S.lookup=async()=>{calls++;return {status:'missing',ranked:[]};};S.state.settings.autoLookup=true;S.state.settings.networkConsent=true;
 const record=C.parse('Smith, A., 2020. A test title for UI behavior. Journal 1, 2.');const panelCard=U.card(d,record,r);d.body.append(panelCard);await Zotero.Promise.delay(1100);check('Listing a card does not trigger automatic network lookup',calls===0);panelCard.remove();
 const hoverCard=U.card(d,record,r,{compact:true});d.body.append(hoverCard);await Zotero.Promise.delay(1100);check('Opted-in hover triggers exactly one lookup',calls===1,{calls});hoverCard.remove();
 S.state.settings.autoLookup=false;const unsafe=U.card(d,{...record,title:'<img src=x onerror=alert(1)>',raw:'<script>bad()</script>'},r);d.body.append(unsafe);check('Metadata is rendered as text, not executable markup',!unsafe.querySelector('img,script')&&!unsafe.textContent.includes('<img'));unsafe.remove();
 let saved;U.saveDialog(d,{...record,title:'CiteLens UI Save '+Date.now()},U.context(r,22),result=>saved=result);const dialog=[...d.querySelectorAll('.cl-dialog')].at(-1),collectionInput=[...dialog.querySelectorAll('label')].find(x=>x.textContent.startsWith('新建文献夹'))?.querySelector('input');check('Save target input is present',!!collectionInput,{labels:[...dialog.querySelectorAll('label')].map(x=>x.textContent),heading:dialog.textContent.slice(0,120)});collectionInput.closest('details').open=true;collectionInput.value='CiteLens UI QA';const save=[...dialog.querySelectorAll('button')].find(x=>x.textContent==='核对并保存');save.click();await Zotero.Promise.delay(50);save.click();for(let n=0;n<80&&!saved&&d.contains(dialog);n++)await Zotero.Promise.delay(100);check('Actual save button creates an item and closes dialog',!!saved&&!d.contains(dialog));check('New collection input reaches library save service',!!saved.collectionID);
 const holder=U.dialog(d,'键盘测试');holder.root.dispatchEvent(new d.defaultView.KeyboardEvent('keydown',Components.utils.cloneInto({key:'Escape',bubbles:true},d.defaultView)));check('Escape closes the dialog',!holder.overlay.isConnected);
 report.passed=true;
}catch(e){report.passed=false;report.error=String(e);report.stack=e.stack;}
finally{S.lookup=lookup;S.state.settings=settings;await S.persist();for(const e of d.querySelectorAll('.cl-overlay'))e.remove();await IOUtils.writeUTF8(base+'/test-results/ui-behavior.json',JSON.stringify(report,null,2));}
return report;
