const base=Zotero.CiteLensTestRoot,version=JSON.parse(await IOUtils.readUTF8(Zotero.CiteLensTestRoot+'/addon/manifest.json')).version,report={run:'production-package',checks:[]},check=(name,ok)=>{report.checks.push({name,ok});if(!ok)throw Error(name);};
try {
 if(Services.dirsvc.get('ProfD',Components.interfaces.nsIFile).path!==base+'/qa-profile')throw Error('QA profile required');
 await Zotero.CiteLens.stop();const {AddonManager}=ChromeUtils.importESModule('resource://gre/modules/AddonManager.sys.mjs');const install=await AddonManager.getInstallForFile(Zotero.File.pathToFile(base+'/dist/paper-nexus-'+version+'.xpi'));await install.install();for(let n=0;n<100&&!Zotero.CiteLens;n++)await Zotero.Promise.delay(100);const P=Zotero.CiteLens;check('Production XPI starts in Zotero',!!P&&P.version===version);const addon=await AddonManager.getAddonByID('cite-lens@local.research');check('Production addon is active',addon.isActive);
 const r=Zotero.Reader._readers.find(x=>x._internalReader?._primaryView?._iframeWindow?.PDFViewerApplication?.pdfDocument.numPages===36);await Zotero.Reader.open(r.itemID);const d=r._iframeWindow.document,refs=await P.references(r),poly=refs.find(x=>x.author==='Polyak'&&x.year==='1957');check('Production package reads original book reference',!!poly);P.showPanel(r,{record:poly});await Zotero.Promise.delay(650);const card=d.querySelector('.cl-root .cl-card');check('Production card contains no redundant detail panels',!card.querySelector('.cl-tabs,.cl-metadata')&&card.querySelector('.cl-title').textContent===poly.title);card.querySelector('.cl-more').click();check('Production menu has the four requested actions',[...card.querySelectorAll('.cl-menu button')].map(x=>x.textContent).join('|')==='更新信息|另存到…|复制引用|设置');[...card.querySelectorAll('button')].find(x=>x.textContent==='另存到…').click();await Zotero.Promise.delay(150);const dialog=[...d.querySelectorAll('.cl-dialog')].at(-1),labels=[...dialog.querySelectorAll('label')];check('Library and collection are presented before metadata',labels[0].textContent.startsWith('文献库')&&labels[1].textContent.startsWith('文献夹'));
 const b=dialog.getBoundingClientRect(),canvas=d.createElement('canvas');canvas.width=Math.ceil(b.width+24)*2;canvas.height=Math.ceil(b.height+24)*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.drawWindow(d.defaultView,b.x-12,b.y-12,canvas.width/2,canvas.height/2,'#fff');await IOUtils.write(base+'/test-results/production-save.png',Uint8Array.from(d.defaultView.atob(canvas.toDataURL('image/png').split(',')[1]),x=>x.charCodeAt(0)));d.querySelector('.cl-overlay')?.remove();P.panels.get(r)?.remove();P.panels.delete(r);
 P.showPanel(r,{record:{DOI:'10.1038/s41467-023-37408-w',title:'A-MYB and BRDT-dependent RNA Polymerase II pause release orchestrates transcriptional regulation in mammalian meiosis',journal:'Nature Communications',type:'journalArticle',year:'2023'}});await Zotero.Promise.delay(600);const authors=d.querySelector('.cl-root .cl-card');check('Production package loads six ordered author slots from retained cache',authors.querySelectorAll('.cl-author-slot').length===6&&authors.querySelector('.cl-author-gap')&&CiteLensCore.norm([...authors.querySelectorAll('.cl-author-slot')].at(-1).title)==='charles g danko');check('Production main card omits verification and role prompts',!authors.querySelector('.cl-eyebrow').textContent.includes('核验')&&!authors.querySelector('.cl-corresponding'));check('Production actions are in top line',!!authors.querySelector('.cl-eyebrow .cl-card-tools')&&!authors.querySelector(':scope > .cl-actions'));check('Production main metrics omit JCI and JCR prefix',!authors.querySelector('.cl-journal').textContent.includes('JCI')&&!authors.querySelector('.cl-journal').textContent.includes('JCR'));check('Production DOI is in journal row after quartile',!!authors.querySelector('.cl-journal .cl-doi')&&authors.querySelector('.cl-journal').lastElementChild.classList.contains('cl-doi'));P.panels.get(r)?.remove();P.panels.delete(r);
 P.showPanel(r,{record:{title:'Comparison of development of the primate <i>fovea centralis</i> with peripheral retina',type:'bookSection',year:'2006',DOI:'10.1017/cbo9780511541629.009'}});await Zotero.Promise.delay(100);const titleCard=d.querySelector('.cl-root .cl-card');check('Production title renders inline italics without visible markup',titleCard.querySelector('.cl-title i')?.textContent==='fovea centralis'&&!titleCard.querySelector('.cl-title').textContent.includes('<i>'));titleCard.querySelector('.cl-more').click();titleCard._menu.lastElementChild.click();check('Production settings has no tabs or provider names',!!d.querySelector('.cl-settings')&&!d.querySelector('.cl-settings .cl-tabs')&&!/Green Frog|Ethereal|EasyPub/.test(d.querySelector('.cl-settings').textContent));d.querySelector('.cl-overlay').remove();P.panels.get(r)?.remove();P.panels.delete(r);
 const file=await IOUtils.readUTF8(base+'/qa-library/cite-lens/state.json');check('Upgrade retained reading list',JSON.parse(file).queue.some(x=>x.record.year==='1957'));check('Upgrade retained appearance preferences',JSON.parse(file).settings.theme==='paper'&&JSON.parse(file).settings.fontSize===14);report.passed=true;
}catch(e){report.passed=false;report.error=String(e);report.stack=e.stack;}
await IOUtils.writeUTF8(base+'/test-results/production-package.json',JSON.stringify(report,null,2));return report;
