const base=Zotero.CiteLensTestRoot,{CiteLensAbstracts:A,CiteLensServices:S,CiteLens:P,CiteLensUI:U}=Zotero.CiteLensQA,report={run:'pubmed-pmc',version:P.version,checks:[],live:[]},check=(name,ok)=>{report.checks.push({name,ok});if(!ok)throw Error(name);},transport=A.transport,key=A.apiKey();
try{
 const r=Zotero.Reader._readers.find(r=>r._internalReader?._primaryView?._iframeWindow?.PDFViewerApplication?.pdfDocument.numPages===36),record=(await P.references(r)).find(x=>/Spatial Profile of Macular Pigments/i.test(x.title));
 const credentialFile=base+'/test-results/ncbi-credential.txt';const credential=await IOUtils.exists(credentialFile)?(await IOUtils.readUTF8(credentialFile)).trim():'';report.apiKeyUsed=!!credential;A.apiKey(credential);A.transport=(url,options)=>url.includes('ncbi.nlm.nih.gov')?transport(url,options):Promise.reject(Error('other providers disabled for NCBI test'));
 for(const input of [record,{DOI:'10.1371/journal.pone.0059247',title:'Vax1/2 Genes Counteract Mitf-Induced Respecification of the Retinal Pigment Epithelium',year:'2013',author:'Ou'}]){const start=Date.now(),value=await A.lookup(S,input,{force:true});report.lastStatus=value.status;check('Direct PubMed retrieves validated record '+input.author,value.status==='available'&&value.source==='PubMed'&&value.text.length>200&&!!value.record.PMID);report.live.push({source:value.source,PMID:value.record.PMID,PMCID:value.record.PMCID,length:value.text.length,ms:Date.now()-start});if(input.author==='Ou'){const pmc=await A.lookup(S,{...input,PMCID:value.record.PMCID},{force:true});check('Direct PMC extracts front abstract and validates article identity',pmc.status==='available'&&pmc.source==='PMC'&&pmc.text.length>200);report.live.push({source:pmc.source,length:pmc.text.length,PMCID:pmc.record.PMCID});}}
 const fixture='<PubmedArticleSet><PubmedArticle><MedlineCitation><PMID>1</PMID><Article><Journal><Title>Journal</Title><JournalIssue><PubDate><Year>2020</Year></PubDate></JournalIssue></Journal><ArticleTitle>Safe &amp; relevant title</ArticleTitle><Abstract><AbstractText Label="METHODS">Methods with H<sub>2</sub>O.</AbstractText><AbstractText Label="RESULTS">Different results.</AbstractText></Abstract><AuthorList><Author><LastName>Smith</LastName></Author></AuthorList></Article></MedlineCitation><PubmedData><ArticleIdList><ArticleId IdType="doi">10.1234/own</ArticleId></ArticleIdList><ReferenceList><Reference><ArticleIdList><ArticleId IdType="doi">10.1234/wrong</ArticleId></ArticleIdList></Reference></ReferenceList></PubmedData></PubmedArticle></PubmedArticleSet>',parsed=A.pubmedRecords(fixture)[0];check('Nested cited DOI cannot replace the article DOI',parsed.DOI==='10.1234/own');check('Structured sections, entities and subscripts remain readable',parsed.abstract.includes('METHODS\nMethods with H2O.\n\nRESULTS')&&parsed.title==='Safe & relevant title');check('Mismatch rejected despite PubMed identity match',!A.select({PMID:'1',title:'Completely different geological rocks and fossils',year:'1990'},[parsed]));
 const doc=r._iframeWindow.document;U.settingsDialog(doc);const field=doc.querySelector('.cl-api-key');check('Optional API credential is masked and lives in secondary settings',field.type==='password'&&field.closest('details')&&!field.closest('details').open);field.value='synthetic-ncbi-key-123456';field.dispatchEvent(new doc.defaultView.Event('change'));check('API credential saved only to local preferences',A.apiKey()===field.value&&!JSON.stringify(S.state).includes(field.value));field.value='';field.dispatchEvent(new doc.defaultView.Event('change'));check('User can remove the saved API credential',A.apiKey()==='');doc.querySelector('.cl-overlay').remove();report.passed=true;
}catch(e){report.passed=false;report.error=String(e);report.stack=e.stack;}
finally{A.transport=transport;A.apiKey(key);if(await IOUtils.exists(base+'/test-results/ncbi-credential.txt'))await IOUtils.remove(base+'/test-results/ncbi-credential.txt');await IOUtils.writeUTF8(base+'/test-results/pubmed-pmc.json',JSON.stringify(report,null,2));}return report;
