const base=Zotero.CiteLensTestRoot,{CiteLens:P,CiteLensUI:U}=Zotero.CiteLensQA,r=Zotero.Reader._readers[0],d=r._iframeWindow.document,report={run:'compact-brand',checks:[]},check=(name,ok)=>{report.checks.push({name,ok});if(!ok)throw Error(name);};let frame;
const capture=async(doc,node,name)=>{await Zotero.Promise.delay(150);const b=node.getBoundingClientRect(),canvas=doc.createElement('canvas');canvas.width=Math.ceil(b.width)*2;canvas.height=Math.ceil(b.height)*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.drawWindow(doc.defaultView,b.x,b.y,b.width,b.height,'#fff');await IOUtils.write(base+'/test-results/'+name+'.png',Uint8Array.from(doc.defaultView.atob(canvas.toDataURL('image/png').split(',')[1]),x=>x.charCodeAt(0)));};
try{
 await Zotero.Reader.open(r.itemID);const button=d.querySelector('[data-cite-lens=toolbar]');check('Reader entry uses icon only and remains named for accessibility',button.textContent===''&&button.getAttribute('aria-label')==='Paper Nexus'&&button.title==='Paper Nexus');check('Reader icon occupies a compact button',button.getBoundingClientRect().width<=34&&button.querySelector('img').width===24);check('New packaged image loads',button.querySelector('img').complete&&button.querySelector('img').naturalWidth===256);
 button.click();await Zotero.Promise.delay(80);check('Icon-only button opens the literature panel',!!d.querySelector('.cl-root'));check('Current interface omits former Chinese name',!d.querySelector('.cl-root').textContent.includes('研联')&&Zotero.getMainWindow().document.getElementById('cite-lens-tools').getAttribute('label')==='Paper Nexus');d.querySelector('.cl-root').remove();P.panels.delete(r);await capture(d,d.querySelector('.toolbar'),'brand-toolbar');
 frame=d.createElement('iframe');frame.src='about:blank';frame.style.cssText='position:fixed;left:0;top:0;width:620px;height:280px;z-index:900000;border:0';d.body.append(frame);await Zotero.Promise.delay(80);const fd=frame.contentDocument;fd.body.style.cssText='margin:0;background:#fff;font:12px sans-serif';
 for(const [label,color,ink] of [['Light','#ffffff','#243730'],['Paper','#f6f1e7','#243730'],['Dark','#1a2623','#eef3ef']]){const row=U.el(fd,'div');row.style.cssText='display:flex;align-items:center;justify-content:space-around;height:90px;background:'+color+';color:'+ink;row.append(U.el(fd,'span',label));for(const size of [20,24,32,48,64])row.append(U.logo(fd,size));fd.body.append(row);}await Zotero.Promise.delay(150);check('Icon size sheet loads every production asset',[...fd.querySelectorAll('img')].every(img=>img.complete&&img.naturalWidth===256));await capture(fd,fd.body,'brand-sizes');report.passed=true;
}catch(e){report.passed=false;report.error=String(e);report.stack=e.stack;}
finally{frame?.remove();await IOUtils.writeUTF8(base+'/test-results/compact-brand.json',JSON.stringify(report,null,2));}return report;
