const {test}=require('node:test'),assert=require('node:assert/strict'),V=require('../addon/network-view.js');
test('labels follow entity identity in either mode; author labels never acquire publication years',()=>{const node={title:'Retinal photoreceptor differentiation',author:'Masuda',creators:[{lastName:'Brat'}],year:2015};assert.equal(V.nodeLabel(node,'topics'),node.title);assert.equal(V.nodeLabel({...node,author:'Other',creators:[{lastName:'Different'}]},'topics'),node.title);assert.equal(V.nodeLabel({kind:'author',title:'Anita Hendrickson',year:2015},'authors'),'Anita Hendrickson');assert.equal(V.nodeLabel({kind:'topic',title:'Retinal development'},'authors'),'Retinal development');assert.equal(V.nodeLabel({...node,title:''},'topics'),'');assert.ok(V.nodeLabel({...node,title:'Long scientific title '.repeat(10)},'topics').length<=52);});
test('pinch keeps the cursor on the same world coordinate throughout smoothing',()=>{const camera={x:12,y:34,k:.5},x=280,y=170,wx=(x-camera.x)/camera.k,wy=(y-camera.y)/camera.k,target=V.zoom(camera,1.7,x,y);let n=0;while(V.step(camera,target,16)){assert.ok(Math.abs((x-camera.x)/camera.k-wx)<1e-8);assert.ok(Math.abs((y-camera.y)/camera.k-wy)<1e-8);assert.ok(++n<100);}assert.equal(camera.k,.85);});
test('precision trackpad pans on both axes, pinch and discrete mouse wheel zoom',()=>{assert.deepEqual(V.wheel({deltaMode:0,deltaX:12.5,deltaY:-3.2}),{x:-12.5,y:3.2,zoom:1});assert.ok(V.wheel({deltaMode:0,deltaX:0,deltaY:-3.2,ctrlKey:true}).zoom>1);assert.ok(V.wheel({deltaMode:1,deltaX:0,deltaY:3}).zoom<1);assert.ok(V.wheel({deltaMode:0,deltaX:0,deltaY:120}).zoom<1);});
test('large event spikes and reversed gestures remain bounded, reduced motion settles immediately',()=>{const c={x:0,y:0,k:1};let t=V.zoom(c,1e20,50,50);assert.equal(t.k,5);t=V.zoom(c,1e-20,50,50);assert.equal(t.k,.06);assert.equal(V.step(c,t,100,true),false);assert.deepEqual(c,t);});
test('dense overview retains every paper location and focused neighborhoods retain identity',()=>{const papers=Array.from({length:100},(_,i)=>({id:'p'+i,kind:'paper',group:'g',x:i,y:i})),hub={id:'g',kind:'author',members:papers.map(p=>p.id)},model={nodes:[...papers,hub],edges:papers.map(p=>({source:'g',target:p.id,kind:'author'})),matches:[]},index=V.index(model);const overview=V.scene(model,index,{k:.3});assert.equal(overview.nodes.length,101);const focus=V.scene(model,index,{k:.3,selected:'g',focused:true});assert.equal(focus.nodes.length,101);model.matches=['p99'];assert.ok(V.scene(model,index,{k:.3}).nodes.some(n=>n.id==='p99'));});
test('screen label grid prevents overlap and preserves priority labels',()=>{const candidates=[{id:'a',priority:1,rect:{x:10,y:10,w:90,h:18}},{id:'b',priority:9,rect:{x:20,y:10,w:90,h:18}},{id:'c',priority:2,rect:{x:10,y:40,w:90,h:18}}];assert.deepEqual(V.labels(candidates,300,300).map(n=>n.id),['b','c']);});

test('one visual line merges relation types and reciprocal citations without counting repeated evidence',()=>{const nodes=[{id:'a',kind:'paper'},{id:'b',kind:'paper'}],edges=[{source:'a',target:'b',kind:'cites',evidence:[{pageIndex:1},{pageIndex:2}]},{source:'a',target:'b',kind:'cites',evidence:[{pageIndex:3}]},{source:'b',target:'a',kind:'cites'},{source:'a',target:'b',kind:'similarity',evidence:[{score:.8}]},{source:'a',target:'b',kind:'author',evidence:[{authorKey:'A'},{authorKey:'B'},{authorKey:'A'}]}],model={nodes,edges},scene=V.scene(model,V.index(model));assert.equal(scene.edges.length,1);const edge=scene.edges[0];assert.equal(edge.count,5);assert.deepEqual(edge.directions,['forward','backward']);assert.deepEqual(edge.kinds,['author','cites','similarity']);assert.ok(V.lineWidth(5)>V.lineWidth(1));assert.equal(V.lineWidth(10000),3.2);});
test('distinct node pairs each keep one line and duplicate layout hints do not thicken it',()=>{const nodes=['a','b','c'].map(id=>({id,kind:'paper'})),edges=[{source:'a',target:'b',kind:'topic'},{source:'b',target:'a',kind:'topic'},{source:'a',target:'c',kind:'topic'}],model={nodes,edges},scene=V.scene(model,V.index(model));assert.equal(scene.edges.length,2);assert.ok(scene.edges.every(e=>e.count===1));});
test('search highlights matches and direct neighbours even above forty connections; no-match fades everything',()=>{
 const nodes=Array.from({length:100},(_,i)=>({id:'n'+i,kind:'author'})),model={nodes,edges:nodes.slice(1,65).map(n=>({source:'n0',target:n.id,kind:'coauthor',evidence:[{paperID:n.id}]})),searchActive:true,matches:['n0']},index=V.index(model);
 const e=V.emphasis(model,index);assert.equal(e.near.size,65);assert.ok(!e.near.has('n90'));model.matches=[];assert.equal(V.emphasis(model,index).near.size,0);model.searchActive=false;assert.equal(V.emphasis(model,index).near,null);assert.equal(V.emphasis(model,index,{selected:'n0'}).near.size,65);
 const first=V.scene(model,index),second=V.scene(model,index,{selected:'n1'});assert.equal(first.edges,second.edges);
});
test('overview shows one stable representative per community; entering and leaving never exposes hover labels from hidden members',()=>{
 const nodes=[{id:'a',kind:'author',title:'Anita',members:['p1','p2'],x:0,y:0},{id:'b',kind:'author',title:'Jan',members:['p1'],x:10,y:0},{id:'c',kind:'author',title:'Other',members:['p3'],x:100,y:0}],model={nodes,edges:[{source:'a',target:'b',kind:'coauthor',evidence:[{paperID:'p1'}]}],communities:[{id:'community:a',members:['a','b'],x:5,y:0,color:0},{id:'community:c',members:['c'],x:100,y:0,color:1}],matches:['b']},i=V.index(model);
 const overview=V.scene(model,i);assert.equal(overview.nodes.length,2);assert.equal(overview.nodes[0].kind,'community');assert.equal(overview.nodes[0].title,'Anita');assert.deepEqual(overview.matches,['community:a']);assert.ok(!overview.index.byID.has('b'));
 const detail=V.scene(model,i,{community:'community:a'});assert.deepEqual(detail.nodes.map(n=>n.id),['a','b']);assert.equal(detail.edges.length,1);assert.deepEqual(detail.matches,['b']);assert.equal(V.scene(model,i).nodes,overview.nodes);
});
test('topic search can retain multiple matching groups without lighting unrelated neighbours',()=>{const model={searchActive:true,searchGroups:true,matches:['a','c']},i={adj:new Map([['a',new Set(['a','b'])],['c',new Set(['c','d'])]])};assert.deepEqual([...V.emphasis(model,i).near].sort(),['a','c']);});

test('pointer attraction stays local, releases to rest and preserves graph coordinates',()=>{
 const nodes=[{id:'a',x:0,y:0},{id:'b',x:36,y:0}],camera={x:0,y:0,k:1},saved=JSON.stringify(nodes);
 assert.equal(V.nearest(nodes,{x:18,y:0},camera,'a').id,'a');
 assert.equal(V.nearest(nodes,{x:35,y:0},camera,'a').id,'b');
 assert.equal(V.nearest(nodes,{x:120,y:0},camera,'a'),null);
 const offsets=new Map();for(let i=0;i<120;i++)V.magnetic(offsets,new Map([['a',{x:8,y:2}]]),16);
 assert.ok(Math.abs(offsets.get('a').x-8)<.05);let running=true;
 for(let i=0;i<180;i++)running=V.magnetic(offsets,new Map(),16);
 assert.equal(running,false);assert.equal(offsets.size,0);assert.equal(JSON.stringify(nodes),saved);
 V.magnetic(offsets,new Map([['a',{x:8,y:2}]]),16,true);assert.equal(offsets.size,0);
 let alpha=1;for(let i=0;i<100;i++)alpha=V.opacity(alpha,.32,16);assert.equal(alpha,.32);
});
