const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');const ctx={CiteLensCore:C};vm.createContext(ctx);for(const file of ['network-core.js','network-map.js'])vm.runInContext(fs.readFileSync(require.resolve('../addon/'+file),'utf8'),ctx);const M=ctx.CiteLensNetworkMap;
const paper=(key,title='Retinal cone photoreceptor development',extra={})=>({id:'1:'+key,title,year:'2020',DOI:'10.1234/'+key,libraryID:1,creators:[{firstName:'Anita',lastName:'Hendrickson'}],attachments:[],collections:[],...extra});
const input=(nodes,extra={})=>({nodes,edges:[],references:[],...extra});
test('author and topic modes expose different evidence types without inventing citation edges',()=>{const nodes=[paper('A'),paper('B','Retinal cone maturation and photoreceptor development')],author=M.build(input(nodes)),topic=M.build(input(nodes,{mode:'topics'}));assert.equal(author.nodes.filter(n=>n.kind==='author').length,1);assert.ok(author.edges.every(e=>e.kind==='author'));assert.ok(topic.nodes.some(n=>n.kind==='topic'));assert.ok(topic.edges.every(e=>e.kind==='topic'));});
test('references only enter the graph after explicit expansion, and ambiguous matches remain excluded',()=>{const a=paper('A'),ref={ref:{title:'A shared external retinal research paper',DOI:'10.1234/ext',year:'2000'},status:'missing',evidence:{attachmentID:7,pageIndex:4}},args=input([a],{references:[[a.id,[ref,{...ref,status:'ambiguous'}]]]});assert.equal(M.build(args).stats.external,0);const graph=M.build({...args,expanded:[a.id]});assert.equal(graph.stats.external,1);assert.equal(graph.stats.omittedReferences,1);assert.equal(graph.edges.find(e=>e.kind==='cites').evidence[0].pageIndex,4);});
test('newly saved reference replaces external node and keeps the source connection',()=>{const a=paper('A'),b=paper('B'),ref={ref:{title:b.title,DOI:b.DOI,year:b.year},status:'missing',evidence:{attachmentID:1}};const graph=M.build(input([a,b],{references:[[a.id,[ref]]],expanded:[a.id]}));assert.equal(graph.stats.external,0);assert.equal(graph.edges.find(e=>e.kind==='cites').target,b.id);});
test('initial load is bounded; selection and search can surface a paper beyond the first window',()=>{const nodes=Array.from({length:1800},(_,i)=>paper(String(i),'Unique research paper '+i));const g=M.build(input(nodes,{limit:600,selected:'1:1700'}));assert.equal(g.stats.local,600);assert.equal(g.stats.hidden,1200);assert.ok(g.nodes.some(n=>n.id==='1:1700'));assert.ok(!g.nodes.some(n=>n.id==='1:1799'));});
test('stable positions and pinned nodes survive worker layout, including empty and singleton graphs',()=>{const node=paper('A'),graph=M.build(input([node],{positions:[{id:node.id,x:17,y:23,pinned:true}]}));M.layout(graph);const result=graph.nodes.find(n=>n.id===node.id);assert.equal(result.x,17);assert.equal(result.y,23);assert.equal(M.layout(M.build(input([]))).nodes.length,0);assert.ok(graph.nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y)));});
test('shared external references become one node and retain both incoming citations',()=>{const a=paper('A'),b=paper('B'),ref={ref:{title:'External common research article',DOI:'10.1234/common'},status:'missing'};const g=M.build(input([a,b],{references:[[a.id,[ref]],[b.id,[ref]]],expanded:[a.id,b.id]}));assert.equal(g.stats.external,1);assert.equal(g.edges.filter(e=>e.kind==='cites').length,2);});
