const {test}=require('node:test'),assert=require('node:assert/strict'),V=require('../addon/network-view.js');
test('labels follow entity identity in either mode; author labels never acquire publication years',()=>{const node={title:'Retinal photoreceptor differentiation',author:'Masuda',creators:[{lastName:'Brat'}],year:2015};assert.equal(V.nodeLabel(node,'topics'),node.title);assert.equal(V.nodeLabel({...node,author:'Other',creators:[{lastName:'Different'}]},'topics'),node.title);assert.equal(V.nodeLabel({kind:'author',title:'Anita Hendrickson',year:2015},'authors'),'Anita Hendrickson');assert.equal(V.nodeLabel({kind:'topic',title:'Retinal development'},'authors'),'Retinal development');assert.equal(V.nodeLabel({...node,title:''},'topics'),'');assert.ok(V.nodeLabel({...node,title:'Long scientific title '.repeat(10)},'topics').length<=52);});
test('pinch keeps the cursor on the same world coordinate throughout smoothing',()=>{const camera={x:12,y:34,k:.5},x=280,y=170,wx=(x-camera.x)/camera.k,wy=(y-camera.y)/camera.k,target=V.zoom(camera,1.7,x,y);let n=0;while(V.step(camera,target,16)){assert.ok(Math.abs((x-camera.x)/camera.k-wx)<1e-8);assert.ok(Math.abs((y-camera.y)/camera.k-wy)<1e-8);assert.ok(++n<100);}assert.equal(camera.k,.85);});
test('precision trackpad pans on both axes, pinch and discrete mouse wheel zoom',()=>{assert.deepEqual(V.wheel({deltaMode:0,deltaX:12.5,deltaY:-3.2}),{x:-12.5,y:3.2,zoom:1});assert.ok(V.wheel({deltaMode:0,deltaX:0,deltaY:-3.2,ctrlKey:true}).zoom>1);assert.ok(V.wheel({deltaMode:1,deltaX:0,deltaY:3}).zoom<1);assert.ok(V.wheel({deltaMode:0,deltaX:0,deltaY:120}).zoom<1);});
test('large event spikes and reversed gestures remain bounded, reduced motion settles immediately',()=>{const c={x:0,y:0,k:1};let t=V.zoom(c,1e20,50,50);assert.equal(t.k,5);t=V.zoom(c,1e-20,50,50);assert.equal(t.k,.06);assert.equal(V.step(c,t,100,true),false);assert.deepEqual(c,t);});
test('dense overview retains every paper location and focused neighborhoods retain identity',()=>{const papers=Array.from({length:100},(_,i)=>({id:'p'+i,kind:'paper',group:'g',x:i,y:i})),hub={id:'g',kind:'author',members:papers.map(p=>p.id)},model={nodes:[...papers,hub],edges:papers.map(p=>({source:'g',target:p.id,kind:'author'})),matches:[]},index=V.index(model);const overview=V.scene(model,index,{k:.3});assert.equal(overview.nodes.length,101);const focus=V.scene(model,index,{k:.3,selected:'g',focused:true});assert.equal(focus.nodes.length,101);model.matches=['p99'];assert.ok(V.scene(model,index,{k:.3}).nodes.some(n=>n.id==='p99'));});
test('screen label grid prevents overlap and preserves priority labels',()=>{const candidates=[{id:'a',priority:1,rect:{x:10,y:10,w:90,h:18}},{id:'b',priority:9,rect:{x:20,y:10,w:90,h:18}},{id:'c',priority:2,rect:{x:10,y:40,w:90,h:18}}];assert.deepEqual(V.labels(candidates,300,300).map(n=>n.id),['b','c']);});

test('one visual line merges relation types and reciprocal citations without counting repeated evidence',()=>{const nodes=[{id:'a',kind:'paper'},{id:'b',kind:'paper'}],edges=[{source:'a',target:'b',kind:'cites',evidence:[{pageIndex:1},{pageIndex:2}]},{source:'a',target:'b',kind:'cites',evidence:[{pageIndex:3}]},{source:'b',target:'a',kind:'cites'},{source:'a',target:'b',kind:'similarity',evidence:[{score:.8}]},{source:'a',target:'b',kind:'author',evidence:[{authorKey:'A'},{authorKey:'B'},{authorKey:'A'}]}],model={nodes,edges},scene=V.scene(model,V.index(model));assert.equal(scene.edges.length,1);const edge=scene.edges[0];assert.equal(edge.count,5);assert.deepEqual(edge.directions,['forward','backward']);assert.deepEqual(edge.kinds,['author','cites','similarity']);assert.ok(V.lineWidth(5)>V.lineWidth(1));assert.equal(V.lineWidth(10000),3.2);});
test('distinct node pairs each keep one line and duplicate layout hints do not thicken it',()=>{const nodes=['a','b','c'].map(id=>({id,kind:'paper'})),edges=[{source:'a',target:'b',kind:'topic'},{source:'b',target:'a',kind:'topic'},{source:'a',target:'c',kind:'topic'}],model={nodes,edges},scene=V.scene(model,V.index(model));assert.equal(scene.edges.length,2);assert.ok(scene.edges.every(e=>e.count===1));});
