const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
const ctx={CiteLensCore:C};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/network-core.js'),'utf8'),ctx);const N=ctx.CiteLensNetworkCore;
const node=(key,extra={})=>({id:'1:'+key,key,libraryID:1,title:'A precise scientific paper '+key,DOI:'10.1234/'+key,year:'2020',creators:[{firstName:'Anita',lastName:'Hendrickson'}],relatedKeys:[],...extra});
test('local citations require an exact DOI or unique title/year/lead name',()=>{const a=node('A'),b=node('B');const g=N.build([a,b],[{source:a.id,refs:[{DOI:b.DOI,title:'Original abbreviated title'}]}]);assert.equal(g.edges.length,1);assert.equal(g.edges[0].kind,'cites');assert.equal(N.neighbors(g,b.id)[0].relations[0].direction,'in');});
test('a conflicting DOI never falls back to an identical title',()=>{const a=node('A'),b=node('B');const g=N.build([a,b],[{source:a.id,refs:[{DOI:'10.1234/conflict',title:b.title,year:b.year,author:'Hendrickson'}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.unresolved,1);});
test('duplicate matches remain ambiguous rather than choosing a library item',()=>{const a=node('A'),b=node('B'),duplicate=node('C',{DOI:b.DOI});const g=N.build([a,b,duplicate],[{source:a.id,refs:[{DOI:b.DOI}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.ambiguous,1);});
test('same-library citation target wins over cross-library copies',()=>{const a=node('A'),b=node('B'),copy={...b,id:'2:B',libraryID:2};const g=N.build([a,b,copy],[{source:a.id,refs:[{DOI:b.DOI}]}]);assert.equal(g.edges[0].target,'1:B');});
test('short initials are not used to manufacture author connections',()=>{assert.equal(N.authorKey({firstName:'A. K.',lastName:'Smith'}),'');assert.equal(N.authorKey({firstName:'',lastName:'Hendrickson'}),'');const a=node('A'),b=node('B');const row=N.neighbors(N.build([a,b]),a.id)[0];assert.equal(row.relations[0].kind,'author');assert.equal(row.relations[0].name,'Anita Hendrickson');});
test('related items are symmetric and scoped by library',()=>{const a=node('A',{relatedKeys:['B']}),b=node('B',{relatedKeys:['A']}),g=N.build([a,b]);assert.equal(g.edges.length,1);assert.ok(N.neighbors(g,b.id).some(x=>x.node.id===a.id));assert.equal(N.neighbors(g,a.id,{scope:[a.id]}).length,0);});
test('self-citations, missing nodes and removed sources do not create ghost edges',()=>{const a=node('A',{relatedKeys:['MISSING']}),g=N.build([a],[{source:a.id,refs:[{DOI:a.DOI}]},{source:'1:deleted',refs:[{DOI:a.DOI}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.sources,1);});
test('metadata search combines title, authors and dates without executing input',()=>{assert.equal(N.search([node('A'),node('B',{year:'2021'})],'Anita 2020').length,1);assert.equal(N.search([node('A')],'<script>alert(1)</script>').length,1);});
test('10k-paper neighbor lookup avoids materializing all same-author pairs',()=>{const nodes=Array.from({length:10000},(_,i)=>node(String(i),{creators:[{firstName:'Fullname'+i%100,lastName:'Author'}]}));const g=N.build(nodes);assert.equal(g.edges.length,0);assert.equal(N.neighbors(g,nodes[0].id).length,99);});
test('display consolidation merges safe same-library copies but preserves conflicts and source evidence',()=>{const a=node('A',{collections:[1],attachments:[]}),b=node('B',{DOI:a.DOI,title:a.title,collections:[2],attachments:[{id:2}]}),conflict=node('C',{DOI:a.DOI,title:'A conflicting metadata record'}),foreign={...a,id:'2:A',libraryID:2};const m=N.consolidate([a,b,conflict,foreign],[{source:b.id,refs:[]}]);assert.equal(m.nodes.length,3);assert.equal(m.aliases.get(b.id),a.id);assert.deepEqual(Array.from(m.nodes.find(n=>n.id===a.id).collections),[1,2]);assert.equal(m.sources[0].source,a.id);assert.equal(a.collections.length,1);});
test('workspace separates missing and ambiguous references and preserves shared external references',()=>{const a=node('A'),b=node('B'),c=node('C',{DOI:b.DOI}),d=node('D');const ref={DOI:'10.1234/external',title:'An external common scientific reference'};const g=N.build([a,b,c,d],[{source:a.id,refs:[ref,ref,{DOI:b.DOI}]},{source:d.id,refs:[ref,{DOI:a.DOI}]}]);const w=N.workspace(g,a.id);assert.equal(w.references.length,2);assert.equal(w.references[1].status,'ambiguous');assert.equal(w.shared.length,1);assert.equal(w.shared[0].shared.length,1);assert.equal(w.incoming[0].node.id,d.id);assert.equal(N.workspace(g,a.id,[a.id]).shared.length,0);});
test('topics group research content without author/year/journal shortcuts or forcing unrelated papers',()=>{const nodes=[node('A',{title:'Retinal cone photoreceptor differentiation',abstract:'Retinal cone photoreceptor maturation and differentiation'}),node('B',{title:'Cone photoreceptor maturation in retina',abstract:'Retinal cone differentiation and photoreceptor maturation'}),node('C',{title:'Antibiotic resistance in bacterial biofilms',abstract:'Bacterial antibiotic resistance biofilm infection'}),node('D',{title:'Biofilm bacterial antibiotic resistance',abstract:''}),node('E',{title:'Galaxy cosmology dark matter'})];const groups=N.topics(nodes);assert.equal(groups.length,2);assert.equal(groups[0].nodes.length,2);assert.ok(groups.every(g=>!g.nodes.some(n=>n.id==='1:E')));assert.ok(groups.some(g=>g.abstracts===1));assert.deepEqual(JSON.parse(JSON.stringify(N.topics(nodes))),JSON.parse(JSON.stringify(groups)));});
test('topic clustering supports Chinese titles and excludes empty records',()=>{const groups=N.topics([node('A',{title:'视网膜发育过程中视锥细胞分化'}),node('B',{title:'视网膜视锥细胞分化与发育'}),node('C',{title:''})]);assert.equal(groups.length,1);assert.equal(groups[0].nodes.length,2);});

test('modularity detects dense connected communities without a nominated root',()=>{const ids=Array.from({length:18},(_,i)=>'n'+i),edges=[];for(let g=0;g<3;g++)for(let i=0;i<6;i++)for(let j=i+1;j<6;j++)edges.push({source:ids[g*6+i],target:ids[g*6+j],weight:1});edges.push({source:'n0',target:'n6',weight:.2},{source:'n6',target:'n12',weight:.2});const groups=N.communities(ids,edges);assert.equal(groups.length,3);assert.ok(groups.every(g=>g.length===6));assert.deepEqual(N.communities([...ids].reverse(),[...edges].reverse()),groups);});
test('topic nearest-neighbour communities are stable when bibliography order changes',()=>{const nodes=[node('A',{title:'Retinal cone photoreceptor differentiation'}),node('B',{title:'Retinal cone photoreceptor maturation'}),node('C',{title:'Bacterial antibiotic resistance biofilm infection'}),node('D',{title:'Antibiotic resistance bacterial biofilm'})];assert.deepEqual(N.topics(nodes),N.topics([...nodes].reverse()));});
