const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
const ctx={CiteLensCore:C};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/network-core.js'),'utf8'),ctx);const N=ctx.CiteLensNetworkCore;
const node=(key,extra={})=>({id:'1:'+key,key,libraryID:1,title:'A precise scientific paper '+key,DOI:'10.1234/'+key,year:'2020',creators:[{firstName:'Anita',lastName:'Hendrickson'}],relatedKeys:[],...extra});
test('local citations require an exact DOI or unique title/year/lead name',()=>{const a=node('A'),b=node('B');const g=N.build([a,b],[{source:a.id,refs:[{DOI:b.DOI,title:'Original abbreviated title'}]}]);assert.equal(g.edges.length,1);assert.equal(g.edges[0].kind,'cites');assert.equal(N.neighbors(g,b.id)[0].relations[0].direction,'in');});
test('a conflicting DOI never falls back to an identical title',()=>{const a=node('A'),b=node('B');const g=N.build([a,b],[{source:a.id,refs:[{DOI:'10.1234/conflict',title:b.title,year:b.year,author:'Hendrickson'}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.unresolved,1);});
test('duplicate matches remain ambiguous rather than choosing a library item',()=>{const a=node('A'),b=node('B'),duplicate=node('C',{DOI:b.DOI});const g=N.build([a,b,duplicate],[{source:a.id,refs:[{DOI:b.DOI}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.ambiguous,1);});
test('same-library citation target wins over cross-library copies',()=>{const a=node('A'),b=node('B'),copy={...b,id:'2:B',libraryID:2};const g=N.build([a,b,copy],[{source:a.id,refs:[{DOI:b.DOI}]}]);assert.equal(g.edges[0].target,'1:B');});
test('short initials are not used to manufacture author connections',()=>{assert.equal(N.authorKey({firstName:'A. K.',lastName:'Smith'}),'');assert.equal(N.authorKey({firstName:'',lastName:'Hendrickson'}),'');const a=node('A'),b=node('B');const row=N.neighbors(N.build([a,b]),a.id)[0];assert.equal(row.relations[0].kind,'author');assert.equal(row.relations[0].name,'Anita Hendrickson');});
test('related items are symmetric and scoped by library',()=>{const a=node('A',{relatedKeys:['B']}),b=node('B',{relatedKeys:['A']}),g=N.build([a,b]);assert.equal(g.edges.length,1);assert.ok(N.neighbors(g,b.id).some(x=>x.node.id===a.id));assert.equal(N.neighbors(g,a.id,{scope:[a.id]}).length,0);});
test('self-citations, missing nodes and removed sources do not create ghost edges',()=>{const a=node('A',{relatedKeys:['MISSING']}),g=N.build([a],[{source:a.id,refs:[{DOI:a.DOI}]},{source:'1:deleted',refs:[{DOI:a.DOI}]}]);assert.equal(g.edges.length,0);assert.equal(g.coverage.sources,1);});
test('metadata search combines title, authors and dates without executing input',()=>{assert.equal(N.search([node('A'),node('B',{year:'2021'})],'Anita 2020').length,1);assert.equal(N.search([node('A')],'<script>alert(1)</script>').length,1);});
test('10k-paper neighbor lookup avoids materializing all same-author pairs',()=>{const nodes=Array.from({length:10000},(_,i)=>node(String(i),{creators:[{firstName:'Fullname'+i%100,lastName:'Author'}]}));const g=N.build(nodes);assert.equal(g.edges.length,0);assert.equal(N.neighbors(g,nodes[0].id).length,99);});
test('display consolidation merges safe same-library copies but preserves conflicts and source evidence',()=>{const a=node('A',{collections:[1],attachments:[]}),b=node('B',{DOI:a.DOI,title:a.title,collections:[2],attachments:[{id:2}]}),conflict=node('C',{DOI:a.DOI,title:'A conflicting metadata record'}),foreign={...a,id:'2:A',libraryID:2};const m=N.consolidate([a,b,conflict,foreign],[{source:b.id,refs:[]}]);assert.equal(m.nodes.length,3);assert.equal(m.aliases.get(b.id),a.id);assert.deepEqual(Array.from(m.nodes.find(n=>n.id===a.id).collections),[1,2]);assert.equal(m.sources[0].source,a.id);assert.equal(a.collections.length,1);});
test('workspace separates missing and ambiguous references and preserves shared external references',()=>{const a=node('A'),b=node('B'),c=node('C',{DOI:b.DOI}),d=node('D');const ref={DOI:'10.1234/external',title:'An external common scientific reference'};const g=N.build([a,b,c,d],[{source:a.id,refs:[ref,ref,{DOI:b.DOI}]},{source:d.id,refs:[ref,{DOI:a.DOI}]}]);const w=N.workspace(g,a.id);assert.equal(w.references.length,2);assert.equal(w.references[1].status,'ambiguous');assert.equal(w.shared.length,1);assert.equal(w.shared[0].shared.length,1);assert.equal(w.incoming[0].node.id,d.id);assert.equal(N.workspace(g,a.id,[a.id]).shared.length,0);});
test('modularity detects dense connected communities without a nominated root',()=>{const ids=Array.from({length:18},(_,i)=>'n'+i),edges=[];for(let g=0;g<3;g++)for(let i=0;i<6;i++)for(let j=i+1;j<6;j++)edges.push({source:ids[g*6+i],target:ids[g*6+j],weight:1});edges.push({source:'n0',target:'n6',weight:.2},{source:'n6',target:'n12',weight:.2});const groups=N.communities(ids,edges);assert.equal(groups.length,3);assert.ok(groups.every(g=>g.length===6));assert.deepEqual(N.communities([...ids].reverse(),[...edges].reverse()),groups);});
test('indexed name search tolerates case and hyphens and highlights the author rather than every coauthor',()=>{
 const papers=[node('p',{title:'Retinal differentiation',abstract:'Biological regeneration of photoreceptors',creators:[{firstName:'Jun–Yan',lastName:'Kang'}]})],nodes=[{id:'author:a',kind:'author',title:'Jun–Yan Kang',members:['1:p']},{id:'author:b',kind:'author',title:'Other Person',members:['1:p']}],index=N.searchIndex({nodes,papers,mode:'authors'}),result=N.queryIndex(index,'jun-YAN');
 assert.deepEqual([...result.matches],['author:a']);assert.equal(result.results[0].id,'author:a');assert.equal(N.queryIndex(index,'photoreceptors').matches.length,2);assert.equal(N.queryIndex(index,'nonexistent term').matches.length,0);assert.equal(N.queryIndex(index,'').results.length,0);
 const topic=N.searchIndex({nodes:[{id:'topic:a',kind:'topic',title:'Retinal development',members:['1:p']}],papers,mode:'topics'});assert.deepEqual([...N.queryIndex(topic,'regeneration').matches],['topic:a']);
});
test('author ego has exact first and second degree paths, never arbitrary same-community members',()=>{
 const nodes=['a','b','c','d'].map((id,i)=>({id,kind:'author',title:id,members:([['ab'],['ab','bc'],['bc'],['d']])[i]})),index=N.searchIndex({nodes,mode:'authors'});
 const first=N.authorNeighborhood(index,'a',1),second=N.authorNeighborhood(index,'a',2);assert.deepEqual(Array.from(first.nodes,n=>n.id).sort(),['a','b']);assert.deepEqual(Array.from(second.nodes,n=>n.id).sort(),['a','b','c']);assert.equal(second.nodes.find(n=>n.id==='a').depth,0);assert.equal(second.nodes.find(n=>n.id==='c').depth,2);assert.ok(second.edges.every(e=>e.evidence.length));assert.equal(second.edges.length,2);
});

test('author lookup accepts joined, reordered, accented and hyphenated names without changing identity',()=>{
 const nodes=[{id:'kang',kind:'author',title:'Jun–Yan Kang',members:['p']},{id:'other',kind:'author',title:'Kai Wang',members:['p']},{id:'accent',kind:'author',title:'José García',members:[]}],index=N.searchIndex({nodes,mode:'authors'});
 for(const q of ['kangjunyan','Kang Junyan','Kang Jun-Yan','junyan Kang','junyan','JUN YAN KANG'])assert.deepEqual([...N.queryIndex(index,q).matches],['kang'],q);
 assert.deepEqual([...N.queryIndex(index,'garcia jose').matches],['accent']);assert.equal(N.queryIndex(index,'J').matches.length,2);assert.equal(N.queryIndex(index,'kangwang').matches.length,0);
});
test('topic lookup tolerates spaces, punctuation, word order and a bounded typo',()=>{
 const nodes=[{id:'t1',kind:'topic',title:'Single-cell retinal development',members:['p1']},{id:'t2',kind:'topic',title:'Retinal cell regeneration',members:['p2']},{id:'t3',kind:'topic',title:'Genomic stability',members:['p3']}],index=N.searchIndex({nodes,mode:'topics'});
 for(const q of ['singlecell','development retinal','retianl development'])assert.ok(N.queryIndex(index,q).matches.includes('t1'),q);
 assert.deepEqual([...N.queryIndex(index,'retinal').matches].sort(),['t1','t2']);assert.equal(N.queryIndex(index,'retinal volcano').matches.length,0);assert.deepEqual([...N.queryIndex(index,'').matches],[]);
 assert.deepEqual(Object.keys(N.queryIndex(index,'retinal').results[0]).sort(),['id','kind','title','year']);
});
