const {test}=require('node:test'),assert=require('node:assert/strict'),S=require('../addon/semantic-core.js');
test('long abstracts keep conclusion and title-only records need no invented abstract',()=>{const text=Array.from({length:1000},(_,i)=>'word'+i).join(' '),parts=S.abstractChunks(text);assert.equal(parts.length,4);assert.ok(parts.at(-1).includes('word999'));assert.deepEqual(S.abstractChunks(''),[]);assert.deepEqual(S.abstractChunks('short record'),[]);});
test('BERT keeps non-ASCII symbols inside WordPiece while separating punctuation',()=>{const tokenizer={model:{vocab:{'[CLS]':101,'[SEP]':102,'[UNK]':100,mu:1,'##€':2,'##ller':3,',':4}}};assert.deepEqual(S.tokenize('Mu€ller,',tokenizer),[101,1,2,3,4,102]);});
test('title-only semantic links use a higher threshold; graph retains isolates and mutual neighbours only',()=>{const nodes=[{id:'a'},{id:'b'}],vectors=[[1,0],[.55,Math.sqrt(1-.55**2)]],partition=(ids,edges)=>edges.length?[ids]:ids.map(x=>[x]);assert.equal(S.graph(nodes,vectors,partition).links.length,0);nodes.forEach(n=>n.abstract='a'.repeat(100));assert.equal(S.graph(nodes,vectors,partition).links.length,1);const many=Array.from({length:30},(_,i)=>({id:'n'+i})),g=S.graph(many,many.map(()=>[1,0]),partition);const counts=new Map();for(const e of g.links){counts.set(e.source,(counts.get(e.source)||0)+1);counts.set(e.target,(counts.get(e.target)||0)+1);}assert.ok([...counts.values()].every(n=>n<=7));});
test('cloud grouping never manufactures a citation and does not connect semantically unrelated papers',()=>{const n=[{id:'a'},{id:'b'}],assignments=n.map(x=>({...x,topic:'Biology'}));assert.equal(S.graph(n,[[1,0],[0,1]],ids=>[ids],assignments).links.length,0);});
test('personal adapters require exact model identity and finite weights',()=>{const a={model:'Xenova/all-MiniLM-L6-v2',revision:'751bff37182d3f1213fa05d7196b954e230abad9',dimension:384,rank:1,a:Array(384).fill(0),b:Array(384).fill(0)};assert.equal(S.validAdapter(a),true);assert.equal(S.validAdapter({...a,revision:'other'}),false);assert.equal(S.validAdapter({...a,b:[NaN,...a.b.slice(1)]}),false);});
test('incremental neighbours equal cold results after additions, metadata edits, deletion and expansion',()=>{
 let seed=17;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),vec=()=>S.normalize(Array.from({length:24},()=>random()));
 const groups=(ids)=>[ids];let nodes=Array.from({length:80},(_,i)=>({id:'p'+i,abstract:'a'.repeat(100)})),vectors=nodes.map(vec),result=S.graph(nodes,vectors,groups);
 for(let round=0;round<8;round++){
  if(round%3===0){nodes.push({id:'added'+round,abstract:'a'.repeat(100)});vectors.push(vec());}else if(round%3===1){vectors[5]=vec();nodes[9]={...nodes[9],abstract:''};}else{nodes.splice(7,1);vectors.splice(7,1);}
  const next=S.graph(nodes,vectors,groups,null,{previous:result.state}),cold=S.graph(nodes,vectors,groups);assert.deepEqual(next.links,cold.links,'round '+round);assert.ok(next.incremental.comparisons<cold.incremental.comparisons);result=next;
 }
 const same=S.graph(nodes,vectors,groups,null,{previous:result.state});assert.equal(same.incremental.comparisons,0);assert.deepEqual(same.links,result.links);
});
test('cloud-label or abstract-availability changes invalidate only affected neighbour rows',()=>{const nodes=[{id:'a',abstract:'x'.repeat(100)},{id:'b',abstract:'x'.repeat(100)},{id:'c'}],v=[[1,0],[.55,Math.sqrt(1-.55**2)],[0,1]],partition=ids=>[ids];const first=S.graph(nodes,v,partition);const edited=[{id:'a'},...nodes.slice(1)],next=S.graph(edited,v,partition,null,{previous:first.state});assert.deepEqual(next.links,S.graph(edited,v,partition).links);assert.equal(next.incremental.changed,1);});
test('SIMD graph preserves scalar neighbours and incremental edits at full embedding width',async()=>{
 const K=require('../addon/semantic-kernel.js'),factory=await K.create();assert.ok(factory);let seed=7;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),nodes=Array.from({length:260},(_,i)=>({id:'p'+i,abstract:'x'.repeat(100)})),vectors=nodes.map(()=>S.normalize(Array.from({length:384},random))),partition=ids=>[ids];S.setKernel(null);const scalar=S.graph(nodes,vectors,partition);try{S.setKernel(factory);const fast=S.graph(nodes,vectors,partition);assert.deepEqual(fast.links.map(x=>[x.source,x.target]),scalar.links.map(x=>[x.source,x.target]));fast.links.forEach((x,i)=>assert.ok(Math.abs(x.score-scalar.links[i].score)<1e-12));vectors[3]=S.normalize(Array.from({length:384},random));const edited=S.graph(nodes,vectors,partition,null,{previous:fast.state}),cold=S.graph(nodes,vectors,partition);assert.deepEqual(edited.links,cold.links);}finally{S.setKernel(null);}
});
