const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js'),SC=require('../addon/semantic-core.js');
function service(){const context={CiteLensCore:C,CiteLensSemanticCore:SC,CiteLensTranslation:{get:()=> 'local'},Zotero:{Promise:{delay:()=>Promise.resolve()}}};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../addon/semantic.js'),'utf8'),context);const S=context.CiteLensSemantic,calls=[];Object.assign(S,{dead:false,load:async()=>{},key:async text=>text,persist:async()=>{},adapter:async()=>null,encode:async texts=>{calls.push(...texts);return texts.map(text=>{const v=Array(384).fill(0);v[text.length%384]=1;return v;});}});return{S,calls};}
test('authors, journal and collection names never enter semantic input or cache keys',async()=>{const {S,calls}=service(),paper={id:'a',title:'Photoreceptor development',author:'Masuda',creators:[{lastName:'Brat'}],journal:'FakeJournal',collections:['FalseTopic']},a=await S.analyze([paper]),b=await S.analyze([{...paper,author:'Changed',creators:[{lastName:'Different'}]}]);assert.deepEqual(calls,[paper.title]);assert.deepEqual(a.vectors,b.vectors);assert.equal(b.encoded,0);});
test('cached PDF author strings are repaired before both embedding and cluster labels',async()=>{const {S,calls}=service(),raw='Sjöstrand, J., Popovic, Z., Conradi, N., 1999Fb. Morphometric study of retinal ganglion cells within the human fovea. Vision Res. 39, 100–110.';await S.analyze([{id:'a',title:raw.split('. Morphometric')[0],raw}]);assert.deepEqual(calls,['Morphometric study of retinal ganglion cells within the human fovea']);assert.equal(C.researchTitle({title:'Müller glia and Parkinson disease'}),'Müller glia and Parkinson disease');});
test('unrecoverable author lists do not become embeddings or forced topic edges',async()=>{const {S,calls}=service(),result=await S.analyze([{id:'a',title:'Smith, A., Jones, B.'}]);assert.equal(calls.length,0);assert.ok(result.vectors[0].every(x=>x===0));});
test('only changed titles are encoded again; missing abstracts stay missing',async()=>{const {S,calls}=service(),papers=[{id:'a',title:'Cone development'},{id:'b',title:'Rod development'}];await S.analyze(papers);const result=await S.analyze([{...papers[0],title:'Human cone development'},papers[1]]);assert.equal(result.encoded,1);assert.equal(result.cached,1);assert.deepEqual(calls,['Cone development','Rod development','Human cone development']);});
test('active large batches retain vectors after bounded disk-cache eviction',async()=>{const {S}=service(),result=await S.analyze(Array.from({length:4510},(_,i)=>({id:String(i),title:'Research title '+i})));assert.equal(S.cache.size,4500);assert.equal(result.vectors.length,4510);assert.ok(result.vectors.every(v=>v.length===384&&v.every(Number.isFinite)));});
test('abort between inference chunks preserves completed reusable work',async()=>{const {S}=service(),controller=new AbortController();let writes=0;S.persist=async()=>{writes++;controller.abort();};await assert.rejects(S.analyze(Array.from({length:100},(_,i)=>({id:String(i),title:'Research title '+i})),{signal:controller.signal}),/已取消/);assert.equal(writes,1);assert.equal(S.cache.size,96);});
test('unchanged final vectors survive text-cache eviction without re-encoding',async()=>{const {S,calls}=service(),papers=[{id:'a',title:'Cone development'},{id:'b',title:'Rod development'}];await S.analyze(papers);S.cache.clear();const next=await S.analyze(papers);assert.equal(calls.length,2);assert.equal(next.encoded,0);assert.equal(next.combined,0);});
test('group naming reuses unchanged groups and only requests changed research content',async()=>{let calls=[];const T={get:()=> 'llm',llmTaskConfig:()=>({id:'fixture',endpoint:'https://example.org',model:'fixture-model'}),nameTopicsLLM:async groups=>{calls.push(groups);return groups.map(g=>({id:g.id,topic:'Retinal development'}));}};const context=vm.createContext({CiteLensCore:C,CiteLensSemanticCore:SC,CiteLensTranslation:T,Zotero:{Promise:{delay:()=>Promise.resolve()}}});vm.runInContext(fs.readFileSync(require.resolve('../addon/semantic.js'),'utf8'),context);const service=context.CiteLensSemantic;Object.assign(service,{dead:false,load:async()=>{},key:async x=>x,persist:async()=>{}});const papers=[{id:'a',title:'Cone development'},{id:'b',title:'Rod development'}],groups=[{id:'g1',members:['a']},{id:'g2',members:['b']}];await service.nameGroups(groups,papers);const unchanged=await service.nameGroups(groups,papers);assert.equal(unchanged.named,0);const edited=await service.nameGroups(groups,[papers[0],{...papers[1],title:'Rod maturation'}]);assert.equal(edited.named,1);assert.equal(calls[1].length,1);assert.equal(calls[1][0].id,'g2');});
test('inference is serialized, reuses one model, and releases it on cancellation or shutdown',async()=>{
 let created=0,terminated=0,active=0,peak=0;const workers=[];class Worker{constructor(){created++;workers.push(this);}postMessage(m){if(m.init){setTimeout(()=>this.onmessage({data:{ready:true}}),1);return;}active++;peak=Math.max(peak,active);this.job=setTimeout(()=>{active--;this.job=null;this.onmessage({data:{vectors:m.texts.map(()=>[1])}});},5);}terminate(){if(this.closed)return;this.closed=true;terminated++;if(this.job){clearTimeout(this.job);this.job=null;active--;}}}
 const win={ChromeWorker:Worker,setTimeout,clearTimeout},context=vm.createContext({CiteLens:{assetResource:'fixture'},CiteLensCore:C,Zotero:{getMainWindow:()=>win}});vm.runInContext(fs.readFileSync(require.resolve('../addon/semantic.js'),'utf8'),context);const S=context.CiteLensSemantic;Object.assign(S,{dead:false,encodeEpoch:1,encodeTail:Promise.resolve()});
 try{await Promise.all([S.encode(['first']),S.encode(['second'])]);assert.equal(created,1);assert.equal(peak,1);assert.equal(S.workers.size,1);
 const controller=new AbortController(),pending=S.encode(['third'],{signal:controller.signal});await new Promise(r=>setTimeout(r,1));controller.abort();await assert.rejects(pending,/已取消/);assert.equal(S.workers.size,0);await S.encode(['after abort']);assert.equal(created,2);await S.stop();assert.equal(terminated,2);assert.equal(S.workers.size,0);
 }finally{await S.stop();}
});
test('LLM naming receives representative content and reuses unchanged requests',async()=>{
 let sent;const T={llmTaskConfig:()=>({id:'fixture',endpoint:'https://example.org',model:'fixture'}),nameTopicsLLM:async groups=>{sent=groups;return groups.map(g=>({id:g.id,topic:'Retinal development'}));}},context=vm.createContext({CiteLensCore:C,CiteLensSemanticCore:SC,CiteLensTranslation:T,Zotero:{Promise:{delay:()=>Promise.resolve()}}});vm.runInContext(fs.readFileSync(require.resolve('../addon/semantic.js'),'utf8'),context);const S=context.CiteLensSemantic;Object.assign(S,{dead:false,load:async()=>{},key:async x=>x,persist:async()=>{}});
 const papers=Array.from({length:12},(_,i)=>({id:String(i),title:i<8?'A peripheral '+i:'Retinal development '+i})),groups=[{id:'g',members:papers.map(p=>p.id),representatives:['8','9','10','11']}];await S.nameGroups(groups,papers);assert.ok(sent[0].papers.every(p=>p.title.startsWith('Retinal')));assert.equal(sent[0].papers.length,4);assert.equal((await S.nameGroups(groups,papers)).named,0);
});

test('switching the embedding space while analysis is waiting cancels the old result',async()=>{const {S}=service();S.encodeEpoch=1;S.persist=async()=>{S.encodeEpoch++;};await assert.rejects(S.analyze([{id:'one',title:'Photoreceptor maturation'}]),/已取消/);assert.equal(S.records.size,0);});
test('API grouping reuses existing themes across batches, persists cache, and only classifies changed content',async()=>{const crypto=require('node:crypto'),files=new Map(),calls=[];const context=vm.createContext({CiteLensCore:C,Zotero:{Promise:{delay:async()=>{}},logError:()=>{}},CiteLensTranslation:{llmTaskConfig:()=>({id:'fixture',endpoint:'https://example.org',model:'model'}),clusterLLM:async(papers,options)=>{calls.push({papers,topics:options.topics});return papers.map(p=>({id:p.id,topicId:options.topics[0]?.id||'new:1',topic:'Retinal development',keywords:[]}));}},IOUtils:{exists:async p=>files.has(p),stat:async p=>({size:files.get(p).length}),readUTF8:async p=>files.get(p),writeUTF8:async(p,v)=>files.set(p,v)}});const create=()=>{vm.runInContext(fs.readFileSync(require.resolve('../addon/semantic.js'),'utf8'),context);const s=context.CiteLensSemantic;Object.assign(s,{dead:false,encodeEpoch:1,groupingPath:'/cache/groups.json',key:async(text,scope)=>crypto.createHash('sha256').update(scope+text).digest('hex')});return s;};const S=create(),nodes=Array.from({length:26},(_,i)=>({id:String(i).padStart(2,'0'),title:'Retinal development '+i,abstract:'Study of developing retinal photoreceptors.',authors:['PRIVATE']}));const initial=await S.classifyTopics(nodes);assert.equal(calls.length,2);assert.equal(new Set(initial.assignments.map(r=>r.topicId)).size,1);assert.ok(calls[1].topics.length);assert.ok(!JSON.stringify(calls).includes('PRIVATE'));assert.equal((await S.classifyTopics(nodes)).classified,0);assert.equal(calls.length,2);const edited=[...nodes.slice(1),{...nodes[0],title:'Cone photoreceptor maturation'}];assert.equal((await S.classifyTopics(edited)).classified,1);assert.equal(calls.at(-1).papers.length,1);const restarted=create();assert.equal((await restarted.classifyTopics(edited)).classified,0);assert.equal(calls.length,3);const expanded=[...edited,{id:'reference',title:'Retinal developmental pathways'}];assert.equal((await restarted.classifyTopics(expanded)).classified,1);assert.equal(calls.at(-1).topics.length,1);const controller=new AbortController();controller.abort();await assert.rejects(restarted.classifyTopics(nodes,{signal:controller.signal}),/已取消/);});
