const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
function setup(request){let writes=[];const ctx={CiteLensCore:C,PathUtils:{},Zotero:{HTTP:{request},logError(){}},IOUtils:{writeUTF8:async(p,s)=>writes.push(s)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/services.js'),'utf8'),ctx);return {S:ctx.CiteLensServices,writes,ctx};}
const cross={DOI:'10.1234/a',title:['The primate fovea structure function and development'],author:[{family:'Bringmann'}],published:{'date-parts':[[2018]]}};
test('deduplicates in-flight metadata requests and persists bounded cache',async()=>{let count=0;const {S,writes}=setup(async()=>{count++;await new Promise(r=>setTimeout(r,5));return {response:{message:cross}}});const record={DOI:cross.DOI,title:cross.title[0]};const [a,b]=await Promise.all([S.lookup(record),S.lookup(record)]);assert.equal(count,1);assert.equal(a.status,'matched');assert.equal(b.status,'matched');assert.equal((await S.lookup(record)).cached,true);assert.ok(writes.length);});
test('network error is not cached as a missing record or zero',async()=>{const {S}=setup(async()=>{throw {status:429}});await assert.rejects(S.lookup({DOI:cross.DOI}),/繁忙/);assert.equal(Object.keys(S.state.cache).length,0);assert.equal(S.inFlight.size,0);});
test('request concurrency never exceeds two',async()=>{let active=0,max=0;const {S}=setup(async()=>{max=Math.max(max,++active);await new Promise(r=>setTimeout(r,8));active--;return {response:{message:cross}}});await Promise.all(Array.from({length:7},(_,i)=>S.lookup({DOI:'10.1234/'+i})));assert.equal(max,2);});
test('stopped service refuses queued or fresh requests',async()=>{const {S}=setup(async()=>({response:{message:cross}}));await S.stop();await assert.rejects(S.lookup({DOI:cross.DOI}),/关闭/);});
test('failed metric import preserves previous metrics',async()=>{const {S}=setup();S.state.metrics=[{journal:'original'}];await assert.rejects(S.importMetrics('[{"journal":"bad"}]'));assert.equal(S.state.metrics[0].journal,'original');});
test('local reading list deduplicates identical entries',async()=>{const {S}=setup(),r={DOI:cross.DOI,title:'A'};await S.enqueue(r,{});await S.enqueue(r,{});assert.equal(S.state.queue.length,1);await S.removeQueue(C.identity(r));assert.equal(S.state.queue.length,0);});
test('library presence includes read-only groups and keeps duplicate matches distinct',async()=>{const {S,ctx}=setup(),calls=[];ctx.Zotero.Libraries={getAll:()=>[{libraryID:1,name:'Personal',libraryType:'user',editable:true},{libraryID:2,name:'Shared',libraryType:'group',editable:false},{libraryID:3,name:'Feed',libraryType:'feed',editable:true}]};S.existing=async(r,id)=>{calls.push(id);return id===2?[{id:10},{id:11}]:[];};const matches=await S.locate({title:'A',year:'2004'});assert.deepEqual(calls,[1,2]);assert.equal(matches.length,2);assert.equal(matches[0].libraryName,'Shared');assert.equal(matches[0].editable,false);});
test('simultaneous library-presence lookups share work but do not retain stale results',async()=>{const {S,ctx}=setup();let calls=0;ctx.Zotero.Libraries={getAll:()=>[{libraryID:1,name:'Personal',libraryType:'user',editable:true}]};S.existing=async()=>{calls++;await new Promise(r=>setTimeout(r,5));return [];};const record={DOI:'10.1234/shared',title:'A'};await Promise.all([S.locate(record),S.locate(record)]);assert.equal(calls,1);await S.locate(record);assert.equal(calls,2);});
test('a previously saved reading-list entry can be queued again',async()=>{const {S}=setup(),record={DOI:'10.1234/revisit',title:'Revisit'};await S.enqueue(record,{});S.state.queue[0].status='saved';await S.enqueue(record,{});assert.equal(S.state.queue.length,1);assert.equal(S.state.queue[0].status,'unread');});
test('enriched DOI retains exact legacy matches without merging conflicting DOIs',async()=>{const {S,ctx}=setup(),record={DOI:'10.1234/a',title:'Exact article title',year:'2020',author:'Smith'},rows=[{id:1,DOI:'',title:record.title,date:'2020-02'},{id:2,DOI:'10.1234/b',title:record.title,date:'2020'},{id:3,DOI:'10.1234/a',title:record.title,date:'2020'},{id:4,DOI:'',title:record.title,date:'2019'}].map(r=>({...r,getField(k){return this[k]||''},getCreators(){return [{lastName:'Smith'}]}}));ctx.Zotero.Search=class{addCondition(){}async search(){return rows.map(x=>x.id)}};ctx.Zotero.Items={getAsync:async ids=>rows.filter(r=>ids.includes(r.id))};assert.deepEqual(Array.from(await S.existing(record,1),r=>r.id),[1,3]);});
