const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../addon/core.js');
function setup(request){let writes=[];const ctx={CiteLensCore:C,PathUtils:{},Zotero:{HTTP:{request},logError(){}},IOUtils:{writeUTF8:async(p,s)=>writes.push(s)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/services.js'),'utf8'),ctx);return {S:ctx.CiteLensServices,writes,ctx};}
const cross={DOI:'10.1234/a',title:['The primate fovea structure function and development'],author:[{family:'Bringmann'}],published:{'date-parts':[[2018]]}};
test('deduplicates in-flight metadata requests and persists bounded cache',async()=>{let count=0;const {S,writes}=setup(async()=>{count++;await new Promise(r=>setTimeout(r,5));return {response:{message:cross}}});const record={DOI:cross.DOI,title:cross.title[0]};const [a,b]=await Promise.all([S.lookup(record),S.lookup(record)]);assert.equal(count,1);assert.equal(a.status,'matched');assert.equal(b.status,'matched');assert.equal((await S.lookup(record)).cached,true);assert.ok(writes.length);});
test('network error is not cached as a missing record or zero',async()=>{const {S}=setup(async()=>{throw {status:429}});await assert.rejects(S.lookup({DOI:cross.DOI}),/繁忙/);assert.equal(Object.keys(S.state.cache).length,0);assert.equal(S.inFlight.size,0);});
test('request concurrency never exceeds two',async()=>{let active=0,max=0;const {S}=setup(async()=>{max=Math.max(max,++active);await new Promise(r=>setTimeout(r,8));active--;return {response:{message:cross}}});await Promise.all(Array.from({length:7},(_,i)=>S.lookup({DOI:'10.1234/'+i})));assert.equal(max,2);});
test('stopped service refuses queued or fresh requests',async()=>{const {S}=setup(async()=>({response:{message:cross}}));await S.stop();await assert.rejects(S.lookup({DOI:cross.DOI}),/关闭/);});
test('failed metric import preserves previous metrics',async()=>{const {S}=setup();S.state.metrics=[{journal:'original'}];await assert.rejects(S.importMetrics('[{"journal":"bad"}]'));assert.equal(S.state.metrics[0].journal,'original');});
test('local reading list deduplicates identical entries',async()=>{const {S}=setup(),r={DOI:cross.DOI,title:'A'};await S.enqueue(r,{});await S.enqueue(r,{});assert.equal(S.state.queue.length,1);await S.removeQueue(C.identity(r));assert.equal(S.state.queue.length,0);});
test('library presence includes read-only groups and keeps duplicate matches distinct',async()=>{const {S,ctx}=setup(),calls=[];ctx.Zotero.Libraries={getAll:()=>[{libraryID:1,name:'Personal',libraryType:'user',editable:true},{libraryID:2,name:'Shared',libraryType:'group',editable:false},{libraryID:3,name:'Feed',libraryType:'feed',editable:true}]};S.existing=async(r,id)=>{calls.push(id);return id===2?[{id:10},{id:11}]:[];};const matches=await S.locate({title:'A',year:'2004'});assert.deepEqual(calls,[1,2]);assert.equal(matches.length,2);assert.equal(matches[0].libraryName,'Shared');assert.equal(matches[0].editable,false);});
test('simultaneous library-presence lookups share work but do not retain stale results',async()=>{const {S,ctx}=setup();let calls=0;ctx.Zotero.Libraries={getAll:()=>[{libraryID:1,name:'Personal',libraryType:'user',editable:true}]};S.existing=async()=>{calls++;await new Promise(r=>setTimeout(r,5));return [];};const record={DOI:'10.1234/shared',title:'A'};await Promise.all([S.locate(record),S.locate(record)]);assert.equal(calls,1);await S.locate(record);assert.equal(calls,2);});
test('a previously saved reading-list entry can be queued again',async()=>{const {S}=setup(),record={DOI:'10.1234/revisit',title:'Revisit'};await S.enqueue(record,{});S.state.queue[0].status='saved';await S.enqueue(record,{});assert.equal(S.state.queue.length,1);assert.equal(S.state.queue[0].status,'unread');});
test('enriched DOI retains exact legacy matches without merging conflicting DOIs',async()=>{const {S,ctx}=setup(),record={DOI:'10.1234/a',title:'Exact article title',year:'2020',author:'Smith'},rows=[{id:1,DOI:'',title:record.title,date:'2020-02'},{id:2,DOI:'10.1234/b',title:record.title,date:'2020'},{id:3,DOI:'10.1234/a',title:record.title,date:'2020'},{id:4,DOI:'',title:record.title,date:'2019'}].map(r=>({...r,getField(k){return this[k]||''},getCreators(){return [{lastName:'Smith'}]}}));ctx.Zotero.Search=class{addCondition(){}async search(){return rows.map(x=>x.id)}};ctx.Zotero.Items={getAsync:async ids=>rows.filter(r=>ids.includes(r.id))};assert.deepEqual(Array.from(await S.existing(record,1),r=>r.id),[1,3]);});

test('fresh and legacy installations enable current-item enrichment and retire artwork setting',async()=>{for(const legacy of [null,{schema:1,queue:[],metrics:[],cache:{},settings:{autoLookup:false,autoAuthors:false,networkConsent:false,networkEnabled:false,themeArtwork:false,readingFont:'Georgia',fontSize:16,preferInstalledMetrics:false,easyPubMedEnabled:false,metricYear:'2020'}}]){const {S,ctx}=setup();ctx.PathUtils={join:(...x)=>x.join('/'),parent:p=>p.slice(0,p.lastIndexOf('/'))};ctx.Zotero.DataDirectory={dir:'/fixture'};ctx.IOUtils.makeDirectory=async()=>{};ctx.IOUtils.exists=async p=>p.endsWith('state.json')&&!!legacy;ctx.IOUtils.readUTF8=async()=>JSON.stringify(legacy);S.detectMetricPlugins=async()=>{};await S.init();assert.equal(S.state.settings.networkEnabled,true);assert.equal(S.state.settings.autoLookup,true);assert.equal(S.state.settings.autoAuthors,true);assert.equal(S.state.settings.networkConsent,true);assert.equal(S.state.settings.themeArtwork,undefined);assert.equal(S.state.settings.preferInstalledMetrics,true);assert.equal(S.state.settings.easyPubMedEnabled,true);assert.equal(S.state.settings.metricYear,'');assert.equal(S.state.settings.readingFont,undefined);assert.equal(S.state.settings.fontSize,undefined);}});

test('automatic offline data preparation shares a request and backs off failure',async()=>{const {S}=setup();let calls=0;S.loadEasyPubMed=async()=>{calls++;await new Promise(r=>setTimeout(r,5));S.epIndex={};};assert.deepEqual(await Promise.all([S.ensureOfflineMetrics(),S.ensureOfflineMetrics()]),[true,true]);assert.equal(calls,1);assert.equal(await S.ensureOfflineMetrics(),false);S.epIndex=null;S.loadEasyPubMed=async()=>{calls++;throw Error('offline')};assert.equal(await S.ensureOfflineMetrics(),false);assert.equal(await S.ensureOfflineMetrics(),false);assert.equal(calls,2);S.dead=true;assert.equal(await S.ensureOfflineMetrics(),false);});

test('explicit refresh bypasses metadata cache while ordinary reading reuses it',async()=>{let calls=0;const {S}=setup(async()=>{calls++;return {response:{message:cross}};});const record={DOI:cross.DOI};await S.lookup(record);await S.lookup(record);assert.equal(calls,1);await S.lookup(record,{force:true});assert.equal(calls,2);});

test('DOI evidence survives incomplete author matching without changing citation verdict',async()=>{let calls=0;const {S}=setup(async()=>{calls++;return {response:{message:{...cross,author:[{given:'First',family:'Author'},{given:'David R.',family:'Liu',ORCID:'https://orcid.org/0000-0002-9943-7557'}]}}};});const record={DOI:cross.DOI,title:cross.title[0],creators:[{firstName:'David R.',lastName:'Liu'}]};const result=await S.lookup(record);assert.equal(result.doiRecord.DOI,cross.DOI);assert.equal(result.doiRecord.creators[1].ORCID,'https://orcid.org/0000-0002-9943-7557');const cached=await S.lookup(record);assert.equal(cached.status,result.status);assert.equal(cached.doiRecord.creators[1].ORCID,result.doiRecord.creators[1].ORCID);assert.equal(calls,1);});

test('unmatched refresh cannot erase confirmed publication and author evidence',async()=>{let response=cross;const {S}=setup(async()=>({response:{message:response}}));const record={DOI:cross.DOI,title:cross.title[0]};await S.lookup(record);response={DOI:cross.DOI,title:['Unrelated geological layers and volcanic activity']};const failed=await S.lookup(record,{force:true});assert.notEqual(failed.status,'matched');assert.equal(S.state.cache[C.identity(record)].value.status,'matched');assert.equal(S.state.cache[C.identity(record)].lastAttempt.status,failed.status);});
test('maintenance removes expired failures while preserving confirmed data and user records',async()=>{const {S}=setup();S.state.cache={yes:{time:1,value:{status:'matched',ranked:[]}},no:{time:1,value:{status:'missing'}}};S.state.authorCache={person:{expires:1,value:{status:'available',authors:[{lastName:'Smith',ORCID:'0000-0002-1825-0097'}]}}};S.state.queue=[{key:'keep'}];const result=await S.maintainCaches();assert.equal(result.removed,1);assert.ok(S.state.cache.yes);assert.ok(S.state.authorCache.person);assert.equal(S.state.queue[0].key,'keep');});
test('publication enrichment fills only missing fields from a verified match',async()=>{const {S}=setup(async()=>({response:{message:{...cross,'container-title':['Journal of Vision'],volume:'8',page:'1-9'}}})),r={DOI:cross.DOI,title:cross.title[0],year:'2018',pages:'2-4'};const filled=await S.publicationMetadata(r);assert.equal(filled.journal,'Journal of Vision');assert.equal(filled.pages,'2-4');assert.equal(filled.title,r.title);const own={...r,journal:'Local Journal'};assert.equal(await S.publicationMetadata(own),own);S.lookup=async()=>({status:'review',ranked:[{record:{journal:'Wrong journal'}}]});assert.equal(await S.publicationMetadata(r),r);});

test('complete publication details fill volume, pages and authors even when journal is already known',async()=>{const {S}=setup(async()=>({response:{message:{...cross,'container-title':['Remote Journal'],volume:'8',issue:'2',page:'1-9',author:[{given:'First',family:'Author'}]}}})),r={DOI:cross.DOI,title:cross.title[0],journal:'Confirmed Journal',creators:[]};const filled=await S.publicationMetadata(r,{complete:true});assert.equal(filled.journal,r.journal);assert.equal(filled.volume,'8');assert.equal(filled.issue,'2');assert.equal(filled.pages,'1-9');assert.equal(filled.creators.length,1);assert.equal(filled.creators[0].lastName,'Author');});
test('same DOI and title can fill missing venue across online/issue years without replacing year',async()=>{
 const title='Mst1/2 signalling to Yap: gatekeeper for liver size and tumour development',record={DOI:'10.1038/sj.bjc.6606011',title,year:'2011'},remote={...record,year:'2010',journal:'British Journal of Cancer',volume:'104',issue:'1',pages:'24–32'};const {S}=setup();S.lookup=async()=>C.decide(record,[remote]);const enriched=await S.publicationMetadata(record,{complete:true});assert.equal(enriched.journal,remote.journal);assert.equal(enriched.year,'2011');assert.equal(enriched.pages,'24–32');
 for(const change of [{DOI:'10.1234/wrong'},{title:'A different experiment on another subject'},{year:'2008'}]){S.lookup=async()=>({status:'review',ranked:[{record:{...remote,...change}}]});assert.equal((await S.publicationMetadata(record,{complete:true})).journal,undefined);}
});
