const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){
 const prefs=new Map(),logins=[],requests=[];
 class Login{init(origin,formActionOrigin,httpRealm,username,password){Object.assign(this,{origin,formActionOrigin,httpRealm,username,password});}}
 class XHR{
  constructor(){this.channel={};this.responseText='';this.status=200;requests.push(this);}
  open(method,url){Object.assign(this,{method,url});}setRequestHeader(k,v){(this.headers||={})[k]=v;}
  send(body){this.body=JSON.parse(body);}abort(){this.onabort?.();}
  chunk(data){this.responseText+=data;this.onprogress?.();}end(data=''){this.responseText+=data;this.onload?.();}
 }
 const context={Services:{logins:{findLogins:origin=>logins.filter(l=>l.origin===origin),addLoginAsync:async l=>logins.push(l),modifyLogin:(old,l)=>logins.splice(logins.indexOf(old),1,l),removeLogin:l=>logins.splice(logins.indexOf(l),1)}},ChromeUtils:{importESModule:()=>({nsLoginInfo:Login}),generateQI:()=>function(){return this}},Components:{results:{NS_ERROR_ABORT:99}}};vm.createContext(context);context.Zotero={getMainWindow:()=>({URL,XMLHttpRequest:XHR,setTimeout,clearTimeout})};context.CiteLensAbstracts={text:s=>s};vm.runInContext(fs.readFileSync('addon/translation.js','utf8'),context);const p=context.CiteLensTranslation;p.init();Object.assign(p,{get:(k,d)=>prefs.get(k)??d,set:(k,v)=>prefs.set(k,v),syncSettings(){},translationCache:new Map(),translationJobs:new Map()});return{p,prefs,logins,requests};
}
const event=content=>'data: '+JSON.stringify({choices:[{delta:{content}}]})+'\n\n';
async function ready(s,id='minimax'){await s.p.saveLLM({...s.p.llmConfig(id),model:'test-model'},'qa-key-not-real');}
test('secure key store excludes preferences, isolates provider+endpoint and replaces key',async()=>{const s=setup();await ready(s);assert.equal(s.logins.length,1);assert.ok(!JSON.stringify([...s.prefs]).includes('qa-key'));await s.p.saveLLM(s.p.llmConfig(),'new-key');assert.equal(s.logins.length,1);assert.equal(s.p.llmKey(s.p.llmConfig()),'new-key');assert.equal(s.p.llmKey({...s.p.llmConfig(),endpoint:'https://other.example/v1'}),'');s.p.removeLLMKey(s.p.llmConfig());assert.equal(s.logins.length,0);});
test('rejects URL credentials, query keys, insecure remote HTTP and empty models',()=>{const {p}=setup();for(const endpoint of ['https://user:secret@example.com/v1','https://example.com/v1?key=secret','http://example.com/v1','ftp://localhost/v1'])assert.throws(()=>p.validateLLM({endpoint,model:'m'}));assert.equal(p.validateLLM({endpoint:'http://localhost:8000/v1',model:'m'}).endpoint,'http://localhost:8000/v1');assert.throws(()=>p.validateLLM({endpoint:'https://example.com',model:''}));});
test('SSE split across chunks streams text, ignores reasoning, shares job and caches',async()=>{const s=setup();await ready(s);const a=[],b=[];const p1=s.p.translateLLM('Retina','en',{target:'zh-Hans',onPartial:x=>a.push(x)}),p2=s.p.translateLLM('Retina','en',{target:'zh-Hans',onPartial:x=>b.push(x)});assert.equal(s.requests.length,1);const xhr=s.requests[0];xhr.chunk('data: {"choices":[{"delta":{"reasoning_content":"private"}}]}\n\n');const data=event('视网膜');xhr.chunk(data.slice(0,20));assert.equal(a.length,0);xhr.chunk(data.slice(20));xhr.end('data: [DONE]\n\n');const r=await p1;await p2;assert.equal(r.text,'视网膜');assert.deepEqual(a,['视网膜']);assert.deepEqual(b,a);await s.p.translateLLM('Retina','en',{target:'zh-Hans'});assert.equal(s.requests.length,1);assert.equal(xhr.headers.Authorization,'Bearer qa-key-not-real');});
test('JSON compatibility fallback and Anthropic text-only deltas work',async()=>{for(const id of ['openai','anthropic']){const s=setup();await ready(s,id);const job=s.p.translateLLM('Retina','en',{target:'ja'}),xhr=s.requests[0];if(id==='anthropic'){assert.equal(xhr.headers['x-api-key'],'qa-key-not-real');assert.ok(xhr.url.endsWith('/messages'));xhr.chunk('event: content_block_delta\ndata: {"type":"content_block_delta","delta":{"type":"text_delta","text":"網膜"}}\n\n');xhr.end('data: {"type":"message_stop"}\n\n');}else xhr.end(JSON.stringify({choices:[{message:{content:'網膜'},finish_reason:'stop'}]}));assert.equal((await job).text,'網膜');}});
test('errors never disclose provider body or credentials and do not cache truncated streams',async()=>{for(const type of ['auth','truncated','disconnected','error','empty']){const s=setup();await ready(s);const task=s.p.translateLLM('Cells','en'),xhr=s.requests[0];const check=assert.rejects(task,e=>!e.message.includes('qa-key'));if(type==='auth'){xhr.status=401;xhr.end('qa-key-not-real');}else if(type==='truncated'){xhr.chunk(event('部分译文'));xhr.end('data: {"choices":[{"delta":{},"finish_reason":"length"}]}\n\n');}else if(type==='disconnected'){xhr.chunk(event('部分'));xhr.end();}else if(type==='error')xhr.end('data: {"error":{"message":"qa-key-not-real"}}\n\ndata: [DONE]\n\n');else xhr.end('data: [DONE]\n\n');await check;assert.equal(s.p.translationCache.size,0);}});
test('credential or model change invalidates cached translations; redirects are blocked',async()=>{const s=setup();await ready(s);const a=s.p.translateLLM('Cells','en'),x=s.requests[0];let result;x.channel.notificationCallbacks.asyncOnChannelRedirect(null,null,0,{onRedirectVerifyCallback:r=>result=r});assert.equal(result,99);x.end(JSON.stringify({choices:[{message:{content:'细胞'},finish_reason:'stop'}]}));await a;await s.p.saveLLM({...s.p.llmConfig(),model:'another'},'changed-key');const b=s.p.translateLLM('Cells','en');assert.equal(s.requests.length,2);s.requests[1].end(JSON.stringify({choices:[{message:{content:'細胞'},finish_reason:'stop'}]}));assert.equal((await b).text,'細胞');});

test('free engines post only requested text and cache the result',async()=>{for(const provider of ['tencenttransmart','bing','google']){const s=setup();s.p.set('translationProvider',provider);const calls=[];s.p.request=async(method,url,opts)=>{calls.push({method,url,opts});return {response:provider==='google'?[[['翻译内容']]]:provider==='bing'?[{translations:[{text:'翻译内容'}]}]:{auto_translation:['翻译内容']}};};const result=await s.p.translate('Gene expression.','en');assert.equal(result.text,'翻译内容');assert.equal(calls.length,1);assert.equal(calls[0].method,'POST');assert.ok(!calls[0].url.includes('Gene'));await s.p.translate('Gene expression.','en');assert.equal(calls.length,1);}});
test('abstract translation preserves paragraph boundaries and cancels before the next chunk',async()=>{const {p}=setup(),seen=[];p.translate=async text=>{seen.push(text);return {text:'译 '+text,source:'fixture'};};const parts=p.chunks(('Cells develop. '.repeat(180))+'\n\nDifferent outcomes.');assert.ok(parts.length>2&&parts.every(s=>s.length<=1600));const r=await p.abstract('First paragraph.\n\nSecond paragraph.');assert.equal(r.text,'译 First paragraph.\n\n译 Second paragraph.');let cancelled=false;p.translate=async()=>{cancelled=true;return {text:'部分',source:'fixture'};};await assert.rejects(p.abstract('First.\n\nSecond.',{cancelled:()=>cancelled}),/取消/);});
test('protected scientific ranges survive translation and traditional target rejects unsupported engine',async()=>{const {p}=setup(),g=p.translationTerms('Müller cells were measured in 10–20 samples.','zh-Hans');assert.ok(g.text.includes('[PNX000]'));assert.ok(g.restore(g.text).includes('米勒细胞'));assert.ok(g.restore(g.text).includes('10～20'));await assert.rejects(p.translate('Cells','en',{provider:'tencenttransmart',target:'zh-Hant'}),/繁体中文/);});
