const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){
 const prefs=new Map(),logins=[],requests=[];
 class Login{init(origin,formActionOrigin,httpRealm,username,password){Object.assign(this,{origin,formActionOrigin,httpRealm,username,password});}}
 class XHR{
  constructor(){this.channel={};this.responseText='';this.status=200;requests.push(this);}
  open(method,url){Object.assign(this,{method,url});}setRequestHeader(k,v){(this.headers||={})[k]=v;}
  send(body){this.body=JSON.parse(body);}abort(){this.onabort?.();}
  chunk(data){this.responseText+=data;this.onprogress?.();}end(data=''){this.responseText+=data;this.onload?.();}
 }
 const context={Services:{logins:{findLogins:origin=>logins.filter(l=>l.origin===origin),addLoginAsync:async l=>logins.push(l),modifyLogin:(old,l)=>logins.splice(logins.indexOf(old),1,l),removeLogin:l=>logins.splice(logins.indexOf(l),1)}},ChromeUtils:{importESModule:()=>({nsLoginInfo:Login}),generateQI:()=>function(){return this}},Components:{results:{NS_ERROR_ABORT:99},interfaces:{nsIRequest:{LOAD_ANONYMOUS:16384}}}};vm.createContext(context);context.Zotero={getMainWindow:()=>({URL,XMLHttpRequest:XHR,setTimeout,clearTimeout})};context.CiteLensAbstracts={text:s=>s};vm.runInContext(fs.readFileSync('addon/translation.js','utf8'),context);const p=context.CiteLensTranslation;p.init();Object.assign(p,{get:(k,d)=>prefs.get(k)??d,set:(k,v)=>prefs.set(k,v),syncSettings(){},translationCache:new Map(),translationJobs:new Map()});return{p,prefs,logins,requests};
}
const event=content=>'data: '+JSON.stringify({choices:[{delta:{content}}]})+'\n\n';
async function ready(s,id='minimax'){await s.p.saveLLM({...s.p.llmConfig(id),model:'test-model'},'qa-key-not-real');}
test('secure key store excludes preferences, isolates provider+endpoint and replaces key',async()=>{const s=setup();await ready(s);assert.equal(s.logins.length,1);assert.ok(!JSON.stringify([...s.prefs]).includes('qa-key'));await s.p.saveLLM(s.p.llmConfig(),'new-key');assert.equal(s.logins.length,1);assert.equal(s.p.llmKey(s.p.llmConfig()),'new-key');assert.equal(s.p.llmKey({...s.p.llmConfig(),endpoint:'https://other.example/v1'}),'');s.p.removeLLMKey(s.p.llmConfig());assert.equal(s.logins.length,0);});
test('rejects URL credentials, query keys, insecure remote HTTP and empty models',()=>{const {p}=setup();for(const endpoint of ['https://user:secret@example.com/v1','https://example.com/v1?key=secret','http://example.com/v1','ftp://localhost/v1'])assert.throws(()=>p.validateLLM({endpoint,model:'m'}));assert.equal(p.validateLLM({endpoint:'http://localhost:8000/v1',model:'m'}).endpoint,'http://localhost:8000/v1');assert.throws(()=>p.validateLLM({endpoint:'https://example.com',model:''}));});
test('SSE split across chunks streams text, ignores reasoning, shares job and caches',async()=>{const s=setup();await ready(s);const a=[],b=[];const p1=s.p.translateLLM('Retina','en',{target:'zh-Hans',onPartial:x=>a.push(x)}),p2=s.p.translateLLM('Retina','en',{target:'zh-Hans',onPartial:x=>b.push(x)});assert.equal(s.requests.length,1);const xhr=s.requests[0];xhr.chunk('data: {"choices":[{"delta":{"reasoning_content":"private"}}]}\n\n');const data=event('视网膜');xhr.chunk(data.slice(0,20));assert.equal(a.length,0);xhr.chunk(data.slice(20));xhr.end('data: [DONE]\n\n');const r=await p1;await p2;assert.equal(r.text,'视网膜');assert.deepEqual(a,['视网膜']);assert.deepEqual(b,a);await s.p.translateLLM('Retina','en',{target:'zh-Hans'});assert.equal(s.requests.length,1);assert.equal(xhr.headers.Authorization,'Bearer qa-key-not-real');});
test('JSON compatibility fallback and Anthropic text-only deltas work',async()=>{for(const id of ['openai','anthropic']){const s=setup();await ready(s,id);const job=s.p.translateLLM('Retina','en',{target:'ja'}),xhr=s.requests[0];if(id==='anthropic'){assert.equal(xhr.headers['x-api-key'],'qa-key-not-real');assert.ok(xhr.url.endsWith('/messages'));xhr.chunk('event: content_block_delta\ndata: {"type":"content_block_delta","delta":{"type":"text_delta","text":"網膜"}}\n\n');xhr.end('data: {"type":"message_stop"}\n\n');}else xhr.end(JSON.stringify({choices:[{message:{content:'網膜'},finish_reason:'stop'}]}));assert.equal((await job).text,'網膜');}});
test('errors never disclose provider body or credentials and do not cache truncated streams',async()=>{for(const type of ['auth','truncated','disconnected','error','empty']){const s=setup();await ready(s);const task=s.p.translateLLM('Cells','en'),xhr=s.requests[0];const check=assert.rejects(task,e=>!e.message.includes('qa-key'));if(type==='auth'){xhr.status=401;xhr.end('qa-key-not-real');}else if(type==='truncated'){xhr.chunk(event('部分译文'));xhr.end('data: {"choices":[{"delta":{},"finish_reason":"length"}]}\n\n');}else if(type==='disconnected'){xhr.chunk(event('部分'));xhr.end();}else if(type==='error')xhr.end('data: {"error":{"message":"qa-key-not-real"}}\n\ndata: [DONE]\n\n');else xhr.end('data: [DONE]\n\n');await check;assert.equal(s.p.translationCache.size,0);}});
test('credential or model change invalidates cached translations; redirects are blocked',async()=>{const s=setup();await ready(s);const a=s.p.translateLLM('Cells','en'),x=s.requests[0];let result;x.channel.notificationCallbacks.asyncOnChannelRedirect(null,null,0,{onRedirectVerifyCallback:r=>result=r});assert.equal(result,99);x.end(JSON.stringify({choices:[{message:{content:'细胞'},finish_reason:'stop'}]}));await a;await s.p.saveLLM({...s.p.llmConfig(),model:'another'},'changed-key');const b=s.p.translateLLM('Cells','en');assert.equal(s.requests.length,2);s.requests[1].end(JSON.stringify({choices:[{message:{content:'細胞'},finish_reason:'stop'}]}));assert.equal((await b).text,'細胞');});

test('free engines post only requested text and cache the result',async()=>{for(const provider of ['tencenttransmart','bing','google']){const s=setup();s.p.set('translationProvider',provider);const calls=[];s.p.request=async(method,url,opts)=>{calls.push({method,url,opts});return {response:provider==='google'?[[['翻译内容']]]:provider==='bing'?[{translations:[{text:'翻译内容'}]}]:{auto_translation:['翻译内容']}};};const result=await s.p.translate('Gene expression.','en');assert.equal(result.text,'翻译内容');assert.equal(calls.length,1);assert.equal(calls[0].method,'POST');assert.ok(!calls[0].url.includes('Gene'));await s.p.translate('Gene expression.','en');assert.equal(calls.length,1);}});
test('abstract translation preserves paragraph boundaries and cancels before the next chunk',async()=>{const {p}=setup(),seen=[];p.translate=async text=>{seen.push(text);return {text:'译 '+text,source:'fixture'};};const parts=p.chunks(('Cells develop. '.repeat(180))+'\n\nDifferent outcomes.');assert.ok(parts.length>2&&parts.every(s=>s.length<=1600));const r=await p.abstract('First paragraph.\n\nSecond paragraph.');assert.equal(r.text,'译 First paragraph.\n\n译 Second paragraph.');let cancelled=false;p.translate=async()=>{cancelled=true;return {text:'部分',source:'fixture'};};await assert.rejects(p.abstract('First.\n\nSecond.',{cancelled:()=>cancelled}),/取消/);});
test('protected scientific ranges survive translation and traditional target rejects unsupported engine',async()=>{const {p}=setup(),g=p.translationTerms('Müller cells were measured in 10–20 samples.','zh-Hans');assert.ok(g.text.includes('[PNX000]'));assert.ok(g.restore(g.text).includes('米勒细胞'));assert.ok(g.restore(g.text).includes('10～20'));await assert.rejects(p.translate('Cells','en',{provider:'tencenttransmart',target:'zh-Hant'}),/繁体中文/);});
test('bilingual mode pairs each original unit with its own translation including incremental results',async()=>{const {p}=setup();p.translate=async text=>({text:'译：'+text,source:'fixture'});const updates=[],r=await p.abstract('First sentence. Second sentence.\n\nFinal paragraph.',{paired:true,onPartial:(text,pairs)=>updates.push(pairs.map(x=>({...x})))});assert.equal(r.pairs.length,3);assert.ok(r.pairs.every(x=>x.translated==='译：'+x.original));assert.equal(updates.at(-1).length,3);assert.ok(r.text.includes('Final paragraph.'));});
test('cancelled bilingual translation does not emit late pairs',async()=>{const {p}=setup();let stop=false,release,updates=0;p.translate=()=>new Promise(r=>release=r);const pending=p.abstract('First. Second.',{paired:true,cancelled:()=>stop,onPartial:()=>updates++});stop=true;release({text:'late',source:'fixture'});await assert.rejects(pending,/取消/);assert.equal(updates,0);});

test('each built-in provider supplies translation and clustering defaults; legacy overrides survive',()=>{
 const {p,prefs}=setup();for(const preset of p.llmPresets.filter(p=>p.id!=='custom')){const t=p.llmTaskConfig('translation',preset.id),c=p.llmTaskConfig('clustering',preset.id);assert.ok(t.model&&c.model&&t.endpoint);assert.equal(t.endpoint,c.endpoint);}
 prefs.set('llmConfigs',JSON.stringify({openai:{endpoint:'https://example.com/v1',model:'my-translation'}}));assert.equal(p.llmConfig('openai').model,'my-translation');assert.equal(p.llmConfig('openai').clusterModel,'gpt-4.1-2025-04-14');assert.equal(p.llmTaskConfig('clustering','openai').endpoint,'https://example.com/v1');
});
test('one stored credential routes each task to its own model without enabling cloud processing',async()=>{
 const s=setup();s.prefs.set('translationProvider','bing');await s.p.saveLLM({...s.p.llmConfig('qwen'),model:'my-translation',clusterModel:'my-cluster'},'qa-key-not-real',{activateTranslation:false});assert.equal(s.prefs.get('translationProvider'),'bing');assert.equal(s.prefs.get('networkEngine'),undefined);assert.equal(s.logins.length,1);
 const translated=s.p.translateLLM('Cells','en'),classified=s.p.clusterLLM([{id:'p1',title:'Retinal cells',abstract:'Development of neurons',DOI:'private-doi',authors:['private-author']}]);assert.equal(s.requests[0].body.model,'my-translation');assert.equal(s.requests[1].body.model,'my-cluster');assert.equal(s.requests[0].headers.Authorization,s.requests[1].headers.Authorization);assert.ok(!JSON.stringify(s.requests[1].body).includes('private-'));assert.ok(s.requests[1].body.messages[0].content.includes('Group scientific papers'));
 s.requests[0].end(JSON.stringify({choices:[{message:{content:'细胞'}}]}));s.requests[1].end(JSON.stringify({choices:[{message:{content:JSON.stringify({papers:[{id:'p1',topic:'Retinal development',keywords:['retina']}]})}}]}));await translated;const rows=await classified;assert.equal(rows[0].topic,'Retinal development');rows[0].keywords.push('mutation');assert.equal((await s.p.clusterLLM([{id:'p1',title:'Retinal cells',abstract:'Development of neurons'}]))[0].keywords.length,1);
});
test('clustering rejects extra, duplicate, missing and malformed results without caching',async()=>{
 for(const papers of [[{id:'other',topic:'Cells',keywords:[]}],[],[{id:'p1',topic:'',keywords:[]}],[{id:'p1',topic:'Cells',keywords:'oops'}],[null]]){const s=setup();await ready(s);const job=s.p.clusterLLM([{id:'p1',title:'Cells'}]);const check=assert.rejects(job);s.requests[0].end(JSON.stringify({choices:[{message:{content:JSON.stringify({papers})}}]}));await check;assert.equal(s.p.topicCache.size,0);}
});
test('connection test reports translation success and clustering failure separately',async()=>{
 const s=setup();await ready(s);const progress=[],job=s.p.testLLM(s.p.llmConfig(),{onProgress:t=>progress.push(t)});s.requests[0].end(JSON.stringify({choices:[{message:{content:'视网膜发育'}}]}));await new Promise(r=>setImmediate(r));assert.equal(s.requests.length,2);s.requests[1].status=403;s.requests[1].end('SECRET BODY');const result=await job;assert.equal(result.translation.ok,true);assert.equal(result.clustering.ok,false);assert.ok(!JSON.stringify(result).includes('SECRET'));assert.deepEqual(progress,['translation','clustering']);
});
function nextCatalog(p){const value=JSON.parse(JSON.stringify(p.modelCatalog()));value.version='2026-10-06.2';for(const row of value.providers){row.model+='-new';row.clusterModel+='-new';}return value;}
test('published catalog matches bundled defaults and rejects hostile endpoints and malformed rows',()=>{
 const {p}=setup(),disk=JSON.parse(fs.readFileSync('model-presets.json'));assert.equal(JSON.stringify(p.validateModelCatalog(disk)),JSON.stringify(p.validateModelCatalog(p.modelCatalog())));
 for(const mutate of [c=>c.providers[0].endpoint='https://evil.example/v1',c=>c.providers[0].endpoint='https://api.minimax.cn/v1?api_key=x',c=>c.providers[0].model='<script>',c=>c.providers.push(c.providers[0]),c=>c.providers[1].id=c.providers[0].id,c=>c.version='bad']){const c=nextCatalog(p);mutate(c);assert.throws(()=>p.validateModelCatalog(c));}
});
test('catalog refresh is anonymous, shared by concurrent clicks, atomic and preserves overrides and credentials',async()=>{
 const s=setup();await s.p.saveLLM(s.p.llmConfig('qwen'),'qa-key-not-real',{activateTranslation:false});await s.p.saveLLM({...s.p.llmConfig('openai'),model:'custom-model',clusterModel:'custom-cluster'},'qa-key-other',{activateTranslation:false});const oldKeys=JSON.stringify(s.logins),catalog=nextCatalog(s.p),first=s.p.updateModelCatalog(),second=s.p.updateModelCatalog();assert.equal(s.requests.length,1);const x=s.requests[0];assert.equal(x.method,'GET');assert.equal(x.body,null);assert.ok(!Object.keys(x.headers).some(k=>/authorization|key/i.test(k)));x.end(JSON.stringify(catalog));const result=await first;await second;assert.equal(result.changed,true);assert.equal(s.p.llmConfig('qwen').model,'qwen3.8-flash-new');assert.equal(s.p.llmConfig('openai').model,'custom-model');assert.equal(s.p.llmConfig('openai').clusterModel,'custom-cluster');assert.equal(JSON.stringify(s.logins),oldKeys);
 const cached=s.prefs.get('llmModelCatalog'),bad=s.p.updateModelCatalog(),check=assert.rejects(bad);s.requests[1].end('{"schema":1}');await check;assert.equal(s.prefs.get('llmModelCatalog'),cached);
});
test('catalog endpoint changes never move saved keys; new accounts receive updated defaults',async()=>{
 const s=setup();await ready(s,'minimax');const old=s.p.llmConfig('minimax').endpoint,catalog=nextCatalog(s.p);catalog.providers.find(p=>p.id==='minimax').endpoint='https://api.minimaxi.com/v1';const job=s.p.updateModelCatalog();s.requests[0].end(JSON.stringify(catalog));await job;assert.equal(s.p.llmConfig('minimax').endpoint,old);assert.equal(s.p.llmPreset('minimax').endpoint,'https://api.minimaxi.com/v1');assert.equal(s.p.llmKey(s.p.llmPreset('minimax')),'');assert.equal(s.p.llmKey(s.p.llmConfig('minimax')),'qa-key-not-real');
});
test('catalog rejects rollbacks and retains defaults on network failure',async()=>{
 const s=setup(),old=nextCatalog(s.p);old.version='2026-10-01.1';let job=s.p.updateModelCatalog(),check=assert.rejects(job,/较旧/);s.requests[0].end(JSON.stringify(old));await check;assert.equal(s.prefs.get('llmModelCatalog'),undefined);job=s.p.updateModelCatalog();check=assert.rejects(job,/连接失败/);s.requests[1].onerror();await check;assert.equal(s.p.modelCatalog().version,s.p.modelCatalogVersion);
});
test('stopping plugin cancels model tests without starting the second paid request',async()=>{
 const s=setup();await ready(s);const pending=s.p.testLLM(s.p.llmConfig());s.p.stop();const result=await pending;assert.equal(result.translation.ok,false);assert.equal(result.clustering.ok,false);assert.equal(s.requests.length,1);await assert.rejects(s.p.updateModelCatalog(),/取消/);
});
test('editable model menus rank task defaults and preserve custom entries without mixing providers',()=>{const {p,prefs}=setup();assert.equal(p.modelChoices('minimax','translation')[0],'MiniMax-M2.7-highspeed');assert.equal(p.modelChoices('minimax','clustering')[0],'MiniMax-M3');assert.equal(new Set(p.modelChoices('deepseek','translation')).size,p.modelChoices('deepseek','translation').length);prefs.set('llmConfigs',JSON.stringify({qwen:{model:'my-translation',clusterModel:'my-cluster'}}));assert.ok(p.modelChoices('qwen','translation','draft-model').includes('draft-model'));assert.ok(!p.modelChoices('openai','translation').includes('my-cluster'));});
test('updated model catalogs validate optional selectable model arrays',()=>{const {p}=setup(),catalog=nextCatalog(p);catalog.providers[0].models=['model-a','model-b','model-a'];assert.equal(p.validateModelCatalog(catalog).providers[0].models.length,2);for(const models of [['<script>'],Array(81).fill('valid'),'bad']){catalog.providers[0].models=models;assert.throws(()=>p.validateModelCatalog(catalog));}});
test('authenticated model discovery paginates, filters non-text models and does not change task choices',async()=>{const s=setup();await ready(s,'anthropic');const config=s.p.llmConfig('anthropic'),job=s.p.discoverModels(config);assert.ok(s.requests[0].url.endsWith('/models?limit=100'));assert.equal(s.requests[0].headers['x-api-key'],'qa-key-not-real');s.requests[0].end(JSON.stringify({data:[{id:'claude-sonnet-5-5'}],has_more:true,last_id:'claude-sonnet-5-5'}));await new Promise(r=>setImmediate(r));assert.ok(s.requests[1].url.includes('&after_id=claude-sonnet-5-5'));s.requests[1].end(JSON.stringify({data:[{id:'claude-haiku-4-5-20251001'},{id:'embedding-1'}],has_more:false}));const result=await job;assert.equal(result.count,2);assert.equal(s.p.llmConfig('anthropic').model,'test-model');assert.ok(s.p.discoveredModels(config).includes('claude-sonnet-5-5'));});
test('failed or partial discovery preserves previous lists and never reveals provider errors',async()=>{const s=setup();await ready(s,'deepseek');const config=s.p.llmConfig('deepseek');s.prefs.set('llmDiscoveredModels',JSON.stringify({deepseek:{endpoint:config.endpoint,models:['known-model']}}));const before=s.prefs.get('llmDiscoveredModels'),job=s.p.discoverModels(config),reject=assert.rejects(job,e=>!e.message.includes('qa-key'));s.requests[0].end(JSON.stringify({data:[{id:'new-model'}],has_more:true,last_id:'new-model'}));await new Promise(r=>setImmediate(r));s.requests[1].status=401;s.requests[1].end('qa-key-not-real');await reject;assert.equal(s.prefs.get('llmDiscoveredModels'),before);});
test('discovery does not send keys to custom or untrusted endpoints and rejects redirects',async()=>{const s=setup();await ready(s,'openai');assert.equal(await s.p.discoverModels({...s.p.llmConfig('openai'),endpoint:'https://not-the-provider.example/v1'}),null);assert.equal(s.requests.length,0);const job=s.p.discoverModels(s.p.llmConfig('openai')),xhr=s.requests[0];let code;xhr.channel.notificationCallbacks.asyncOnChannelRedirect(null,null,0,{onRedirectVerifyCallback:x=>code=x});assert.equal(code,99);xhr.end(JSON.stringify({data:[{id:'gpt-4.1'}]}));await job;});
test('group naming sends only representative scientific text and rejects years or keyword clouds',async()=>{for(const topic of ['Retinal development','retina · cells · cone','Smith 2020']){const s=setup();await ready(s);const promise=s.p.nameTopicsLLM([{id:'g',papers:[{title:'Retinal cell differentiation',abstract:'',authors:['PRIVATE-AUTHOR'],DOI:'PRIVATE-DOI'}]}]);const body=s.requests[0].body;assert.ok(!JSON.stringify(body).includes('PRIVATE'));assert.ok(body.messages[0].content.includes('2–7 English words'));const check=topic==='Retinal development'?promise:assert.rejects(promise);s.requests[0].end(JSON.stringify({choices:[{message:{content:JSON.stringify({topics:[{id:'g',topic}]})}}]}));await check;}});

test('MiniMax group names tolerate leading whitespace before a JSON code fence in SSE and JSON responses',async()=>{for(const streamed of [true,false]){const s=setup();await ready(s);const job=s.p.nameTopicsLLM([{id:'g',papers:[{title:'Retinal cell differentiation',abstract:''}]}]);const text=' \n\n```json\n'+JSON.stringify({topics:[{id:'g',topic:'Retinal cell differentiation'}]})+'\n```\n';if(streamed){s.requests[0].chunk(event(text.slice(0,6)));s.requests[0].chunk(event(text.slice(6)));s.requests[0].end('data: [DONE]\n\n');}else s.requests[0].end(JSON.stringify({choices:[{message:{content:text},finish_reason:'stop'}]}));const rows=await job;assert.equal(rows[0].topic,'Retinal cell differentiation');}});

test('group naming rejects generic placeholders and requests shared evidence rather than outliers',async()=>{const s=setup();await ready(s);const job=s.p.nameTopicsLLM([{id:'g',papers:[{title:'Neurocysticercosis and oncogenesis',abstract:''},{title:'Neurocysticercosis: an enigmatic disease',abstract:''}]}]);assert.match(s.requests[0].body.messages[0].content,/most supplied papers/);const rejected=assert.rejects(job,/主题名称不符合要求/);s.requests[0].end(JSON.stringify({choices:[{message:{content:JSON.stringify({topics:[{id:'g',topic:'Scientific research'}]})}}]}));await rejected;});
