const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(check){const addon={version:'0.3.3',applyBackgroundUpdates:1,findUpdates:l=>check(l),cancelUpdate(){}},manager={getAddonByID:async()=>addon,UPDATE_WHEN_USER_REQUESTED:1,AUTOUPDATE_DEFAULT:1,AUTOUPDATE_ENABLE:2,AUTOUPDATE_DISABLE:0,shouldAutoUpdate:a=>a.applyBackgroundUpdates!==0,updateEnabled:true};const ctx={ChromeUtils:{importESModule:()=>({AddonManager:manager})},Zotero:{getMainWindow:()=>({setTimeout,clearTimeout}),logError(){}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../addon/updater.js'),'utf8'),ctx);return {U:ctx.CiteLensUpdater,addon,manager};}
test('native auto-update policy persists through reload',async()=>{const {U,addon}=setup(()=>{});await U.start({id:'x',version:'0.4.0'});await U.setAutomatic(false);assert.equal(addon.applyBackgroundUpdates,0);assert.equal(U.automatic,false);await U.setAutomatic(true);assert.equal(addon.applyBackgroundUpdates,2);U.stop();});
test('current version and global update disable are represented accurately',async()=>{const {U,manager}=setup(l=>l.onUpdateFinished(null,0));manager.updateEnabled=false;await U.start({id:'x'});assert.equal(U.globallyEnabled,false);await U.check();assert.equal(U.phase,'current');U.stop();});
test('duplicate manual checks share the active operation',async()=>{let calls=0,done;const {U}=setup(l=>{calls++;done=()=>l.onUpdateFinished(null,0)});await U.start({id:'x'});const pending=U.check();await new Promise(r=>setImmediate(r));await U.check();assert.equal(calls,1);done();await pending;U.stop();});
test('update discovery and installation use the native install object',async()=>{let listener,installed=0;const install={version:'0.4.0',addListener:l=>listener=l,removeListener(){},async install(){installed++;listener.onInstallEnded();}};const {U}=setup(l=>{l.onUpdateAvailable(null,install);l.onUpdateFinished(null,0)});await U.start({id:'x'});await U.check();assert.equal(U.phase,'available');await U.apply();assert.equal(installed,1);assert.equal(U.phase,'current');U.stop();});
test('failed discovery clears stale updates and allows retry',async()=>{const {U}=setup(l=>l.onUpdateFinished(null,7));await U.start({id:'x'});U.install={version:'stale'};await U.check();assert.equal(U.phase,'error');assert.equal(U.install,null);U.stop();});
test('download or integrity failure preserves the existing version',async()=>{let listener;const install={version:'0.4.0',addListener:l=>listener=l,removeListener(){},async install(){listener.onDownloadFailed();}};const {U,addon}=setup(l=>{l.onUpdateAvailable(null,install);l.onUpdateFinished(null,0)});await U.start({id:'x'});await U.check();await U.apply();assert.equal(U.phase,'error');assert.equal(addon.version,'0.3.3');assert.equal(U.install,null);U.stop();});
test('stopping cancels pending checks and ignores late callbacks',async()=>{let callback;const {U}=setup(l=>callback=l);await U.start({id:'x'});const pending=U.check();await new Promise(r=>setImmediate(r));U.stop();callback.onUpdateAvailable(null,{version:'late'});callback.onUpdateFinished(null,0);await pending;assert.equal(U.install,null);assert.equal(U.subscribers.size,0);});
function clock(U){let id=0;const timers=new Map();U.host={setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id)};return {timers,fire:ms=>{const entry=[...timers].find(([,t])=>t.ms===ms);assert.ok(entry,'deadline armed');timers.delete(entry[0]);entry[1].fn();}};}
const tick=()=>new Promise(r=>setImmediate(r));
test('lookup timeout unlocks retry and ignores the stale lookup',async()=>{let discover=0,resolve;const {U,manager,addon}=setup(l=>{discover++;l.onUpdateFinished(null,0)});await U.start({id:'x'});const c=clock(U);manager.getAddonByID=()=>new Promise(r=>resolve=r);const pending=U.check();await tick();c.fire(U.checkTimeout);await pending;assert.equal(U.phase,'error');assert.match(U.message,/超时/);assert.equal(U.cancelCheck,null);manager.getAddonByID=async()=>addon;await U.check();resolve(addon);await tick();assert.equal(discover,1);assert.equal(U.phase,'current');assert.equal(c.timers.size,0);U.stop();});
test('discovery deadline cancels native check and ignores late update callbacks',async()=>{let listener,cancelled=0;const {U,addon}=setup(l=>listener=l);await U.start({id:'x'});addon.cancelUpdate=()=>cancelled++;const c=clock(U),pending=U.check();await tick();c.fire(U.checkTimeout);await pending;listener.onUpdateAvailable(null,{version:'late'});listener.onUpdateFinished(null,0);assert.equal(cancelled,1);assert.equal(U.phase,'error');assert.equal(U.install,null);assert.equal(c.timers.size,0);U.stop();});
test('stop settles a pending addon lookup without starting discovery',async()=>{let resolve,calls=0;const {U,manager,addon}=setup(()=>calls++);await U.start({id:'x'});const c=clock(U);manager.getAddonByID=()=>new Promise(r=>resolve=r);const pending=U.check();await tick();U.stop();await pending;resolve(addon);await tick();assert.equal(calls,0);assert.equal(c.timers.size,0);});
test('stalled installation times out, detaches listener, cancels and allows a fresh check',async()=>{let listener,cancelled=0,removed=0;const install={version:'next',addListener:l=>listener=l,removeListener:()=>removed++,install:()=>new Promise(()=>{}),cancel:()=>cancelled++};const {U}=setup(l=>{l.onUpdateAvailable(null,install);l.onUpdateFinished(null,0)});await U.start({id:'x'});const c=clock(U);await U.check();const pending=U.apply();c.fire(U.installTimeout);await pending;listener.onInstallEnded();assert.equal(U.phase,'error');assert.equal(U.install,null);assert.equal(cancelled,1);assert.equal(removed,1);assert.equal(c.timers.size,0);await U.check();assert.equal(U.phase,'available');U.stop();});
test('successful addon shutdown settles install without cancelling the native replacement',async()=>{let listener,cancelled=0;const install={version:'next',addListener:l=>listener=l,removeListener(){},install(){},cancel:()=>cancelled++};const {U}=setup(l=>{l.onUpdateAvailable(null,install);l.onUpdateFinished(null,0)});await U.start({id:'x'});const c=clock(U);await U.check();const pending=U.apply();U.stop();await pending;listener.onInstallEnded();assert.equal(cancelled,0);assert.equal(c.timers.size,0);assert.equal(U.install,null);});
test('changing plugin policy clears stale status without changing the host global switch',async()=>{const {U,manager}=setup(l=>l.onUpdateFinished(null,0));manager.updateEnabled=false;await U.start({id:'x'});await U.check();await U.setAutomatic(false);assert.equal(U.phase,'idle');assert.equal(U.automatic,false);await U.setAutomatic(true);assert.equal(U.automatic,true);assert.equal(U.globallyEnabled,false);assert.equal(manager.updateEnabled,false);U.stop();});
