using System;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Net.Http;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using System.Drawing;
using System.Windows.Forms;
using System.Web.Script.Serialization;

internal static class Setup {
 internal static JavaScriptSerializer JSON=new JavaScriptSerializer { MaxJsonLength=4000000 };
 internal static Dictionary<string,object> Config=Parse(ReadResource("installer.json"));
 internal static List<Dictionary<string,object>> Models=Rows(Config["models"]);
 internal static string Version=(string)Config["version"];
 internal static string Arg(string key) { var a=Environment.GetCommandLineArgs();var i=Array.IndexOf(a,key);return i>=0&&i+1<a.Length?a[i+1]:null; }
 internal static bool Flag(string key) {return Environment.GetCommandLineArgs().Contains(key);}
 internal static Dictionary<string,object> Parse(string text){return JSON.Deserialize<Dictionary<string,object>>(text);}
 internal static List<Dictionary<string,object>> Rows(object value){return ((IEnumerable)value).Cast<object>().Select(v=>(Dictionary<string,object>)v).ToList();}
 internal static string ReadResource(string name){using(var r=new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream(name)))return r.ReadToEnd();}
 internal static string Hash(string file){using(var s=File.OpenRead(file))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
 internal static bool Valid(string path,Dictionary<string,object> info){return File.Exists(path)&&new FileInfo(path).Length==Convert.ToInt64(info["bytes"])&&Hash(path)==(string)info["sha256"];}
 internal static string Canonical(object value){var d=value as Dictionary<string,object>;if(d!=null)return "{"+string.Join(",",d.OrderBy(p=>p.Key,StringComparer.Ordinal).Select(p=>JSON.Serialize(p.Key)+":"+Canonical(p.Value)))+"}";var a=value as IList;if(a!=null)return "["+string.Join(",",a.Cast<object>().Select(Canonical))+"]";return JSON.Serialize(value);}
 internal static string DefaultData(){var selected=ZoteroInstall.Preferred(ZoteroInstall.Profiles());if(selected!=null)return selected.Data;string fallback=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Zotero"),profiles=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Zotero","Zotero","Profiles");try{if(Directory.Exists(profiles))foreach(var folder in Directory.GetDirectories(profiles).OrderBy(x=>x)){var prefs=Path.Combine(folder,"prefs.js");if(!File.Exists(prefs))continue;var m=Regex.Match(File.ReadAllText(prefs),"user_pref\\(\"extensions\\.zotero\\.dataDir\",\\s*(\"(?:\\\\.|[^\"\\\\])*\")");if(m.Success){var dir=JSON.Deserialize<string>(m.Groups[1].Value);if(File.Exists(Path.Combine(dir,"zotero.sqlite")))return dir;}}}catch(IOException){}return fallback;}
 internal static string ModelRoot(string data){try{var path=Path.Combine(data,"paper-nexus-model-location.json");if(File.Exists(path)&&new FileInfo(path).Length<16384){var record=Parse(File.ReadAllText(path));var root=(string)record["root"];if(Convert.ToInt32(record["schema"])==1&&Path.IsPathRooted(root))return root;}}catch(Exception){}return Path.Combine(data,"paper-nexus-models");}
 internal static void AtomicWrite(string path,string content){var temp=path+".tmp-"+Guid.NewGuid().ToString("N");File.WriteAllText(temp,content,new UTF8Encoding(false));try{if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}finally{if(File.Exists(temp))File.Delete(temp);}}
 [System.Runtime.InteropServices.DllImport("user32.dll")] internal static extern IntPtr SendMessage(IntPtr hWnd,uint message,IntPtr wParam,IntPtr lParam);
 [System.Runtime.InteropServices.DllImport("shell32.dll")] static extern int SHGetKnownFolderPath([System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStruct)] Guid id,uint flags,IntPtr token,out IntPtr path);
 internal static string PluginDownloads(){IntPtr path=IntPtr.Zero;try{if(SHGetKnownFolderPath(new Guid("374DE290-123F-4565-9164-39C4925E467B"),0,IntPtr.Zero,out path)==0)return Path.Combine(System.Runtime.InteropServices.Marshal.PtrToStringUni(path),"Paper Nexus");}finally{if(path!=IntPtr.Zero)System.Runtime.InteropServices.Marshal.FreeCoTaskMem(path);}return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads","Paper Nexus");}
 [STAThread] static int Main(){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;try{if(Flag("--zotero-probe")){if(Arg("--profiles-ini")==null)throw new Exception("Explicit profiles.ini required");var rows=ZoteroInstall.Profiles(Arg("--profiles-ini"));if(Arg("--stage-profile")!=null){var profile=rows.First(p=>Path.GetFullPath(p.Directory)==Path.GetFullPath(Arg("--stage-profile")));ZoteroInstall.Stage(Arg("--plugin-file"),profile);}var value=JSON.Serialize(new Dictionary<string,object>{{"running",ZoteroInstall.Running()},{"profiles",rows.Select(p=>new Dictionary<string,object>{{"name",p.Name},{"path",p.Directory},{"preferred",p.Preferred},{"installed",ZoteroInstall.Installed(p)},{"data",p.Data}}).ToArray()}});if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),value);else Console.WriteLine(value);return 0;}if(Flag("--quiet")){if(Flag("--plugin-only")){if(Arg("--download-dir")==null)throw new Exception("Download directory required");using(var engine=new Engine()){if(Flag("--cancel-test"))engine.Progress=(phase,p)=>{if(p>0)engine.Cancel();};var file=engine.DownloadPlugin(Arg("--download-dir")).GetAwaiter().GetResult();if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),file);return 0;}}var ids=(Arg("--model")??"minilm").Split(',');var chosen=ids.Select(id=>Models.First(m=>(string)m["id"]==id)).ToList();if(Arg("--data-dir")==null||Arg("--download-dir")==null)throw new Exception("Explicit data and download directories required");using(var engine=new Engine()){if(Flag("--cancel-test"))engine.Progress=(phase,p)=>{if(phase=="model"&&p>0.08)engine.Cancel();};string file=null;foreach(var model in chosen)file=engine.Install(model,Arg("--data-dir"),Arg("--download-dir"),Arg("--model-dir")).GetAwaiter().GetResult();if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),file);return 0;}}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new Installer());return 0;}catch(Exception e){if(Arg("--selection-check")!=null)File.WriteAllText(Arg("--selection-check"),e.ToString());if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),e.Message);return 1;}}
}
internal sealed class ZoteroProfile {
 internal string Name,Directory;internal bool Preferred;
 internal string Data {get{var fallback=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Zotero");try{var text=File.ReadAllText(Path.Combine(Directory,"prefs.js"));if(text.Contains("user_pref(\"extensions.zotero.useDataDir\", false)"))return fallback;var m=Regex.Match(text,"user_pref\\(\"extensions\\.zotero\\.dataDir\",\\s*(\"(?:\\\\.|[^\"\\\\])*\")");if(m.Success){var value=Setup.JSON.Deserialize<string>(m.Groups[1].Value);if(Path.IsPathRooted(value))return value;}}catch(IOException){}return fallback;}}
 public override string ToString(){return Name+" — "+Path.GetFileName(Directory);}
}
internal static class ZoteroInstall {
 internal const string ID="cite-lens@local.research";
 internal static List<ZoteroProfile> Profiles(string ini=null){ini=ini??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Zotero","Zotero","profiles.ini");var rows=new List<ZoteroProfile>();if(!File.Exists(ini))return rows;var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);string section="";var fields=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);Action append=()=>{string path,name,relative,pref;if(!section.StartsWith("Profile",StringComparison.OrdinalIgnoreCase)||!fields.TryGetValue("Path",out path)||string.IsNullOrWhiteSpace(path))return;fields.TryGetValue("IsRelative",out relative);if(relative=="0"&&!Path.IsPathRooted(path))return;try{var dir=Path.GetFullPath(relative=="0"?path:Path.Combine(Path.GetDirectoryName(ini),path));if(!Directory.Exists(dir)||!File.Exists(Path.Combine(dir,"prefs.js"))||!seen.Add(dir))return;fields.TryGetValue("Name",out name);fields.TryGetValue("Default",out pref);rows.Add(new ZoteroProfile{Name=name??Path.GetFileName(dir),Directory=dir,Preferred=pref=="1"});}catch(ArgumentException){}catch(NotSupportedException){}};
  try{foreach(var raw in File.ReadAllLines(ini)){var line=raw.Trim().TrimStart('\uFEFF');if(line.StartsWith(";")||line.StartsWith("#"))continue;if(line.StartsWith("[")&&line.EndsWith("]")){append();section=line.Substring(1,line.Length-2);fields.Clear();}else{int equal=line.IndexOf('=');if(equal>0)fields[line.Substring(0,equal).Trim()]=line.Substring(equal+1).Trim();}}append();}catch(IOException){}catch(UnauthorizedAccessException){}return rows;
 }
 internal static ZoteroProfile Preferred(List<ZoteroProfile> rows){if(rows.Count==1)return rows[0];var defaults=rows.Where(p=>p.Preferred).ToList();return defaults.Count==1?defaults[0]:null;}
 internal static string Application(){
  foreach(var p in System.Diagnostics.Process.GetProcessesByName("zotero"))using(p){try{var path=p.MainModule.FileName;if(File.Exists(path))return path;}catch(Exception){}}
  foreach(var hive in new[]{Microsoft.Win32.Registry.CurrentUser,Microsoft.Win32.Registry.LocalMachine}){
   foreach(var key in new[]{@"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\zotero.exe",@"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\zotero.exe"})try{using(var entry=hive.OpenSubKey(key)){var value=entry==null?null:entry.GetValue(null) as string;if(value!=null&&File.Exists(value.Trim('"')))return value.Trim('"');}}catch(System.Security.SecurityException){}
   foreach(var prefix in new[]{@"SOFTWARE\Zotero",@"SOFTWARE\WOW6432Node\Zotero"})try{using(var entry=hive.OpenSubKey(prefix)){var version=entry==null?null:entry.GetValue("CurrentVersion") as string;if(version!=null)using(var main=hive.OpenSubKey(prefix+"\\"+version+@"\Main")){var path=main==null?null:main.GetValue("PathToExe") as string;if(path!=null&&File.Exists(path))return path;}}}catch(System.Security.SecurityException){}
  }
  foreach(var basePath in new[]{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs")}){var path=Path.Combine(basePath,"Zotero","zotero.exe");if(File.Exists(path))return path;}return null;
 }
 internal static bool Running(){foreach(var name in new[]{"zotero","zotero-bin"}){var processes=System.Diagnostics.Process.GetProcessesByName(name);bool any=processes.Length>0;foreach(var p in processes)p.Dispose();if(any)return true;}return false;}
 internal static bool Installed(ZoteroProfile profile){try{string target=Path.Combine(profile.Directory,"extensions",ID+".xpi"),registry=Path.Combine(profile.Directory,"extensions.json");if(!Setup.Valid(target,(Dictionary<string,object>)Setup.Config["plugin"])||!File.Exists(registry)||new FileInfo(registry).Length>32*1024*1024||File.GetLastWriteTimeUtc(registry)<File.GetLastWriteTimeUtc(target))return false;var record=new JavaScriptSerializer{MaxJsonLength=32*1024*1024}.Deserialize<Dictionary<string,object>>(File.ReadAllText(registry));foreach(var addon in Setup.Rows(record["addons"])){object id,version,active,disabled,blocked;if(addon.TryGetValue("id",out id)&&(string)id==ID&&addon.TryGetValue("version",out version)&&(string)version==Setup.Version&&addon.TryGetValue("active",out active)&&active is bool&&(bool)active&&(!addon.TryGetValue("userDisabled",out disabled)||!(disabled is bool)||!(bool)disabled)&&(!addon.TryGetValue("appDisabled",out blocked)||!(blocked is bool)||!(bool)blocked))return true;}}catch(Exception){}return false;}
 internal static void RefreshStartupCache(ZoteroProfile profile){var cache=Path.Combine(profile.Directory,"addonStartup.json.lz4");if(File.Exists(cache)){File.Copy(cache,Path.Combine(profile.Directory,".paper-nexus-startup.previous"),true);File.Delete(cache);}}
 internal static void Stage(string file,ZoteroProfile profile){var plugin=(Dictionary<string,object>)Setup.Config["plugin"];if(!Directory.Exists(profile.Directory)||!File.Exists(Path.Combine(profile.Directory,"prefs.js"))||!Setup.Valid(file,plugin))throw new Exception("插件或 Zotero 配置校验失败 / Plugin or profile verification failed");if(Installed(profile))return;if(Running())throw new Exception("请正常退出 Zotero 后继续 / Quit Zotero normally, then continue");using(var mutex=new FileStream(Path.Combine(profile.Directory,".paper-nexus-installer.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None))using(var profileLock=new FileStream(Path.Combine(profile.Directory,"parent.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){
  var folder=Path.Combine(profile.Directory,"extensions");Directory.CreateDirectory(folder);var target=Path.Combine(folder,ID+".xpi");if(Setup.Valid(target,plugin)){RefreshStartupCache(profile);return;}string temp=Path.Combine(folder,".nexus-"+Guid.NewGuid().ToString("N")),backup=Path.Combine(folder,".nexus-previous");bool hadPrevious=File.Exists(target);try{File.Copy(file,temp);File.SetLastWriteTimeUtc(temp,DateTime.UtcNow);if(!Setup.Valid(temp,plugin)||Running())throw new Exception("请退出 Zotero 后重试 / Quit Zotero and retry");if(hadPrevious){if(File.Exists(backup))File.Delete(backup);File.Replace(temp,target,backup);}else File.Move(temp,target);if(!Setup.Valid(target,plugin)){if(hadPrevious&&File.Exists(backup))File.Copy(backup,target,true);throw new Exception("安装校验失败 / Installation verification failed");}}finally{if(File.Exists(temp))File.Delete(temp);}
  RefreshStartupCache(profile);
 }}
}

internal sealed class Engine:IDisposable {
 readonly CancellationTokenSource stop=new CancellationTokenSource();internal Action<string,double> Progress;internal bool Cancelled {get{return stop.IsCancellationRequested;}}internal void Cancel(){stop.Cancel();}public void Dispose(){stop.Dispose();}
 void Check(){stop.Token.ThrowIfCancellationRequested();}
 void Report(string phase,double p){Check();if(Progress!=null)Progress(phase,p);}
 void Verify(string folder,Dictionary<string,object> manifest){foreach(var f in Setup.Rows(manifest["files"])){Check();string name=(string)f["name"];if(Path.GetFileName(name)!=name||!Setup.Valid(Path.Combine(folder,name),f))throw new Exception("模型校验失败 / Model verification failed");}}
 async Task Fetch(Dictionary<string,object> asset,string target,string phase="model"){Check();var uri=new Uri((string)asset["url"]);if(uri.Scheme!="https")throw new Exception("HTTPS required");long expected=Convert.ToInt64(asset["bytes"]);var offline=(phase=="plugin"?Setup.Arg("--plugin-dir"):null)??Setup.Arg("--package-dir");if(offline!=null){File.Copy(Path.Combine(offline,(string)asset["name"]),target);Report(phase,phase=="plugin"?1:0.88);}else{
  using(var handler=new HttpClientHandler {AllowAutoRedirect=false})using(var client=new HttpClient(handler)){client.Timeout=TimeSpan.FromMinutes(15);HttpResponseMessage response=null;try{for(int i=0;i<8;i++){response=await client.GetAsync(uri,HttpCompletionOption.ResponseHeadersRead,stop.Token);if((int)response.StatusCode<300||(int)response.StatusCode>=400)break;var next=response.Headers.Location;if(next==null)throw new Exception("Missing redirect");uri=next.IsAbsoluteUri?next:new Uri(uri,next);response.Dispose();response=null;if(uri.Scheme!="https")throw new Exception("HTTPS required");}if(response==null||response.StatusCode!=HttpStatusCode.OK)throw new Exception("下载暂不可用 / Download unavailable");using(var input=await response.Content.ReadAsStreamAsync())using(var output=File.Create(target)){byte[] buffer=new byte[65536];long total=0;int count;while((count=await input.ReadAsync(buffer,0,buffer.Length,stop.Token))>0){total+=count;if(total>expected)throw new Exception("Unexpected file size");await output.WriteAsync(buffer,0,count,stop.Token);Report(phase,phase=="plugin"?(double)total/expected:0.08+0.80*total/expected);}}}finally{if(response!=null)response.Dispose();}}}
  Check();if(!Setup.Valid(target,asset))throw new Exception("文件校验失败，请重试 / File verification failed");
 }
 internal async Task<string> DownloadPlugin(string downloads){Directory.CreateDirectory(downloads);var plugin=(Dictionary<string,object>)Setup.Config["plugin"];var xpi=Path.Combine(downloads,(string)plugin["name"]);if(!Setup.Valid(xpi,plugin)){Report("plugin",0);var temp=Path.Combine(downloads,".plugin-"+Guid.NewGuid().ToString("N"));try{await Fetch(plugin,temp,"plugin");Check();if(File.Exists(xpi))File.Replace(temp,xpi,null);else File.Move(temp,xpi);}finally{if(File.Exists(temp))File.Delete(temp);}}Check();Report("plugin",1);return xpi;}
 internal async Task<string> Install(Dictionary<string,object> model,string data,string downloads,string modelDirectory=null){if(!File.Exists(Path.Combine(data,"zotero.sqlite")))throw new Exception("请选择包含 zotero.sqlite 的 Zotero 数据目录 / Choose the Zotero data folder containing zotero.sqlite");var root=modelDirectory??Setup.ModelRoot(data);if(root==Path.Combine(data,"paper-nexus-models"))Directory.CreateDirectory(root);if(!Directory.Exists(root))throw new Exception("模型目录不可用，请重新选择 / Model folder unavailable; choose an existing folder");using(var mutex=new FileStream(Path.Combine(root,".installer.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){var work=Path.Combine(root,".setup-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(work);try{
  var manifest=(Dictionary<string,object>)model["manifest"];var parent=Path.Combine(root,(string)model["id"]);var target=Path.Combine(parent,(string)manifest["version"]);var xpi=await DownloadPlugin(downloads);
  bool usable=false;if(Directory.Exists(target)){Report("verify",0.08);try{Verify(target,manifest);usable=true;}catch(IOException){}catch(Exception){Check();}}
  if(!usable){var asset=(Dictionary<string,object>)model["package"];var archive=Path.Combine(downloads,(string)asset["name"]);if(!Setup.Valid(archive,asset)){var partial=Path.Combine(downloads,".model-"+Guid.NewGuid().ToString("N"));try{await Fetch(asset,partial);if(File.Exists(archive))File.Replace(partial,archive,null);else File.Move(partial,archive);}finally{if(File.Exists(partial))File.Delete(partial);}}Report("verify",0.89);var extracted=Path.Combine(work,"verified");Directory.CreateDirectory(extracted);var files=Setup.Rows(manifest["files"]);var expected=new HashSet<string>(files.Select(f=>(string)f["name"]),StringComparer.Ordinal){"manifest.json"};var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
   using(var zip=ZipFile.OpenRead(archive)){foreach(var entry in zip.Entries){Check();if(!expected.Contains(entry.FullName)||!seen.Add(entry.FullName)||Path.GetFileName(entry.FullName)!=entry.FullName)throw new Exception("Unexpected model archive entry");long limit=entry.FullName=="manifest.json"?4000000:Convert.ToInt64(files.First(f=>(string)f["name"]==entry.FullName)["bytes"]);if(entry.Length>limit)throw new Exception("Unexpected model file size");entry.ExtractToFile(Path.Combine(extracted,entry.FullName));}if(seen.Count!=expected.Count)throw new Exception("Incomplete model package");}
   var actualIdentity=Setup.Parse(File.ReadAllText(Path.Combine(extracted,"manifest.json")));var expectedIdentity=new Dictionary<string,object>(manifest);actualIdentity.Remove("name");expectedIdentity.Remove("name");if(Setup.Canonical(actualIdentity)!=Setup.Canonical(expectedIdentity))throw new Exception("Model manifest mismatch");Verify(extracted,manifest);Report("install",0.97);Directory.CreateDirectory(parent);var backup=Path.Combine(work,"previous");if(Directory.Exists(target))Directory.Move(target,backup);try{Directory.Move(extracted,target);}catch{if(Directory.Exists(backup))Directory.Move(backup,target);throw;}}
  string pointer=Path.Combine(parent,"active.json"),staged=Path.Combine(parent,".active-"+Guid.NewGuid().ToString("N"));File.WriteAllText(staged,Setup.JSON.Serialize(manifest),new UTF8Encoding(false));try{if(File.Exists(pointer))File.Replace(staged,pointer,null);else File.Move(staged,pointer);}finally{if(File.Exists(staged))File.Delete(staged);}Setup.AtomicWrite(Path.Combine(data,"paper-nexus-model-location.json"),Setup.JSON.Serialize(new Dictionary<string,object>{{"schema",1},{"root",Path.GetFullPath(root)}}));if(Progress!=null)Progress("done",1);return xpi;
 }finally{if(Directory.Exists(work))Directory.Delete(work,true);}}}
}
internal static class Visual {
 internal static Color ColorFor(string name){return ColorTranslator.FromHtml((string)((Dictionary<string,object>)Setup.Config["appearance"])[name]);}
 internal static readonly Color Ink=ColorFor("ink"),Muted=ColorFor("muted"),Green=ColorFor("success"),Paper=ColorFor("paper"),Accent=ColorFor("accent"),Card=ColorFor("card"),Button=ColorFor("button");
 static readonly System.Drawing.Text.PrivateFontCollection Fonts=new System.Drawing.Text.PrivateFontCollection();
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern IntPtr AddFontMemResourceEx(IntPtr p,uint size,IntPtr reserved,ref uint count);
 static Visual(){foreach(var name in new[]{"NexusSans-Regular.ttf","NexusSans-SemiBold.ttf"})using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(name)){var bytes=new byte[s.Length];s.Read(bytes,0,bytes.Length);var p=System.Runtime.InteropServices.Marshal.AllocHGlobal(bytes.Length);System.Runtime.InteropServices.Marshal.Copy(bytes,0,p,bytes.Length);Fonts.AddMemoryFont(p,bytes.Length);uint count=0;AddFontMemResourceEx(p,(uint)bytes.Length,IntPtr.Zero,ref count);}}
 internal static FontFamily Face(bool bold){var name=bold?"Nexus Sans SemiBold":"Nexus Sans Regular";var family=Fonts.Families.FirstOrDefault(f=>f.Name==name || (bold && f.Name.StartsWith(name+" ",StringComparison.Ordinal)));if(family==null)throw new Exception("Bundled font unavailable: "+name+"; found "+string.Join(", ",Fonts.Families.Select(f=>f.Name)));return family;}
 internal static Font Font(float size,FontStyle weight=FontStyle.Regular){return new Font(Face((weight&FontStyle.Bold)!=0),size*.75f,FontStyle.Regular,GraphicsUnit.Point);}
 internal static Font Resolve(Font font){return new Font(Face(font.FontFamily.Name.Contains("SemiBold")),font.SizeInPoints,FontStyle.Regular,GraphicsUnit.Point);}
 internal static void DrawText(Graphics g,string text,Font font,Rectangle bounds,Color color,bool center=false,bool path=false){g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;using(var face=Resolve(font))using(var brush=new SolidBrush(color))using(var format=new StringFormat {Alignment=center?StringAlignment.Center:StringAlignment.Near,LineAlignment=StringAlignment.Center,Trimming=path?StringTrimming.EllipsisPath:StringTrimming.EllipsisCharacter,FormatFlags=StringFormatFlags.NoWrap})g.DrawString(text,face,brush,bounds,format);}
 internal static System.Drawing.Drawing2D.GraphicsPath Round(RectangleF r,float radius){var p=new System.Drawing.Drawing2D.GraphicsPath();float d=radius*2;p.AddArc(r.X,r.Y,d,d,180,90);p.AddArc(r.Right-d,r.Y,d,d,270,90);p.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);p.AddArc(r.X,r.Bottom-d,d,d,90,90);p.CloseFigure();return p;}
}
internal sealed class NexusLabel:Label {
 internal NexusLabel(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}
 protected override void OnPaint(PaintEventArgs e){e.Graphics.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;using(var face=Visual.Resolve(Font))using(var brush=new SolidBrush(ForeColor))using(var format=new StringFormat {Trimming=StringTrimming.EllipsisCharacter})e.Graphics.DrawString(Text,face,brush,ClientRectangle,format);}
}
internal sealed class Card:Panel {protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Visual.Paper);e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=Visual.Round(new RectangleF(0,0,Width,Height),12))using(var b=new SolidBrush(Visual.Card))e.Graphics.FillPath(b,p);}internal Card(){BackColor=Visual.Card;Resize+=(s,e)=>{if(Width>0&&Height>0){using(var p=Visual.Round(new RectangleF(0,0,Width,Height),12)){var old=Region;Region=new Region(p);if(old!=null)old.Dispose();}}};}}
internal class QuietButton:Button {bool hover;internal bool Chevron;internal QuietButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;MouseEnter+=(s,e)=>{hover=true;Invalidate();};MouseLeave+=(s,e)=>{hover=false;Invalidate();};}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;var bg=Enabled?(hover?(BackColor==Visual.Accent?Visual.ColorFor("accentHover"):Visual.ColorFor("buttonHover")):BackColor):Visual.ColorFor("disabled");using(var p=Visual.Round(new RectangleF(0,0,Width-1,Height-1),8))using(var brush=new SolidBrush(bg))e.Graphics.FillPath(brush,p);Visual.DrawText(e.Graphics,Text,Font,new Rectangle(4,0,Width-(Chevron?24:8),Height),Enabled?ForeColor:Visual.ColorFor("disabledInk"),true);if(Chevron)using(var pen=new Pen(Enabled?ForeColor:Visual.ColorFor("disabledInk"),1.4f)){float x=Width-14,y=Height/2f;e.Graphics.DrawLines(pen,new[]{new PointF(x-3,y-2),new PointF(x,y+1),new PointF(x+3,y-2)});}}}
internal sealed class LanguageChoice:QuietButton {
 int selected;internal event EventHandler SelectedIndexChanged;
 internal int SelectedIndex {get{return selected;}set{selected=value;Text=value==0?"简体中文":"English";if(SelectedIndexChanged!=null)SelectedIndexChanged(this,EventArgs.Empty);Invalidate();}}
 internal LanguageChoice(){Chevron=true;BackColor=Visual.Button;ForeColor=Visual.Ink;Cursor=Cursors.Hand;Click+=(s,e)=>{var menu=new ContextMenuStrip {Font=Font,BackColor=Visual.Card,ForeColor=Visual.Ink,ShowImageMargin=false};foreach(var label in new[]{"简体中文","English"}){int index=menu.Items.Count;var item=new ToolStripMenuItem(label){Checked=index==selected};item.Click+=(a,b)=>SelectedIndex=index;menu.Items.Add(item);}menu.Closed+=(a,b)=>menu.Dispose();menu.Show(this,new Point(0,Height));};}
}
internal sealed class ModelCheck:CheckBox {internal ModelCheck(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);Cursor=Cursors.Hand;}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;float size=16*DeviceDpi/96f,y=(Height-size)/2;using(var p=Visual.Round(new RectangleF(0,y,size,size),5))using(var b=new SolidBrush(Checked?Visual.ColorFor("selected"):Visual.ColorFor("unchecked")))e.Graphics.FillPath(b,p);if(Checked)using(var pen=new Pen(Color.White,2.2f)){e.Graphics.DrawLines(pen,new[]{new PointF(size*.24f,y+size*.51f),new PointF(size*.43f,y+size*.71f),new PointF(size*.78f,y+size*.29f)});}Visual.DrawText(e.Graphics,Text,Font,new Rectangle((int)size+10,0,Width-(int)size-10,Height),Visual.Ink);}}
internal sealed class Track:Control {double value;internal Color Tint=Visual.Accent;internal double Value{get{return value;}set{this.value=Math.Max(0,Math.Min(1,value));Invalidate();}}internal Track(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=Visual.Round(new RectangleF(0,0,Width,Height),Height/2f))using(var b=new SolidBrush(Visual.ColorFor("track")))e.Graphics.FillPath(b,p);if(value>0)using(var p=Visual.Round(new RectangleF(0,0,Math.Max(Height,(float)(Width*value)),Height),Height/2f))using(var b=new SolidBrush(Tint))e.Graphics.FillPath(b,p);}}
internal sealed class PathDisplay:Control {internal PathDisplay(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}protected override void OnPaint(PaintEventArgs e){Visual.DrawText(e.Graphics,Text,Font,ClientRectangle,Visual.Muted,false,true);}}
internal sealed class Installer:Form {
 bool zh=(Setup.Arg("--lang")??System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName)=="zh",busy,complete;string data=Setup.DefaultData(),modelDirectory=Setup.ModelRoot(Setup.DefaultData()),xpi;Engine engine;Label heading,intro,status,targetLabel,pluginLabel;Button pluginButton;Track pluginBar;PathDisplay pathLabel;Button folder,action,cancel,help;LanguageChoice language;DateTime downloadBegan;List<Track> modelBars=new List<Track>();HashSet<int> completed=new HashSet<int>();List<CheckBox> options=new List<CheckBox>();List<Label> details=new List<Label>();
 string T(string cn,string en){return zh?cn:en;}
 Label LabelAt(string text,float size,FontStyle style,int x,int y,int w,int h){var l=new NexusLabel {Text=text,Font=Visual.Font(size,style),Location=new Point(x,y),Size=new Size(w,h),ForeColor=Visual.Ink};Controls.Add(l);return l;}
 Button ButtonAt(int x,int y,int w,string text,EventHandler handler){var b=new QuietButton {Text=text,Location=new Point(x,y),Size=new Size(w,28),FlatStyle=FlatStyle.Flat,BackColor=Visual.Button,ForeColor=Visual.Ink,Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=0;b.Click+=handler;Controls.Add(b);return b;}
 void SelectionCheck(){var checks=new Dictionary<string,bool>();using(var face=Visual.Resolve(heading.Font)){checks["private-font-after-dpi-layout"]=face.FontFamily.Name.StartsWith("Nexus Sans SemiBold",StringComparison.Ordinal);Console.WriteLine("Font after layout: "+heading.Font.FontFamily.Name+" -> "+face.FontFamily.Name);}checks["footer-actions-aligned"]=pluginButton.Top+pluginButton.Height/2==action.Top+action.Height/2&&pluginButton.Right<action.Left;checks["cancel-replaces-secondary"]=cancel.Bounds==pluginButton.Bounds;Busy(true);checks["busy-shows-only-cancel"]=!pluginButton.Visible&&cancel.Visible;Busy(false);checks["idle-restores-plugin-only"]=pluginButton.Visible&&!cancel.Visible;checks["default-single"]=options[0].Checked&&!options[1].Checked;Setup.SendMessage(options[0].Handle,0x00F5,IntPtr.Zero,IntPtr.Zero);checks["empty-disabled"]=!options.Any(o=>o.Checked)&&!action.Enabled;Setup.SendMessage(options[1].Handle,0x00F5,IntPtr.Zero,IntPtr.Zero);checks["second-only"]=!options[0].Checked&&options[1].Checked;RefreshText();checks["refresh-preserves"]=!options[0].Checked&&options[1].Checked;Setup.SendMessage(options[0].Handle,0x00F5,IntPtr.Zero,IntPtr.Zero);checks["both"]=options.All(o=>o.Checked);Setup.SendMessage(options[1].Handle,0x00F5,IntPtr.Zero,IntPtr.Zero);checks["first-only"]=options[0].Checked&&!options[1].Checked;checks["visible-downloads"]=Path.GetFileName(Setup.PluginDownloads())=="Paper Nexus"&&!Setup.PluginDownloads().Contains("AppData");File.WriteAllText(Setup.Arg("--selection-check"),Setup.JSON.Serialize(checks));Close();}
 internal Installer(){if(Setup.Arg("--selection-check")!=null)Shown+=(s,e)=>BeginInvoke(new Action(SelectionCheck));AutoScaleMode=AutoScaleMode.Dpi;ClientSize=new Size(620,456);MinimumSize=MaximumSize=Size;FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;BackColor=Visual.Paper;StartPosition=FormStartPosition.CenterScreen;Font=Visual.Font(13);LabelAt("PAPER NEXUS  /  FOR ZOTERO",11,FontStyle.Bold,32,21,430,20).ForeColor=Visual.Accent;
  using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("nexus.png")){var image=new Bitmap(s);Controls.Add(new PictureBox {Image=new Bitmap(image),Location=new Point(523,30),Size=new Size(64,64),SizeMode=PictureBoxSizeMode.Zoom});}
  heading=LabelAt("",27,FontStyle.Bold,32,50,478,40);heading.ForeColor=Visual.Accent;intro=LabelAt("",13,FontStyle.Regular,32,102,556,24);intro.ForeColor=Visual.Muted;
  pluginLabel=LabelAt("",13,FontStyle.Bold,34,144,365,24);pluginLabel.ForeColor=Visual.Accent;pluginButton=ButtonAt(268,400,122,"",DownloadPlugin);pluginButton.Height=36;pluginBar=new Track {Location=new Point(34,174),Size=new Size(554,3),Visible=false};Controls.Add(pluginBar);
  for(int i=0;i<Setup.Models.Count;i++){int at=i,y=180+i*72;var panel=new Card {Location=new Point(30,y),Size=new Size(560,64),BackColor=Visual.Card};Controls.Add(panel);var radio=new ModelCheck {Location=new Point(16,5),Size=new Size(520,25),Font=Visual.Font(15,FontStyle.Bold)};panel.Controls.Add(radio);radio.Click+=(s,e)=>{complete=false;completed.Clear();foreach(var bar in modelBars)bar.Visible=false;RefreshText();};options.Add(radio);var detail=new NexusLabel {Location=new Point(39,33),Size=new Size(493,19),ForeColor=Visual.Muted,Font=Visual.Font(12)};panel.Controls.Add(detail);details.Add(detail);var progress=new Track {Location=new Point(39,56),Size=new Size(493,3),Visible=false};panel.Controls.Add(progress);modelBars.Add(progress);}options[0].Checked=true;
  targetLabel=LabelAt("",12,FontStyle.Bold,34,327,100,22);pathLabel=new PathDisplay {Location=new Point(126,327),Size=new Size(350,22),Font=Visual.Font(12)};Controls.Add(pathLabel);folder=ButtonAt(480,324,108,"",(s,e)=>{using(var dialog=new FolderBrowserDialog {SelectedPath=Directory.Exists(modelDirectory)?modelDirectory:data})if(dialog.ShowDialog()==DialogResult.OK){modelDirectory=dialog.SelectedPath;customModelDirectory=true;complete=false;RefreshText();}});status=LabelAt("",12,FontStyle.Regular,34,360,554,37);status.ForeColor=Visual.Muted;help=ButtonAt(28,404,88,"",(s,e)=>System.Diagnostics.Process.Start("https://github.com/JunyanKang/paper-nexus/blob/main/docs/INSTALL.md"));help.BackColor=Visual.ColorFor("quiet");language=new LanguageChoice {Location=new Point(126,404),Size=new Size(112,28)};language.SelectedIndex=zh?0:1;language.SelectedIndexChanged+=(s,e)=>{zh=language.SelectedIndex==0;RefreshText();};Controls.Add(language);cancel=ButtonAt(268,400,122,"",(s,e)=>{if(engine!=null)engine.Cancel();cancel.Enabled=false;status.Text=T("正在取消…","Cancelling…");});cancel.Height=36;cancel.Visible=false;action=ButtonAt(402,400,187,"",Start);action.Height=36;action.BackColor=Visual.Accent;action.ForeColor=Color.White;RefreshText();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};Shown+=(s,e)=>{var path=Setup.Arg("--screenshot");if(Setup.Flag("--progress-preview")){foreach(var option in options){option.Checked=true;option.Enabled=false;}action.Enabled=folder.Enabled=language.Enabled=false;pluginButton.Visible=false;cancel.Visible=true;UpdateCard(0,"done",1);if(Setup.Models.Count>1){downloadBegan=DateTime.UtcNow.AddSeconds(-2);UpdateCard(1,"model",.42);}status.Text=T("1 个模型已安装 · 正在下载下一个","1 model installed · Downloading the next");}if(new[]{"pending","installed","waiting"}.Contains(Setup.Arg("--install-preview"))){xpi=Path.Combine(Setup.PluginDownloads(),"preview.xpi");complete=true;pluginState=Setup.Arg("--install-preview");RefreshPlugin();}if(path!=null){using(var timer=new System.Windows.Forms.Timer {Interval=600}){timer.Tick+=(a,b)=>{timer.Stop();using(var bmp=new Bitmap(Width,Height)){DrawToBitmap(bmp,new Rectangle(0,0,Width,Height));bmp.Save(path);}Close();};timer.Start();while(!IsDisposed&&Visible)Application.DoEvents();}}};
 }
 ZoteroProfile zoteroProfile;bool profileResolved,customModelDirectory,polling;string pluginState="downloaded";
 bool ResolveProfile(){if(profileResolved)return true;var rows=ZoteroInstall.Profiles();zoteroProfile=ZoteroInstall.Preferred(rows);if(zoteroProfile==null&&rows.Count>0){using(var dialog=new Form{Text=T("选择 Zotero 配置","Choose a Zotero profile"),ClientSize=new Size(460,138),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,BackColor=Visual.Paper,Font=Visual.Font(13)}){
  var label=new NexusLabel{Text=T("插件和模型将用于所选配置。","The plugin and models will use this profile."),Location=new Point(20,14),Size=new Size(420,24),ForeColor=Visual.Ink};var menu=new ComboBox{Location=new Point(20,44),Size=new Size(420,28),DropDownStyle=ComboBoxStyle.DropDownList,BackColor=Visual.Button,ForeColor=Visual.Ink,Font=Visual.Font(13),DrawMode=DrawMode.OwnerDrawFixed,ItemHeight=25};menu.DrawItem+=(s,e)=>{if(e.Index<0)return;using(var brush=new SolidBrush((e.State&DrawItemState.Selected)!=0?Visual.ColorFor("buttonHover"):Visual.Button))e.Graphics.FillRectangle(brush,e.Bounds);Visual.DrawText(e.Graphics,menu.Items[e.Index].ToString(),menu.Font,e.Bounds,Visual.Ink);};foreach(var row in rows)menu.Items.Add(row);menu.SelectedIndex=0;
  var ok=new QuietButton{Text=T("继续","Continue"),Location=new Point(340,94),Size=new Size(100,28),BackColor=Visual.Accent,ForeColor=Color.White,DialogResult=DialogResult.OK};var cancelProfile=new QuietButton{Text=T("取消","Cancel"),Location=new Point(230,94),Size=new Size(100,28),BackColor=Visual.Button,ForeColor=Visual.Ink,DialogResult=DialogResult.Cancel};dialog.Controls.AddRange(new Control[]{label,menu,ok,cancelProfile});dialog.AcceptButton=ok;dialog.CancelButton=cancelProfile;if(dialog.ShowDialog(this)!=DialogResult.OK)return false;zoteroProfile=(ZoteroProfile)menu.SelectedItem;
 }}profileResolved=true;if(zoteroProfile!=null){data=zoteroProfile.Data;if(!customModelDirectory)modelDirectory=Setup.ModelRoot(data);}RefreshText();return true;}
 void RefreshPlugin(){if(xpi==null)return;var labels=new Dictionary<string,string>{{"downloaded",T("已下载","Downloaded")},{"waiting",T("待继续","Paused")},{"pending",T("待启用","Enable in Zotero")},{"installed",T("已安装","Installed")},{"manual",T("已下载","Downloaded")}};pluginLabel.Text="Paper Nexus · v"+Setup.Version+" · "+labels[pluginState];pluginButton.Text=pluginState=="pending"||pluginState=="installed"?T("打开 Zotero","Open Zotero"):pluginState=="manual"?T("打开文件","Show XPI"):T("继续安装","Continue setup");if(complete)action.Text=pluginState=="manual"?T("打开插件文件夹","Show plugin file"):pluginState=="pending"||pluginState=="installed"?T("打开 Zotero","Open Zotero"):T("继续安装","Continue setup");if(pluginState=="pending")status.Text=T("待启用：在 Zotero「工具 → 插件」中启用 Paper Nexus。","Enable Paper Nexus in Zotero → Tools → Plugins.");else if(pluginState=="installed")status.Text=T("插件已安装并启用。","Plugin installed and enabled.");else if(pluginState=="manual")status.Text=T("未识别到 Zotero 或配置。请在 Zotero 中从文件安装已下载的 XPI。","Zotero or its profile was not found. Install the downloaded XPI from file in Zotero.");}
 async Task InstallPlugin(){if(xpi==null)return;if(zoteroProfile==null||ZoteroInstall.Application()==null){pluginState="manual";RefreshPlugin();return;}if(await Task.Run(()=>ZoteroInstall.Installed(zoteroProfile))){pluginState="installed";RefreshPlugin();return;}if(ZoteroInstall.Running()){pluginState="waiting";RefreshPlugin();if(MessageBox.Show(this,T("请正常退出 Zotero，保存正在阅读或编辑的内容，再点击确定继续。","Quit Zotero normally after saving your work, then click OK to continue."),T("请先退出 Zotero","Quit Zotero to continue"),MessageBoxButtons.OKCancel,MessageBoxIcon.Information)==DialogResult.OK){if(!ZoteroInstall.Running())await InstallPlugin();}return;}Busy(true);cancel.Visible=false;status.Text=T("正在安装插件…","Installing plugin…");try{await Task.Run(()=>ZoteroInstall.Stage(xpi,zoteroProfile));Busy(false);pluginState="pending";RefreshPlugin();PollPlugin();}catch(Exception error){Busy(false);pluginState="downloaded";RefreshPlugin();status.Text=error.Message;}}
 async void PollPlugin(){if(pluginState!="pending"||polling||zoteroProfile==null)return;polling=true;try{while(!IsDisposed&&pluginState=="pending"){await Task.Delay(2000);if(IsDisposed)break;bool installed=await Task.Run(()=>ZoteroInstall.Installed(zoteroProfile));if(installed){pluginState="installed";if(!busy)RefreshPlugin();break;}}}finally{polling=false;}}
 void OpenZotero(){var exe=ZoteroInstall.Application();if(exe==null){if(xpi!=null)System.Diagnostics.Process.Start("explorer.exe","/select,\""+xpi+"\"");return;}try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(exe,zoteroProfile==null?"":"-profile \""+zoteroProfile.Directory+"\""){UseShellExecute=true});PollPlugin();}catch(Exception e){status.Text=e.Message;}}

 void UpdateCard(int index,string phase,double value){modelBars[index].Visible=true;modelBars[index].Value=value;if(phase=="model"){var package=(Dictionary<string,object>)Setup.Models[index]["package"];double total=Convert.ToDouble(package["bytes"]),bytes=Math.Max(0,(value-.08)/.8)*total,seconds=Math.Max(.1,(DateTime.UtcNow-downloadBegan).TotalSeconds);details[index].Text=T("下载中","Downloading")+string.Format(" · {0:F1} / {1:F1} MB · {2:F1} MB/s",bytes/1e6,total/1e6,bytes/seconds/1e6);}else{var names=new Dictionary<string,string>{{"plugin",T("下载插件","Downloading plugin")},{"verify",T("校验中","Verifying")},{"install",T("安装中","Installing")},{"done",T("已安装 · 可在插件中切换","Installed · Available in plugin settings")}};details[index].Text=names[phase];}if(phase=="done"){completed.Add(index);details[index].ForeColor=Visual.Green;modelBars[index].Tint=Visual.Green;modelBars[index].Invalidate();}}
 void RefreshText(){Text=T("Paper Nexus 安装助手","Paper Nexus Installer");heading.Text=T("把文献，连成研究线索。","Connect your research.");intro.Text=T("选择至少一个本地模型，可多选。以后仅更新插件。","Choose one or more models. Update the plugin independently.");for(int i=0;i<options.Count;i++){options[i].Text=(string)Setup.Models[i][zh?"titleZh":"titleEn"];details[i].ForeColor=completed.Contains(i)?Visual.Green:Visual.Muted;modelBars[i].Tint=completed.Contains(i)?Visual.Green:Visual.Accent;details[i].Text=completed.Contains(i)?T("已安装 · 可在插件中切换","Installed · Available in plugin settings"):(string)Setup.Models[i][zh?"detailZh":"detailEn"];}action.Enabled=!busy&&options.Any(o=>o.Checked);targetLabel.Text=T("模型位置","Model folder");pathLabel.Text=modelDirectory.Replace(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"%USERPROFILE%");folder.Text=T("选择文件夹","Browse");help.Text=T("安装帮助","Help");cancel.Text=T("取消","Cancel");pluginLabel.Text=T("插件 XPI","Plugin XPI")+" · v"+Setup.Version;pluginButton.Text=xpi==null?T("仅更新插件","Plugin only"):T("打开文件","Show XPI");action.Text=complete?T("打开插件文件夹","Show plugin file"):T("下载插件与模型","Get plugin & models");status.Text=complete?T("模型已就绪。在 Zotero 中从文件安装 XPI，然后在网络设置中选择分析方案。","Model ready. Install the XPI from file in Zotero, then choose an analysis in Network settings."):T("无需账户或管理员权限。文献内容保留在本机。","No account or administrator access. Library content stays local.");RefreshPlugin();}
 void Busy(bool value){busy=value;pluginButton.Enabled=!value;pluginButton.Visible=!value;options.ForEach(o=>o.Enabled=!value);folder.Enabled=language.Enabled=action.Enabled=!value;cancel.Visible=value;cancel.Enabled=true;}
 async void DownloadPlugin(object sender,EventArgs e){if(!ResolveProfile())return;if(xpi!=null&&File.Exists(xpi)){if(pluginState=="pending"||pluginState=="installed")OpenZotero();else if(pluginState=="manual")System.Diagnostics.Process.Start("explorer.exe","/select,\""+xpi+"\"");else await InstallPlugin();return;}engine=new Engine();Busy(true);pluginBar.Visible=true;pluginBar.Value=0;engine.Progress=(phase,p)=>BeginInvoke(new Action(()=>{if(!busy)return;pluginBar.Value=p;status.Text=T("下载插件","Downloading XPI")+" · "+(int)(p*100)+"%";}));try{xpi=await Task.Run(()=>engine.DownloadPlugin(Setup.PluginDownloads()));Busy(false);RefreshText();pluginBar.Tint=Visual.Green;await InstallPlugin();}catch(Exception error){Busy(false);status.Text=engine.Cancelled?T("已取消","Cancelled"):error.Message;}finally{engine.Dispose();engine=null;}}
 async void Start(object sender,EventArgs e){if(busy||!options.Any(o=>o.Checked)||!ResolveProfile())return;if(complete){if(pluginState=="pending"||pluginState=="installed")OpenZotero();else if(pluginState=="manual")System.Diagnostics.Process.Start("explorer.exe","/select,\""+xpi+"\"");else await InstallPlugin();return;}if(!File.Exists(Path.Combine(data,"zotero.sqlite"))){using(var dialog=new FolderBrowserDialog {Description=T("选择 Zotero 数据目录（包含 zotero.sqlite）","Choose the Zotero data folder (contains zotero.sqlite)"),ShowNewFolderButton=false}){if(dialog.ShowDialog()!=DialogResult.OK)return;data=dialog.SelectedPath;if(!File.Exists(Path.Combine(data,"zotero.sqlite")))return;if(!Directory.Exists(modelDirectory))modelDirectory=Setup.ModelRoot(data);}}if(complete){if(pluginState=="pending"||pluginState=="installed")OpenZotero();else if(pluginState=="manual")System.Diagnostics.Process.Start("explorer.exe","/select,\""+xpi+"\"");else await InstallPlugin();return;}completed.Clear();for(int i=0;i<options.Count;i++)if(options[i].Checked){modelBars[i].Value=0;modelBars[i].Visible=true;details[i].ForeColor=Visual.Muted;details[i].Text=T("等待下载","Waiting to download");}Busy(true);status.Text=T("正在准备…","Preparing…");var chosen=Setup.Models.Where((m,i)=>options[i].Checked).ToList();if(chosen.Count==0){Busy(false);return;}int modelIndex=0;engine=new Engine();engine.Progress=(phase,p)=>{int step=modelIndex;BeginInvoke(new Action(()=>{if(!busy)return;if(phase!="plugin"&&step<chosen.Count)UpdateCard(Setup.Models.IndexOf(chosen[step]),phase,p);else if(phase=="plugin"){pluginBar.Visible=true;pluginBar.Value=p;}var names=new Dictionary<string,string>{{"plugin",T("下载插件","Downloading plugin")},{"model",T("下载模型","Downloading model")},{"verify",T("校验模型","Verifying model")},{"install",T("安装模型","Installing model")},{"done",T("完成","Done")}};status.Text=(step+1)+"/"+chosen.Count+" · "+names[phase]+" · "+(int)(p*100)+"%";}));};try{foreach(var model in chosen){downloadBegan=DateTime.UtcNow;xpi=await Task.Run(()=>engine.Install(model,data,Setup.PluginDownloads(),modelDirectory));modelIndex++;}complete=true;Busy(false);RefreshText();await InstallPlugin();}catch(Exception error){Busy(false);status.Text=engine.Cancelled?T("已取消，原有模型保留。","Cancelled. Existing model retained."):T("安装未完成，可重试。","Not completed. You can retry.");if(!engine.Cancelled)MessageBox.Show(this,error.Message,T("安装未完成","Installation not completed"),MessageBoxButtons.OK,MessageBoxIcon.Information);}finally{engine.Dispose();engine=null;}}
}
