using System;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Net.Http;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using System.Drawing;
using System.Windows.Forms;
using System.Web.Script.Serialization;

internal static class Setup {
 internal static JavaScriptSerializer JSON=new JavaScriptSerializer { MaxJsonLength=4000000 };
 internal static Dictionary<string,object> Config=Parse(ReadResource("installer.json"));
 internal static List<Dictionary<string,object>> Models=Rows(Config["models"]);
 internal static string Version=(string)Config["version"];
 internal static string Arg(string key) { var a=Environment.GetCommandLineArgs();var i=Array.IndexOf(a,key);return i>=0&&i+1<a.Length?a[i+1]:null; }
 internal static bool Flag(string key) {return Environment.GetCommandLineArgs().Contains(key);}
 internal static Dictionary<string,object> Parse(string text){return JSON.Deserialize<Dictionary<string,object>>(text);}
 internal static List<Dictionary<string,object>> Rows(object value){return ((IEnumerable)value).Cast<object>().Select(v=>(Dictionary<string,object>)v).ToList();}
 internal static string ReadResource(string name){using(var r=new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream(name)))return r.ReadToEnd();}
 internal static string Hash(string file){using(var s=File.OpenRead(file))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
 internal static bool Valid(string path,Dictionary<string,object> info){return File.Exists(path)&&new FileInfo(path).Length==Convert.ToInt64(info["bytes"])&&Hash(path)==(string)info["sha256"];}
 internal static string Canonical(object value){var d=value as Dictionary<string,object>;if(d!=null)return "{"+string.Join(",",d.OrderBy(p=>p.Key,StringComparer.Ordinal).Select(p=>JSON.Serialize(p.Key)+":"+Canonical(p.Value)))+"}";var a=value as IList;if(a!=null)return "["+string.Join(",",a.Cast<object>().Select(Canonical))+"]";return JSON.Serialize(value);}
 internal static string DefaultData(){string fallback=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Zotero"),profiles=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Zotero","Zotero","Profiles");try{if(Directory.Exists(profiles))foreach(var folder in Directory.GetDirectories(profiles).OrderBy(x=>x)){var prefs=Path.Combine(folder,"prefs.js");if(!File.Exists(prefs))continue;var m=Regex.Match(File.ReadAllText(prefs),"user_pref\\(\"extensions\\.zotero\\.dataDir\",\\s*(\"(?:\\\\.|[^\"\\\\])*\")");if(m.Success){var dir=JSON.Deserialize<string>(m.Groups[1].Value);if(File.Exists(Path.Combine(dir,"zotero.sqlite")))return dir;}}}catch(IOException){}return fallback;}
 [STAThread] static int Main(){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;try{if(Flag("--quiet")){var ids=(Arg("--model")??"minilm").Split(',');var chosen=ids.Select(id=>Models.First(m=>(string)m["id"]==id)).ToList();if(Arg("--data-dir")==null||Arg("--download-dir")==null)throw new Exception("Explicit data and download directories required");using(var engine=new Engine()){if(Flag("--cancel-test"))engine.Progress=(phase,p)=>{if(phase=="model"&&p>0.08)engine.Cancel();};string file=null;foreach(var model in chosen)file=engine.Install(model,Arg("--data-dir"),Arg("--download-dir")).GetAwaiter().GetResult();if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),file);return 0;}}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new Installer());return 0;}catch(Exception e){if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),e.Message);return 1;}}
}
internal sealed class Engine:IDisposable {
 readonly CancellationTokenSource stop=new CancellationTokenSource();internal Action<string,double> Progress;internal bool Cancelled {get{return stop.IsCancellationRequested;}}internal void Cancel(){stop.Cancel();}public void Dispose(){stop.Dispose();}
 void Check(){stop.Token.ThrowIfCancellationRequested();}
 void Report(string phase,double p){Check();if(Progress!=null)Progress(phase,p);}
 void Verify(string folder,Dictionary<string,object> manifest){foreach(var f in Setup.Rows(manifest["files"])){Check();string name=(string)f["name"];if(Path.GetFileName(name)!=name||!Setup.Valid(Path.Combine(folder,name),f))throw new Exception("模型校验失败 / Model verification failed");}}
 async Task Fetch(Dictionary<string,object> asset,string target){Check();var uri=new Uri((string)asset["url"]);if(uri.Scheme!="https")throw new Exception("HTTPS required");long expected=Convert.ToInt64(asset["bytes"]);var offline=Setup.Arg("--package-dir");if(offline!=null){File.Copy(Path.Combine(offline,(string)asset["name"]),target);Report("model",0.88);}else{
  using(var handler=new HttpClientHandler {AllowAutoRedirect=false})using(var client=new HttpClient(handler)){client.Timeout=TimeSpan.FromMinutes(15);HttpResponseMessage response=null;try{for(int i=0;i<8;i++){response=await client.GetAsync(uri,HttpCompletionOption.ResponseHeadersRead,stop.Token);if((int)response.StatusCode<300||(int)response.StatusCode>=400)break;var next=response.Headers.Location;if(next==null)throw new Exception("Missing redirect");uri=next.IsAbsoluteUri?next:new Uri(uri,next);response.Dispose();response=null;if(uri.Scheme!="https")throw new Exception("HTTPS required");}if(response==null||response.StatusCode!=HttpStatusCode.OK)throw new Exception("下载暂不可用 / Download unavailable");using(var input=await response.Content.ReadAsStreamAsync())using(var output=File.Create(target)){byte[] buffer=new byte[65536];long total=0;int count;while((count=await input.ReadAsync(buffer,0,buffer.Length,stop.Token))>0){total+=count;if(total>expected)throw new Exception("Unexpected file size");await output.WriteAsync(buffer,0,count,stop.Token);Report("model",0.08+0.80*total/expected);}}}finally{if(response!=null)response.Dispose();}}}
  Check();if(!Setup.Valid(target,asset))throw new Exception("文件校验失败，请重试 / File verification failed");
 }
 internal async Task<string> Install(Dictionary<string,object> model,string data,string downloads){if(!File.Exists(Path.Combine(data,"zotero.sqlite")))throw new Exception("请选择包含 zotero.sqlite 的 Zotero 数据目录 / Choose the Zotero data folder containing zotero.sqlite");var root=Path.Combine(data,"paper-nexus-models");Directory.CreateDirectory(root);using(var mutex=new FileStream(Path.Combine(root,".installer.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){var work=Path.Combine(root,".setup-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(work);try{
  var plugin=(Dictionary<string,object>)Setup.Config["plugin"];var manifest=(Dictionary<string,object>)model["manifest"];var parent=Path.Combine(root,(string)model["id"]);var target=Path.Combine(parent,(string)manifest["version"]);Directory.CreateDirectory(downloads);var xpi=Path.Combine(downloads,(string)plugin["name"]);if(!Setup.Valid(xpi,plugin)){Report("plugin",0.04);var temp=Path.Combine(work,"plugin.xpi");using(var input=Assembly.GetExecutingAssembly().GetManifestResourceStream("plugin.xpi"))using(var output=File.Create(temp))input.CopyTo(output);if(!Setup.Valid(temp,plugin))throw new Exception("Plugin verification failed");Check();File.Copy(temp,xpi,true);}
  bool usable=false;if(Directory.Exists(target)){Report("verify",0.08);try{Verify(target,manifest);usable=true;}catch(IOException){}catch(Exception){Check();}}
  if(!usable){var archive=Path.Combine(work,"model.pnmodel");await Fetch((Dictionary<string,object>)model["package"],archive);Report("verify",0.89);var extracted=Path.Combine(work,"verified");Directory.CreateDirectory(extracted);var files=Setup.Rows(manifest["files"]);var expected=new HashSet<string>(files.Select(f=>(string)f["name"]),StringComparer.Ordinal){"manifest.json"};var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
   using(var zip=ZipFile.OpenRead(archive)){foreach(var entry in zip.Entries){Check();if(!expected.Contains(entry.FullName)||!seen.Add(entry.FullName)||Path.GetFileName(entry.FullName)!=entry.FullName)throw new Exception("Unexpected model archive entry");long limit=entry.FullName=="manifest.json"?4000000:Convert.ToInt64(files.First(f=>(string)f["name"]==entry.FullName)["bytes"]);if(entry.Length>limit)throw new Exception("Unexpected model file size");entry.ExtractToFile(Path.Combine(extracted,entry.FullName));}if(seen.Count!=expected.Count)throw new Exception("Incomplete model package");}
   if(Setup.Canonical(Setup.Parse(File.ReadAllText(Path.Combine(extracted,"manifest.json"))))!=Setup.Canonical(manifest))throw new Exception("Model manifest mismatch");Verify(extracted,manifest);Report("install",0.97);Directory.CreateDirectory(parent);var backup=Path.Combine(work,"previous");if(Directory.Exists(target))Directory.Move(target,backup);try{Directory.Move(extracted,target);}catch{if(Directory.Exists(backup))Directory.Move(backup,target);throw;}}
  string pointer=Path.Combine(parent,"active.json"),staged=Path.Combine(parent,".active-"+Guid.NewGuid().ToString("N"));File.WriteAllText(staged,Setup.JSON.Serialize(manifest),new UTF8Encoding(false));try{if(File.Exists(pointer))File.Replace(staged,pointer,null);else File.Move(staged,pointer);}finally{if(File.Exists(staged))File.Delete(staged);}if(Progress!=null)Progress("done",1);return xpi;
 }finally{if(Directory.Exists(work))Directory.Delete(work,true);}}}
}
internal sealed class Installer:Form {
 bool zh=(Setup.Arg("--lang")??System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName)=="zh",busy,complete;string data=Setup.DefaultData(),xpi;Engine engine;Label heading,intro,status,targetLabel;Button folder,action,cancel,help;ComboBox language;ProgressBar bar;List<CheckBox> options=new List<CheckBox>();List<Label> details=new List<Label>();
 string T(string cn,string en){return zh?cn:en;}
 Label LabelAt(string text,float size,FontStyle style,int x,int y,int w,int h){var l=new Label {Text=text,Font=new Font("Segoe UI",size,style),Location=new Point(x,y),Size=new Size(w,h),ForeColor=Color.FromArgb(35,58,59)};Controls.Add(l);return l;}
 Button ButtonAt(int x,int y,int w,string text,EventHandler handler){var b=new Button {Text=text,Location=new Point(x,y),Size=new Size(w,34),FlatStyle=FlatStyle.Flat,BackColor=Color.White,Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=0;b.Click+=handler;Controls.Add(b);return b;}
 internal Installer(){AutoScaleMode=AutoScaleMode.Dpi;ClientSize=new Size(620,570);MinimumSize=MaximumSize=Size;FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;BackColor=Color.FromArgb(249,247,242);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",9);LabelAt("PAPER NEXUS  /  FOR ZOTERO",9,FontStyle.Bold,32,27,430,20);
  using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("nexus.png")){var image=new Bitmap(s);Controls.Add(new PictureBox {Image=new Bitmap(image),Location=new Point(523,32),Size=new Size(64,64),SizeMode=PictureBoxSizeMode.Zoom});}
  heading=LabelAt("",24,FontStyle.Bold,30,66,480,45);intro=LabelAt("",10,FontStyle.Regular,32,117,556,36);
  for(int i=0;i<Setup.Models.Count;i++){int at=i,y=169+i*99;var panel=new Panel {Location=new Point(30,y),Size=new Size(560,92),BackColor=Color.White};Controls.Add(panel);var radio=new CheckBox {Location=new Point(15,9),Size=new Size(522,28),Font=new Font("Segoe UI",11,FontStyle.Bold)};panel.Controls.Add(radio);radio.Click+=(s,e)=>{complete=false;RefreshText();};options.Add(radio);var detail=new Label {Location=new Point(39,40),Size=new Size(494,45),ForeColor=Color.FromArgb(91,99,99),Font=new Font("Segoe UI",9)};panel.Controls.Add(detail);details.Add(detail);}options[0].Checked=true;
  targetLabel=LabelAt("",9,FontStyle.Regular,34,381,450,20);folder=ButtonAt(32,405,556,"",(s,e)=>{using(var dialog=new FolderBrowserDialog {SelectedPath=data})if(dialog.ShowDialog()==DialogResult.OK){data=dialog.SelectedPath;complete=false;RefreshText();}});status=LabelAt("",9,FontStyle.Regular,34,449,554,47);bar=new ProgressBar {Location=new Point(34,500),Size=new Size(552,5),Maximum=1000,Visible=false};Controls.Add(bar);help=ButtonAt(28,524,86,"",(s,e)=>System.Diagnostics.Process.Start("https://github.com/JunyanKang/paper-nexus/blob/main/docs/INSTALL.md"));language=new ComboBox {Location=new Point(125,527),Size=new Size(113,29),DropDownStyle=ComboBoxStyle.DropDownList};language.Items.AddRange(new object[]{"简体中文","English"});language.SelectedIndex=zh?0:1;language.SelectedIndexChanged+=(s,e)=>{zh=language.SelectedIndex==0;RefreshText();};Controls.Add(language);cancel=ButtonAt(296,524,94,"",(s,e)=>{if(engine!=null)engine.Cancel();cancel.Enabled=false;status.Text=T("正在取消…","Cancelling…");});cancel.Visible=false;action=ButtonAt(402,524,186,"",Start);action.BackColor=Color.FromArgb(22,73,77);action.ForeColor=Color.White;RefreshText();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};Shown+=(s,e)=>{var path=Setup.Arg("--screenshot");if(path!=null){using(var timer=new System.Windows.Forms.Timer {Interval=600}){timer.Tick+=(a,b)=>{timer.Stop();using(var bmp=new Bitmap(Width,Height)){DrawToBitmap(bmp,new Rectangle(0,0,Width,Height));bmp.Save(path);}Close();};timer.Start();while(!IsDisposed&&Visible)Application.DoEvents();}}};
 }
 void RefreshText(){Text=T("Paper Nexus 安装助手","Paper Nexus Installer");heading.Text=T("把文献，连成研究线索。","Connect your research.");intro.Text=T("选择至少一个本地模型，可多选。以后仅更新插件。","Choose one or more models. Update the plugin independently.");for(int i=0;i<options.Count;i++){options[i].Text=(string)Setup.Models[i][zh?"titleZh":"titleEn"];details[i].Text=(string)Setup.Models[i][zh?"detailZh":"detailEn"];}action.Enabled=!busy&&options.Any(o=>o.Checked);targetLabel.Text=T("Zotero 数据目录","Zotero data folder");folder.Text=data;help.Text=T("安装帮助","Help");cancel.Text=T("取消","Cancel");action.Text=complete?T("打开插件文件夹","Show plugin file"):T("下载并安装","Download & install");status.Text=complete?T("模型已就绪。在 Zotero 中从文件安装 XPI，然后在设置中启用所选模型。","Model ready. Install the XPI from file in Zotero, then enable your chosen model in Settings."):T("无需账户或管理员权限。文献内容保留在本机。","No account or administrator access. Library content stays local.");}
 void Busy(bool value){busy=value;options.ForEach(o=>o.Enabled=!value);folder.Enabled=language.Enabled=action.Enabled=!value;cancel.Visible=bar.Visible=value;cancel.Enabled=true;}
 async void Start(object sender,EventArgs e){if(complete){System.Diagnostics.Process.Start("explorer.exe","/select,\""+xpi+"\"");return;}Busy(true);bar.Value=0;status.Text=T("正在准备…","Preparing…");var chosen=Setup.Models.Where((m,i)=>options[i].Checked).ToList();if(chosen.Count==0){Busy(false);return;}int modelIndex=0;engine=new Engine();engine.Progress=(phase,p)=>BeginInvoke(new Action(()=>{if(!busy)return;bar.Value=Math.Min(1000,(int)((modelIndex+p)/chosen.Count*1000));var names=new Dictionary<string,string>{{"plugin",T("准备插件","Preparing plugin")},{"model",T("下载模型","Downloading model")},{"verify",T("校验模型","Verifying model")},{"install",T("安装模型","Installing model")},{"done",T("完成","Done")}};status.Text=(modelIndex+1)+"/"+chosen.Count+" · "+names[phase]+" · "+(int)(p*100)+"%";}));try{foreach(var model in chosen){xpi=await Task.Run(()=>engine.Install(model,data,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PaperNexusInstaller",Setup.Version)));modelIndex++;}complete=true;Busy(false);RefreshText();}catch(Exception error){Busy(false);status.Text=engine.Cancelled?T("已取消，原有模型保留。","Cancelled. Existing model retained."):T("安装未完成，可重试。","Not completed. You can retry.");if(!engine.Cancelled)MessageBox.Show(this,error.Message,T("安装未完成","Installation not completed"),MessageBoxButtons.OK,MessageBoxIcon.Information);}finally{engine.Dispose();engine=null;}}
}
