"""Build the compact MeSH 2026 topic vocabulary from the pinned official XML."""
from pathlib import Path
import argparse, gzip, hashlib, json, re, xml.etree.ElementTree as ET

SOURCE = 'https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/desc2026.gz'
SHA256 = 'ccd4d0d33bebfd4c836a59e7dd0c635b1d4e20c4f5a6abc55e2eb0ba4c8716dd'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path, help=SOURCE)
parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'addon/topic-lexicon.js')
args = parser.parse_args()
assert hashlib.sha256(args.source.read_bytes()).hexdigest() == SHA256, 'Unexpected MeSH source'
terms = set()
with gzip.open(args.source, 'rb') as source:
    for _, record in ET.iterparse(source, events=('end',)):
        if record.tag != 'DescriptorRecord':
            continue
        trees = [node.text for node in record.findall('./TreeNumberList/TreeNumber')]
        names = [record.findtext('./DescriptorName/String') or '']
        for term in record.findall('./ConceptList/Concept/TermList/Term'):
            text = term.findtext('String') or ''
            if term.get('ConceptPreferredTermYN') == 'Y' or re.fullmatch(r'[A-Z][A-Z0-9-]{2,11}', text):
                names.append(text)
        # Anatomy, organisms, diseases, chemicals, techniques, psychiatry and biology.
        # Exact, natural-order phrases only; never synthesize labels from inverted headings.
        if any(tree[0] in 'ABCDEFG' for tree in trees):
            for name in names:
                name = name.lower().strip()
                if re.fullmatch(r'[a-z][a-z0-9 -]{2,63}', name) and len(name.split()) <= 6 and not re.search(r'\b(and|or|but|with|without|for|by|in|to|the|of)\b', name):
                    terms.add(name)
        record.clear()
text = '\n'.join(sorted(terms))
args.output.write_text('/* Derived from NLM MeSH 2026. See vendor/MeSH-NOTICE. Generated by scripts/build_topic_lexicon.py. */\nvar CiteLensTopicLexicon=(()=>{let terms;return{has:value=>(terms??=new Set('+json.dumps(text)+'.split("\\n"))).has(value)};})();\n', encoding='utf-8')
print(len(terms), 'phrases;', args.output.stat().st_size, 'bytes')
