(module
 (memory (export "memory") 1 1024)
 (func (export "row") (param $i i32) (param $n i32) (param $d i32) (param $start i32) (param $out i32)
  (local $j i32) (local $k i32) (local $a i32) (local $b i32) (local $bytes i32) (local $s0 v128) (local $s1 v128)
  (local.set $bytes (i32.mul (local.get $d) (i32.const 8)))
  (local.set $a (i32.mul (local.get $i) (local.get $bytes)))
  (local.set $j (local.get $start))
  (block $end (loop $rows
   (br_if $end (i32.ge_u (local.get $j) (local.get $n)))
   (local.set $b (i32.mul (local.get $j) (local.get $bytes)))
   (local.set $k (i32.const 0))
   (local.set $s0 (v128.const f64x2 0 0)) (local.set $s1 (v128.const f64x2 0 0))
   (loop $dot
    (local.set $s0 (f64x2.add (local.get $s0) (f64x2.mul (v128.load (i32.add (local.get $a) (local.get $k))) (v128.load (i32.add (local.get $b) (local.get $k))))))
    (local.set $s1 (f64x2.add (local.get $s1) (f64x2.mul (v128.load offset=16 (i32.add (local.get $a) (local.get $k))) (v128.load offset=16 (i32.add (local.get $b) (local.get $k))))))
    (local.set $k (i32.add (local.get $k) (i32.const 32)))
    (br_if $dot (i32.lt_u (local.get $k) (local.get $bytes)))
   )
   (local.set $s0 (f64x2.add (local.get $s0) (local.get $s1)))
   (f64.store (i32.add (local.get $out) (i32.mul (local.get $j) (i32.const 8))) (f64.add (f64x2.extract_lane 0 (local.get $s0)) (f64x2.extract_lane 1 (local.get $s0))))
   (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $rows)
  ))
 )
)
