/* Read-only public ORCID records; no identity inference or changes to Zotero items. */
var CiteLensCareer=(()=>{
 const C=CiteLensCore,NC=CiteLensNetworkCore,flights=new Map(),memory=new Map(),waiting=[];let stopped=false,active=0;
 async function request(url){if(active>=2)await new Promise((resolve,reject)=>waiting.push({resolve,reject}));else active++;try{if(stopped)throw Error('已关闭');return await Zotero.HTTP.request('GET',url,{headers:{Accept:'application/json'},responseType:'json',timeout:20000});}finally{const next=waiting.shift();if(next)next.resolve();else active--;}}
 const clean=v=>C.plainTitle(typeof v==='string'?v:v?.value||''),safeURL=v=>{const s=clean(v);return /^https?:\/\/[^\s/@?#]+(?:[/?#][^\s]*)?$/i.test(s)?s:'';};
 function date(raw){const y=Number(raw?.year?.value),m=Number(raw?.month?.value),d=Number(raw?.day?.value);if(!Number.isInteger(y)||y<1000||y>9999)return null;const out={year:y,precision:'year',label:String(y),sort:y*10000};if(Number.isInteger(m)&&m>=1&&m<=12){out.month=m;out.precision='month';out.label+='.'+String(m).padStart(2,'0');out.sort+=m*100;const days=new Date(Date.UTC(y,m,0)).getUTCDate();if(Number.isInteger(d)&&d>=1&&d<=days){out.day=d;out.precision='day';out.label+='.'+String(d).padStart(2,'0');out.sort+=d;}}return out;}
 const source=r=>clean(r.source?.['assertion-origin-name'])||clean(r.source?.['source-name'])||'ORCID';
 function parse(oid,person={},activities={}){
  const events=[],seen=new Map(),merge=(previous,event)=>{previous.sources=[...new Set([...previous.sources,...event.sources])];for(const field of ['organization','department','journal','workType','start','end','DOI'])if(!previous[field]&&event[field])previous[field]=event[field];previous.year=(previous.start||previous.end)?.year||null;previous.endOnly=!previous.start&&!!previous.end;if(previous.DOI)previous.url='https://doi.org/'+previous.DOI;return previous;},add=(row,kind)=>{
   if(!row||row.visibility&&row.visibility!=='public')return;const ids=row['external-ids']?.['external-id']||[],doi=ids.find(i=>i['external-id-type']==='doi'&&i['external-id-relationship']!=='part-of'),doiID=doi&&C.doi(doi['external-id-value']);
   const start=date(row['start-date']||row['publication-date']||row['completion-date']),end=date(row['end-date']),org=clean(row.organization?.name||row['convening-organization']?.name),title=clean(row.title?.title)||clean(row['role-title'])||org||clean(row['review-group-id']);if(!title)return;
   const external=ids.filter(i=>i['external-id-relationship']!=='part-of').map(i=>[i['external-id-type'],clean(i['external-id-value']).toLowerCase()]).sort();
   const key=doiID?'doi:'+doiID:kind+':'+JSON.stringify(external.length?[org,external]:[C.norm(title),C.norm(org),start?.label,end?.label]);
   const event={id:kind+':'+row['put-code'],kind,title,organization:org,department:clean(row['department-name']),journal:clean(row['journal-title']),workType:clean(row.type),start,end,year:(start||end)?.year||null,endOnly:!start&&!!end,DOI:doiID||'',url:doiID?'https://doi.org/'+doiID:safeURL(row.url||row['review-url'])||'https://orcid.org/'+oid,sources:[source(row)],updated:row['last-modified-date']?.value||null};
   const previous=seen.get(key);if(previous)return merge(previous,event);
   seen.set(key,event);events.push(event);return event;
  };
  for(const [section,kind,singular] of [['educations','education','education'],['qualifications','education','qualification'],['employments','employment','employment'],['invited-positions','employment','invited-position'],['distinctions','distinction','distinction'],['memberships','membership','membership'],['services','service','service']])for(const group of activities[section]?.['affiliation-group']||[])for(const summary of group.summaries||[])add(summary[singular+'-summary'],kind);
  for(const [section,kind,key] of [['works','work','work-summary'],['fundings','funding','funding-summary']])for(const group of activities[section]?.group||[]){const rows=[...(group[key]||[])].filter(r=>!r.visibility||r.visibility==='public').sort((a,b)=>Number(b['display-index']||0)-Number(a['display-index']||0));let preferred;for(const row of rows){const event=add(row,kind);if(!event)continue;if(!preferred){preferred=event;continue;}if(event!==preferred&&!(event.DOI&&preferred.DOI&&event.DOI!==preferred.DOI)){merge(preferred,event);events.splice(events.indexOf(event),1);for(const [key,value] of seen)if(value===event)seen.set(key,preferred);}}}
  // Across provider groups, merge a DOI-less duplicate only with one exact
  // title/year/journal match. Different DOI records always remain distinct.
  const titles=new Map();for(const e of events)if(e.kind==='work'&&e.year&&C.norm(e.title).length>=24&&e.journal){const k=JSON.stringify([C.norm(e.title),e.year,C.norm(e.journal)]);if(!titles.has(k))titles.set(k,[]);titles.get(k).push(e);}
  for(const rows of titles.values()){const identified=rows.filter(e=>e.DOI),unidentified=rows.filter(e=>!e.DOI);if(identified.length===1)for(const e of unidentified){merge(identified[0],e);events.splice(events.indexOf(e),1);}}

  events.sort((a,b)=>(a.start?.sort||a.end?.sort||Infinity)-(b.start?.sort||b.end?.sort||Infinity)||a.kind.localeCompare(b.kind)||a.title.localeCompare(b.title));
  const profile={name:clean(person.name?.['credit-name'])||[clean(person.name?.['given-names']),clean(person.name?.['family-name'])].filter(Boolean).join(' '),biography:clean(person.biography?.content),keywords:(person.keywords?.keyword||[]).map(k=>clean(k.content)).filter(Boolean),links:(person['researcher-urls']?.['researcher-url']||[]).map(r=>({title:clean(r['url-name'])||safeURL(r.url),url:safeURL(r.url)})).filter(r=>r.url)};
  return {schema:2,orcid:oid,profile,events};
 }
 function groups(events,{kind='all',descending=false}={}){const grouped=new Map();for(const e of events){if(kind!=='all'&&e.kind!==kind)continue;const y=e.year||0;if(!grouped.has(y))grouped.set(y,[]);grouped.get(y).push(e);}return [...grouped].sort((a,b)=>!a[0]?1:!b[0]?-1:descending?b[0]-a[0]:a[0]-b[0]).map(([year,events])=>({year,events:[...events].sort((a,b)=>((a.start?.sort||a.end?.sort||Infinity)-(b.start?.sort||b.end?.sort||Infinity))*(descending?-1:1))}));}
 const root=()=>PathUtils.join(PathUtils.parent(CiteLensServices.path),'orcid-careers-v1');
 async function cached(oid){if(memory.has(oid))return memory.get(oid);try{const path=PathUtils.join(root(),oid+'.json');if((await IOUtils.stat(path)).size>8*1024*1024)return null;const value=JSON.parse(await IOUtils.readUTF8(path));if(value.schema===2&&value.orcid===oid&&Number.isFinite(value.fetchedAt)&&Array.isArray(value.events)&&value.events.every(e=>e&&typeof e.id==='string'&&typeof e.title==='string'&&typeof e.kind==='string')&&value.profile&&typeof value.profile.name==='string'&&Array.isArray(value.profile.links)&&Array.isArray(value.profile.keywords)){value.events=value.events.filter(e=>e.kind!=='review');remember(oid,value);return value;}}catch(_){}return null;}
 function remember(oid,value){memory.delete(oid);memory.set(oid,value);while(memory.size>6)memory.delete(memory.keys().next().value);}
 async function persist(value){await IOUtils.makeDirectory(root(),{ignoreExisting:true});const path=PathUtils.join(root(),value.orcid+'.json'),text=JSON.stringify(value);if(text.length>4*1024*1024)return;await IOUtils.writeUTF8(path,text,{tmpPath:path+'.tmp'});const files=[];for(const p of await IOUtils.getChildren(root()))if(/\d{4}-\d{4}-\d{4}-[\dX]{4}\.json$/.test(p)){try{const st=await IOUtils.stat(p);files.push({p,time:st.lastModified,bytes:st.size});}catch(_){}}files.sort((a,b)=>b.time-a.time);let bytes=0;for(let i=0;i<files.length;i++){bytes+=files[i].bytes;if(i>=20||bytes>16*1024*1024)await IOUtils.remove(files[i].p,{ignoreAbsent:true});}}
 async function load(input,{force=false}={}){
  const oid=NC.orcid(input);if(!oid)throw Error('请输入有效的 ORCID 编号或 orcid.org 链接');if(stopped)throw Error('已关闭');const old=await cached(oid);if(!force&&old&&Date.now()-old.fetchedAt<(old.partial?300000:86400000))return {...old,cached:true};if(flights.has(oid))return flights.get(oid);
  const work=(async()=>{const results=await Promise.allSettled(['person','activities'].map(route=>request('https://pub.orcid.org/v3.0/'+oid+'/'+route)));if(stopped)throw Error('已关闭');const person=results[0].status==='fulfilled',activities=results[1].status==='fulfilled';if(!person&&!activities){if(old)return {...old,stale:true};throw Error('暂时无法读取公开履历，请稍后重试');}const value=parse(oid,person?results[0].value.response:{},activities?results[1].value.response:{});if(!person&&old)value.profile=old.profile;if(!activities&&old)value.events=old.events;value.partial=!person||!activities;value.fetchedAt=Date.now();remember(oid,value);await persist(value).catch(e=>Zotero.logError(e));return value;})().finally(()=>flights.delete(oid));flights.set(oid,work);return work;
 }
 function stop(){stopped=true;memory.clear();for(const item of waiting.splice(0))item.reject(Error('已关闭'));}
 return {date,parse,groups,safeURL,load,cached,stop};
})();
if(typeof module!=='undefined')module.exports=CiteLensCareer;
