/* Themed controls adapted from Paper Voice's MIT interaction patterns.
 * Keep native select data/events; replace only the OS-owned popup presentation. */
var CiteLensControls={
 documents:new Map(),sequence:0,
 fonts(){if(!this.fontCache){try{this.fontCache=[...new Set(Array.from(Components.classes['@mozilla.org/gfx/fontenumerator;1'].createInstance(Components.interfaces.nsIFontEnumerator).EnumerateAllFonts()))].filter(x=>x&&!x.startsWith('.')).sort((a,b)=>a.localeCompare(b));}catch(_){this.fontCache=['Arial'];}}return this.fontCache;},
 defaultFont(legacy){const names=legacy==='serif'?['Songti SC','Georgia','Times New Roman']:['PingFang SC','Microsoft YaHei','Noto Sans CJK SC','Helvetica Neue','Segoe UI','Arial'];return names.find(x=>this.fonts().includes(x))||this.fonts()[0];},
 install(doc){
  if(this.documents.has(doc))return;const win=doc.defaultView,entries=new Map(),tips=new Map(),listeners=[],scope='.cl-root,.cl-dialog,.cl-floating,.cl-card,.cl-summary,[data-cite-lens]',owns=n=>!!n?.closest?.(scope);let active=null,index=0,tipTarget=null,timer,typeTimer,typed='';
  const el=(tag,cls)=>{const n=doc.createElement(tag);n.className=cls;return n;},menu=el('div','cl-select-popover'),tip=el('div','cl-tooltip');menu.hidden=tip.hidden=true;menu.setAttribute('popover','manual');tip.setAttribute('popover','manual');menu.setAttribute('role','listbox');tip.setAttribute('role','tooltip');tip.id='cl-tooltip-'+(++this.sequence);doc.documentElement.append(menu,tip);
  const listen=(n,k,fn,c=false)=>{n.addEventListener(k,fn,c);listeners.push(()=>n.removeEventListener(k,fn,c));};
  const hideTip=()=>{win.clearTimeout(timer);if(tipTarget){const prior=tipTarget._clDescription;if(prior===null)tipTarget.removeAttribute('aria-describedby');else tipTarget.setAttribute('aria-describedby',prior);delete tipTarget._clDescription;}tipTarget=null;tip.hidden=true;if(tip.matches(':popover-open'))tip.hidePopover();};
  const close=()=>{if(active){for(const target of [active.button,active.editable].filter(Boolean)){target.setAttribute('aria-expanded','false');target.removeAttribute('aria-activedescendant');}}active=null;menu.hidden=true;if(menu.matches(':popover-open'))menu.hidePopover();};
  const highlight=i=>{if(!active)return;index=Math.max(0,Math.min(i,active.select.options.length-1));for(const row of menu.children)row.dataset.focused=String(Number(row.dataset.index)===index);const row=menu.children[index];if(row){active.button.setAttribute('aria-activedescendant',row.id);active.editable?.setAttribute('aria-activedescendant',row.id);const top=row.offsetTop,bottom=top+row.offsetHeight;if(top<menu.scrollTop)menu.scrollTop=top;else if(bottom>menu.scrollTop+menu.clientHeight)menu.scrollTop=bottom-menu.clientHeight;}};
  const choose=i=>{if(!active)return;const entry=active,option=entry.select.options[i];if(!option||option.disabled)return;entry.select.selectedIndex=i;if(entry.editable){entry.editable.value=option.value;entry.editable.dispatchEvent(new win.Event('input',{bubbles:true}));entry.editable.dispatchEvent(new win.Event('change',{bubbles:true}));}close();entry.select.dispatchEvent(new win.Event('change',{bubbles:true}));(entry.editable||entry.button).focus();sync(entry);};
  const open=entry=>{if(entry.select.disabled||entry.editable?.disabled)return;close();hideTip();active=entry;if(entry.editable)entry.select.value=entry.editable.value;menu.replaceChildren();menu.dataset.clData=String(!entry.select.closest('.cl-settings'));menu.id=entry.button.id+'-list';entry.button.setAttribute('aria-controls',menu.id);entry.button.setAttribute('aria-expanded','true');menu.setAttribute('aria-label',entry.button.getAttribute('aria-label')||entry.button.textContent);if(entry.editable){entry.editable.setAttribute('aria-expanded','true');entry.editable.setAttribute('aria-controls',menu.id);}
   Array.from(entry.select.options).forEach((o,i)=>{const row=el('div','cl-select-option');row.id=menu.id+'-'+i;row.dataset.index=i;row.setAttribute('role','option');row.setAttribute('aria-selected',String(o.selected));row.setAttribute('aria-disabled',String(o.disabled));const label=el('span',''),mark=el('span','cl-select-check');label.textContent=o.textContent;mark.textContent=o.selected?'✓':'';mark.setAttribute('aria-hidden','true');row.append(label,mark);row.onpointermove=()=>highlight(i);row.onpointerdown=e=>e.preventDefault();row.onclick=e=>{e.stopPropagation();choose(i);};menu.append(row);});
   menu.hidden=false;menu.style.cssText='left:8px;top:8px;width:max-content;max-height:230px;max-width:'+Math.max(80,win.innerWidth-16)+'px';menu.showPopover();const b=(entry.editable?.parentElement||entry.button).getBoundingClientRect(),width=Math.min(Math.max(menu.offsetWidth,b.width),win.innerWidth-16),below=win.innerHeight-b.bottom-12,above=b.top-12,down=below>=Math.min(menu.scrollHeight,230)||below>=above;menu.style.width=width+'px';menu.style.maxHeight=Math.max(36,Math.min(230,down?below:above))+'px';menu.style.left=Math.max(8,Math.min(b.right-width,win.innerWidth-width-8))+'px';menu.style.top=(down?b.bottom+5:Math.max(8,b.top-menu.offsetHeight-5))+'px';highlight(entry.select.selectedIndex);
  };
  const sync=entry=>{const {select,button,label}=entry;if(!select.isConnected){if(active===entry)close();button.remove();entries.delete(select);return;}const value=select.selectedOptions[0]?.textContent||'';if(label.textContent!==value)label.textContent=value;const disabled=select.disabled||entry.editable?.disabled;if(button.disabled!==!!disabled)button.disabled=!!disabled;delete button.dataset.clTooltip;button.setAttribute('aria-label',entry.editable?.getAttribute('aria-label')||select.getAttribute('aria-label')||Array.from(select.labels||[],x=>x.textContent).join(' ')||value);if(button.hidden!==select.hidden)button.hidden=select.hidden;};
  const enhance=select=>{if(entries.has(select)||!owns(select))return;const button=el('button','cl-select-trigger'),label=el('span','cl-select-value'),arrow=el('span','cl-select-arrow');button.type='button';button.id='cl-combobox-'+(++this.sequence);button.setAttribute('role','combobox');button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');arrow.setAttribute('aria-hidden','true');button.append(label,arrow);select.after(button);button.dataset.clData=String(!select.closest('.cl-settings'));const editable=select.dataset.editableFor&&doc.getElementById(select.dataset.editableFor);const entry={select,button,label,editable,tab:select.getAttribute('tabindex'),descriptors:{}};entries.set(select,entry);select.classList.add('cl-native-select');select.tabIndex=-1;select.setAttribute('aria-hidden','true');
   if(select.dataset.translationSetting)button.dataset.translationSettingProxy=select.dataset.translationSetting;button.dataset.selectId=select.id;
   for(const name of ['value','selectedIndex']){const proto=Object.getOwnPropertyDescriptor(win.HTMLSelectElement.prototype,name);entry.descriptors[name]=Object.getOwnPropertyDescriptor(select,name);Object.defineProperty(select,name,{configurable:true,get(){return proto.get.call(this);},set(v){proto.set.call(this,v);sync(entry);}});}
   button.onclick=e=>{e.preventDefault();e.stopPropagation();active===entry?close():open(entry);};
   button.onkeydown=e=>{if(['ArrowDown','ArrowUp','Home','End','Enter',' ','Escape','Tab'].includes(e.key)){if(e.key==='Tab'){close();return;}e.preventDefault();e.stopPropagation();if(e.key==='Escape'){close();return;}if(e.key==='Enter'||e.key===' '){if(active===entry)choose(index);else open(entry);return;}const was=active===entry;if(!was)open(entry);const options=Array.from(select.options),step=e.key==='ArrowUp'?-1:1;let next=e.key==='Home'?0:e.key==='End'?options.length-1:was?index+step:index;while(options[next]?.disabled)next+=step;highlight(next);return;}if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();if(active!==entry)open(entry);win.clearTimeout(typeTimer);typed+=e.key.toLocaleLowerCase();typeTimer=win.setTimeout(()=>typed='',700);const at=Array.from(select.options).findIndex(o=>!o.disabled&&o.textContent.toLocaleLowerCase().startsWith(typed));if(at>=0)highlight(at);}};if(editable){button.classList.add('cl-model-toggle');label.hidden=true;editable.setAttribute('role','combobox');editable.setAttribute('aria-autocomplete','list');editable.setAttribute('aria-haspopup','listbox');editable.setAttribute('aria-expanded','false');editable.autocomplete='off';editable.spellcheck=false;listen(editable,'keydown',e=>{if(active!==entry&&!['ArrowDown','ArrowUp'].includes(e.key))return;if(['ArrowDown','ArrowUp','Enter','Escape','Tab'].includes(e.key))button.onkeydown(e);});listen(editable,'input',()=>{select.value=editable.value;if(active===entry)close();});}
   sync(entry);
  };
  const allowed=n=>n.matches('.cl-icon-button,.cl-doi,.cl-author-slot,.cl-metrics,[data-metric-detail]');
  const tooltip=n=>{if(!owns(n)||!n.hasAttribute('title'))return;const text=n.getAttribute('title');n.removeAttribute('title');if(!tips.has(n)){tips.set(n,text);Object.defineProperty(n,'title',{configurable:true,get:()=>'',set:v=>{tips.set(n,String(v));if(allowed(n))n.dataset.clTooltip=String(v);else delete n.dataset.clTooltip;}});}else tips.set(n,text);if(allowed(n))n.dataset.clTooltip=text;else delete n.dataset.clTooltip;};
  const scan=n=>{if(n.nodeType!==1)return;if(n.matches('select'))enhance(n);tooltip(n);for(const x of n.querySelectorAll('select,[title]')){if(x.matches('select'))enhance(x);tooltip(x);}};
  const observer=new win.MutationObserver(records=>{for(const r of records){if(r.type==='childList')r.addedNodes.forEach(scan);else tooltip(r.target);}for(const e of entries.values())sync(e);if(active&&(!active.select.isConnected||!active.button.getClientRects().length))close();if(tipTarget&&!tipTarget.isConnected)hideTip();});observer.observe(doc.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['title','disabled','hidden','selected','label']});scan(doc.documentElement);
  listen(doc,'change',e=>{if(entries.has(e.target))sync(entries.get(e.target));});
  listen(doc,'click',e=>{const label=e.target.closest?.('label[for]'),select=label&&doc.getElementById(label.htmlFor);if(entries.has(select)){e.preventDefault();entries.get(select).button.focus();}});
  listen(doc,'pointerdown',e=>{hideTip();if(active&&!active.button.contains(e.target)&&e.target!==active.editable&&!menu.contains(e.target))close();},true);
  const show=n=>{if(!allowed(n)||!n.isConnected||!owns(n)||!n.getClientRects().length||n.getAttribute('aria-expanded')==='true')return;const label=n.querySelector('.cl-select-value');if(label&&label.scrollWidth<=label.clientWidth+1)return;const text=n.dataset.clTooltip;if(!text||text===n.textContent?.trim()&&!n.classList.contains('cl-icon-button'))return;for(const other of this.documents.values())other.hideTip?.();tipTarget=n;n._clDescription=n.getAttribute('aria-describedby');n.setAttribute('aria-describedby',((n._clDescription||'')+' '+tip.id).trim());tip.textContent=text;tip.hidden=false;tip.style.left='8px';tip.style.top='8px';tip.showPopover();const b=n.getBoundingClientRect(),t=tip.getBoundingClientRect(),top=b.bottom+6+t.height<=win.innerHeight-8?b.bottom+6:b.top-t.height-6;tip.style.left=Math.max(8,Math.min(b.left+(b.width-t.width)/2,win.innerWidth-t.width-8))+'px';tip.style.top=Math.max(8,top)+'px';};
  for(const type of ['pointerover','focusin'])listen(doc,type,e=>{const n=e.target.closest?.('[data-cl-tooltip]');if(!owns(n)){hideTip();return;}if(n===tipTarget||n.contains(e.relatedTarget))return;hideTip();timer=win.setTimeout(()=>show(n),type==='focusin'?0:450);});for(const type of ['pointerout','focusout'])listen(doc,type,e=>{const n=e.target.closest?.('[data-cl-tooltip]');if(n?.contains(e.relatedTarget))return;hideTip();});listen(win,'blur',hideTip);
  listen(win,'keydown',e=>{hideTip();if(active&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();const b=active.editable||active.button;close();b.focus();}},true);listen(doc,'scroll',e=>{hideTip();if(active&&!menu.contains(e.target))close();},true);listen(win,'resize',()=>{close();hideTip();});
  const dispose=()=>{observer.disconnect();close();hideTip();win.clearTimeout(typeTimer);listeners.forEach(fn=>fn());for(const [s,e] of entries){e.button.remove();s.classList.remove('cl-native-select');s.removeAttribute('aria-hidden');if(e.tab===null)s.removeAttribute('tabindex');else s.setAttribute('tabindex',e.tab);for(const [key,desc] of Object.entries(e.descriptors)){delete s[key];if(desc)Object.defineProperty(s,key,desc);}}for(const [n,t] of tips){delete n.title;delete n.dataset.clTooltip;if(t)n.setAttribute('title',t);}menu.remove();tip.remove();this.documents.delete(doc);};listen(win,'pagehide',dispose);this.documents.set(doc,{dispose,close,hideTip});
 },
 release(doc){this.documents.get(doc)?.dispose();},stop(){for(const d of [...this.documents.keys()])this.release(d);}
};
