/* Versioned, shared offline resources. No library content leaves this installer. */
var CiteLensModels={
 listeners:new Set(),dead:true,phase:'idle',message:'',ratio:0,installed:new Map(),verified:new Set(),resources:new Set(),catalogURL:'https://raw.githubusercontent.com/JunyanKang/paper-nexus/main/model-catalog.json',
 async start(){this.dead=false;this.phase='idle';this.message='';this.root=PathUtils.join(Zotero.DataDirectory.dir,'paper-nexus-models');this.installed=new Map();this.verified=new Set();this.resources=new Set();this.catalog=CiteLensModelCore.catalog(await (await Zotero.getMainWindow().fetch(CiteLens.rootURI+'model-catalog.json')).json());await IOUtils.makeDirectory(this.root,{ignoreExisting:true});
  this.packages=(await (await Zotero.getMainWindow().fetch(CiteLens.rootURI+'model-packages.json')).json()).models;await this.refreshInstalled();
 },
 async refreshInstalled(){if(this.dead||this.task)return;const found=new Map();for(const model of this.catalog.models){try{const path=PathUtils.join(this.root,model.id,'active.json');if(!await IOUtils.exists(path)||(await IOUtils.stat(path)).size>50000)continue;const m=CiteLensModelCore.manifest(JSON.parse(await IOUtils.readUTF8(path)));if(m.id!==model.id)continue;let complete=true;for(const f of m.files){const file=PathUtils.join(this.directory(m),f.name);if(!await IOUtils.exists(file)||(await IOUtils.stat(file)).size!==f.bytes){complete=false;break;}}if(complete)found.set(m.id,m);}catch(e){Zotero.logError(e);}}if(this.dead||this.task)return;for(const [id,m] of this.installed)if(!found.has(id)||!CiteLensModelCore.equivalent(m,found.get(id)))this.verified.delete(id+'@'+m.version);this.installed=found;this.emit();},

 emit(phase=this.phase,message=this.message,ratio=this.ratio){Object.assign(this,{phase,message,ratio});for(const f of [...this.listeners])try{f(this.snapshot());}catch(e){Zotero.logError(e);}},
 snapshot(){return {phase:this.phase,message:this.message,ratio:this.ratio,busy:!!this.task,selected:this.selected(),models:this.catalog?.models.map(m=>({...m,installed:this.installed.get(m.id)?.version||'',update:CiteLensModelCore.compare(m.version,this.installed.get(m.id)?.version||'0.0.0')>0}))||[]};},
 subscribe(f){this.listeners.add(f);f(this.snapshot());return()=>this.listeners.delete(f);},
 selected(){const wanted=CiteLensServices.state.settings.localModel||'minilm';return this.installed.has(wanted)?wanted:this.installed.has('minilm')?'minilm':this.installed.keys().next().value||wanted;},
 directory(m){return PathUtils.join(this.root,m.id,m.version);},
 async hash(path){const data=await IOUtils.read(path),buffer=await Zotero.getMainWindow().crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');},
 async verify(m,dir,signal){for(let i=0;i<m.files.length;i++){if(this.dead||signal?.aborted)throw Error('已取消');const f=m.files[i],path=PathUtils.join(dir,f.name);if(!await IOUtils.exists(path)||(await IOUtils.stat(path)).size!==f.bytes||await this.hash(path)!==f.sha256)throw Error('模型校验失败，请重新安装');await Zotero.Promise.delay(0);}},
 async prepare(id=this.selected()){
  const m=this.installed.get(id);if(!m)throw Error('请先在设置中安装本地模型');const dir=this.directory(m),key=m.id+'@'+m.version;
  if(!this.verified.has(key)){await this.verify(m,dir);this.verified.add(key);}const name='paper-nexus-model-'+m.id+'-'+m.version.replace(/\./g,'-'),resources=Services.io.getProtocolHandler('resource').QueryInterface(Components.interfaces.nsIResProtocolHandler);resources.setSubstitution(name,Services.io.newURI(Services.io.newFileURI(Zotero.File.pathToFile(dir)).spec.replace(/\/?$/,'/')));this.resources.add(name);return {...m,baseURL:'resource://'+name+'/'};
 },
 async activate(id){await this.prepare(id);if(this.dead)throw Error('已取消');CiteLensServices.state.settings.localModel=id;await CiteLensServices.persist();await CiteLensSemantic.useModel(await this.prepare(id));for(const f of CiteLensNetwork.listeners)f('model');this.emit('ready','模型已就绪',1);},
 async check(){if(this.task||this.phase==='checking')return;const ticket=this.checkTicket=(this.checkTicket||0)+1;this.emit('checking','正在检查模型更新…',0);try{const r=await Zotero.HTTP.request('GET',this.catalogURL,{responseType:'json',timeout:20000}),next=CiteLensModelCore.catalog(r.response);if(this.dead||ticket!==this.checkTicket||this.task)return;this.catalog=next;this.emit('checked',next.models.some(m=>this.installed.has(m.id)&&CiteLensModelCore.compare(m.version,this.installed.get(m.id).version)>0)?'有可用模型更新':'模型已是最新');}catch(e){if(!this.dead&&ticket===this.checkTicket&&!this.task)this.emit('error','模型目录暂不可用，请稍后重试');}},
 cancel(){if(this.committing)return;this.task?.abort();this.cancelDownload?.();},
 async install(id,{archive=null}={}){
  if(this.dead)throw Error('已取消');if(this.task)throw Error('模型安装正在进行中');this.checkTicket=(this.checkTicket||0)+1;const expected=this.catalog.models.find(m=>m.id===id);if(!expected)throw Error('模型目录无此版本');const controller=new (Zotero.getMainWindow().AbortController)(),signal=controller.signal;this.task=controller;const temp=PathUtils.join(this.root,'.install-'+Date.now()+'-'+Math.random().toString(36).slice(2));let reader,downloaded;
  const check=()=>{if(this.dead||signal.aborted)throw Error('已取消');};try{await IOUtils.makeDirectory(temp);this.emit('installing',archive?'正在导入模型…':'正在下载模型…',0);
   if(!archive){const pack=this.packages?.find(p=>p.id===id&&p.version===expected.version);if(pack){downloaded=temp+'.pnmodel';await Zotero.HTTP.download(pack.url,downloaded,{timeout:600000,cancellerReceiver:cancel=>{this.cancelDownload=cancel;if(signal.aborted)cancel();},onProgress:n=>{if(n>pack.bytes){this.cancelDownload?.();return;}this.emit('installing','正在下载模型…',Math.min(.88,n/pack.bytes*.88));}});check();if((await IOUtils.stat(downloaded)).size!==pack.bytes||await this.hash(downloaded)!==pack.sha256)throw Error('模型包校验失败，请重试');archive=downloaded;}}
   if(archive){reader=Components.classes['@mozilla.org/libjar/zip-reader;1'].createInstance(Components.interfaces.nsIZipReader);reader.open(Zotero.File.pathToFile(archive));const names=reader.findEntries('*'),entries=[];while(names.hasMore())entries.push(names.getNext());const permitted=new Set(['manifest.json',...expected.files.map(f=>f.name)]);if(entries.length!==permitted.size||entries.some(n=>!permitted.has(n)))throw Error('模型包内容与清单不一致');if(reader.getEntry('manifest.json').realSize>50000)throw Error('模型清单过大');reader.extract('manifest.json',Zotero.File.pathToFile(PathUtils.join(temp,'manifest.json')));const actual=CiteLensModelCore.manifest(JSON.parse(await IOUtils.readUTF8(PathUtils.join(temp,'manifest.json'))));if(!CiteLensModelCore.equivalent(expected,actual))throw Error('模型包版本与当前目录不一致');
    for(let i=0;i<expected.files.length;i++){check();const f=expected.files[i];if(reader.getEntry(f.name).realSize!==f.bytes)throw Error('模型文件大小不符');reader.extract(f.name,Zotero.File.pathToFile(PathUtils.join(temp,f.name)));this.emit('installing','正在导入模型…',(i+1)/expected.files.length*.9);await Zotero.Promise.delay(0);}reader.close();reader=null;
   }else{const total=expected.files.reduce((s,f)=>s+f.bytes,0);let completed=0;for(const f of expected.files){check();await Zotero.HTTP.download(f.url,PathUtils.join(temp,f.name),{timeout:180000,cancellerReceiver:cancel=>{this.cancelDownload=cancel;if(signal.aborted)cancel();},onProgress:n=>{if(n>f.bytes){this.cancelDownload?.();return;}this.emit('installing','正在下载模型…',Math.min(.9,(completed+n)/total*.9));}});completed+=f.bytes;}}
   check();this.emit('verifying','正在校验模型…',.94);await this.verify(expected,temp,signal);check();this.committing=true;const dir=this.directory(expected);await IOUtils.makeDirectory(PathUtils.parent(dir),{ignoreExisting:true});
   // Existing same-version resources are immutable; a failed install never removes them.
   if(await IOUtils.exists(dir)){try{await this.verify(expected,dir,signal);}catch(e){check();const backup=dir+'.backup-'+Date.now();await IOUtils.move(dir,backup);try{await IOUtils.move(temp,dir);}catch(error){await IOUtils.move(backup,dir);throw error;}}}else await IOUtils.move(temp,dir);check();await IOUtils.writeUTF8(PathUtils.join(PathUtils.parent(dir),'active.json'),JSON.stringify(expected),{tmpPath:PathUtils.join(PathUtils.parent(dir),'active.json.tmp')});this.installed.set(id,expected);this.verified.add(id+'@'+expected.version);await this.activate(id);this.emit('ready','模型已安装',1);
  }catch(e){this.emit(signal.aborted?'idle':'error',signal.aborted?'已取消':e.message,0);throw e;}finally{reader?.close();this.cancelDownload=null;this.task=null;this.committing=false;await IOUtils.remove(temp,{recursive:true,ignoreAbsent:true});if(downloaded)await IOUtils.remove(downloaded,{ignoreAbsent:true});this.emit();}
 },
 async importArchive(path){const reader=Components.classes['@mozilla.org/libjar/zip-reader;1'].createInstance(Components.interfaces.nsIZipReader);let id;const temp=PathUtils.join(this.root,'.manifest-'+Date.now()+'.json');try{reader.open(Zotero.File.pathToFile(path));if(!reader.hasEntry('manifest.json')||reader.getEntry('manifest.json').realSize>50000)throw Error('请选择 Paper Nexus 模型包');reader.extract('manifest.json',Zotero.File.pathToFile(temp));id=CiteLensModelCore.manifest(JSON.parse(await IOUtils.readUTF8(temp))).id;}finally{reader.close();await IOUtils.remove(temp,{ignoreAbsent:true});}return this.install(id,{archive:path});},
 async stop(){this.dead=true;this.checkTicket=(this.checkTicket||0)+1;this.task?.abort();this.cancelDownload?.();this.listeners.clear();for(const name of this.resources)Services.io.getProtocolHandler('resource').QueryInterface(Components.interfaces.nsIResProtocolHandler).setSubstitution(name,null);this.resources.clear();}
};
