/* Network-first local research canvas. The worker owns expensive layout; the UI owns navigation. */
var CiteLensNetworkUI={
 open(reader=null,{doc=Zotero.getMainWindow().document,onClose=null}={}){
  const existing=doc.querySelector('.pn-network');if(existing){existing.focus();return existing;}
  const U=CiteLensUI,N=CiteLensNetwork,C=CiteLensCore,NC=CiteLensNetworkCore,V=CiteLensNetworkView,win=doc.defaultView;
  let reloadEpoch=0;let alive=true,data,model=null,selected='',hover='',mode='authors',focused=false,limit=600,externalLimit=300,expanded=new Set(),controller=null,epoch=0,expanding=false,cancelExpansion=false,unsubscribe=()=>{},reloadTimer,searchTimer,raf=0,animation=null,drag=null,history=[],loaded=false;
  const dialog=U.dialog(doc,'Paper Nexus',{className:'pn-network pn-map-window',onClose:()=>{alive=false;epoch++;cancelExpansion=true;controller?.abort();unsubscribe();win.clearTimeout(reloadTimer);win.clearTimeout(searchTimer);win.cancelAnimationFrame(raf);win.clearTimeout(settleTimer);resize.disconnect();themeObserver.disconnect();N.views.delete(dialog.close);onClose?.();}}),{frame,root,footer}=dialog;N.views.add(dialog.close);root.classList.add('pn-map-body');frame.dataset.paperNexus='network';
  const header=frame.querySelector('.cl-dialog-header');header.insertBefore(U.iconButton(doc,'设置','settings',()=>U.settingsDialog(doc)),header.querySelector('.cl-dismiss'));
  const bar=U.el(doc,'div',null,'pn-map-controls'),library=U.el(doc,'select'),collection=U.el(doc,'select'),searchWrap=U.el(doc,'div',null,'pn-map-search'),search=U.el(doc,'input'),suggestions=U.el(doc,'div',null,'pn-search-results'),views=U.el(doc,'div',null,'pn-map-views');
  library.setAttribute('aria-label','文献库');collection.setAttribute('aria-label','文献夹');search.type='search';search.placeholder='定位文献或作者';search.setAttribute('aria-label','定位文献或作者');search.setAttribute('role','combobox');search.setAttribute('aria-autocomplete','list');search.setAttribute('aria-expanded','false');suggestions.hidden=true;suggestions.id='pn-search-'+(++U.sequence);suggestions.setAttribute('role','listbox');search.setAttribute('aria-controls',suggestions.id);searchWrap.append(search,suggestions);
  const option=(el,value,label)=>{const o=U.el(doc,'option',label);o.value=value;el.append(o);};
  for(const [value,label] of [['authors','作者'],['topics','主题']]){const b=U.quiet(doc,label,()=>{if(mode===value)return;mode=value;focused=false;for(const child of views.children)child.setAttribute('aria-pressed',String(child===b));build(true);});b.dataset.groupMode=value;b.setAttribute('aria-pressed',String(mode===value));views.append(b);}views.setAttribute('aria-label','聚类方式');
  const expand=U.quiet(doc,'扩展引文',()=>expandReferences());expand.dataset.expandCitations='true';bar.append(library,collection,searchWrap,views,expand);
  const status=U.el(doc,'div','','cl-status'),workspace=U.el(doc,'div',null,'pn-map-workspace'),stage=U.el(doc,'div',null,'pn-map-stage'),canvas=U.el(doc,'canvas',null,'pn-map-canvas'),inspector=U.el(doc,'aside',null,'pn-map-inspector'),loader=U.el(doc,'div',null,'pn-map-loading'),loadingLabel=U.el(doc,'span','正在读取本地文献…'),progress=U.el(doc,'progress'),cancel=U.quiet(doc,'取消',()=>{cancelExpansion=true;controller?.abort();epoch++;reloadEpoch++;loader.hidden=true;expand.disabled=false;U.status(status,'已取消，现有网络保留');});
  canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','本地文献网络；可搜索定位，方向键平移，加减号缩放，Enter 查看当前节点');inspector.hidden=true;progress.max=100;progress.value=5;loader.append(U.logo(doc,42),loadingLabel,progress,cancel);loader.setAttribute('role','status');stage.append(canvas,loader);workspace.append(stage,inspector);root.append(bar,status,workspace);
  const tools=U.el(doc,'div',null,'pn-map-tools'),fitButton=U.quiet(doc,'全景',()=>{focused=false;fit();draw();}),focusButton=U.quiet(doc,'聚焦',()=>{if(!selected)return;focused=!focused;focusButton.setAttribute('aria-pressed',String(focused));fit();draw();});focusButton.disabled=true;
  tools.append(U.quiet(doc,'＋',()=>zoomAt(1.25)),U.quiet(doc,'−',()=>zoomAt(.8)),fitButton,focusButton);stage.append(tools);
  const legend=U.el(doc,'div',null,'pn-map-legend');legend.append(U.el(doc,'span','● 本地论文'),U.el(doc,'span','○ 扩展引文'),U.el(doc,'span','→ 引用'),U.el(doc,'span','— 作者／主题'));stage.append(legend);
  const count=U.el(doc,'span','','pn-map-count'),more=U.quiet(doc,'再载入 600 篇',()=>{limit+=600;build(false);});more.hidden=true;footer.append(count,more);
  const camera={x:0,y:0,k:1},target={...camera};let dimensions={w:800,h:500},palette=[],ink='',muted='',paper='',accent='',font='sans-serif',index=null,scene=null,sceneKey='',themeDirty=true,movingUntil=0,settleTimer=0,lastFrame=0,pointer=null,morph=null;
  const reduced=win.matchMedia('(prefers-reduced-motion: reduce)');
  const related=id=>index?.adj.get(id)||new Set([id]);
  const visible=()=>!model?[]:focused&&selected?model.nodes.filter(n=>related(selected).has(n.id)):model.nodes;
  const sync=()=>Object.assign(target,camera);
  const motion=()=>{movingUntil=win.performance.now()+100;win.clearTimeout(settleTimer);settleTimer=win.setTimeout(draw,110);draw();};
  const fit=(animated=true)=>{const nodes=visible();if(!nodes.length)return;const xs=nodes.map(n=>n.x),ys=nodes.map(n=>n.y),left=Math.min(...xs)-55,right=Math.max(...xs)+55,top=Math.min(...ys)-55,bottom=Math.max(...ys)+55,k=Math.min(2.2,Math.max(.08,Math.min((dimensions.w-55)/(right-left),(dimensions.h-90)/(bottom-top))));Object.assign(target,{k,x:dimensions.w/2-(left+right)/2*k,y:(dimensions.h-25)/2-(top+bottom)/2*k});if(!animated||reduced.matches)Object.assign(camera,target);motion();};
  const center=node=>{target.x=dimensions.w/2-node.x*target.k;target.y=dimensions.h/2-node.y*target.k;motion();};
  const zoomAt=(factor,x=dimensions.w/2,y=dimensions.h/2)=>{Object.assign(target,V.zoom(target,factor,x,y));motion();};
  const size=()=>{const r=stage.getBoundingClientRect();if(r.width<1||r.height<1)return;const old=dimensions;dimensions={w:r.width,h:r.height};const dpr=Math.min(2,win.devicePixelRatio||1),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;camera.x+=(r.width-old.w)/2;camera.y+=(r.height-old.h)/2;target.x+=(r.width-old.w)/2;target.y+=(r.height-old.h)/2;draw();};
  const resize=new win.ResizeObserver(size);resize.observe(stage);const themeObserver=new win.MutationObserver(()=>{themeDirty=true;draw();});themeObserver.observe(doc.documentElement,{attributes:true,attributeFilter:['style','data-cl-theme']});
  function draw(){if(raf||!alive)return;raf=win.requestAnimationFrame(paint);}
  function paint(now){raf=0;if(!alive)return;const started=win.performance.now(),pending=V.step(camera,target,lastFrame?now-lastFrame:16,reduced.matches);lastFrame=now;
   if(morph){const t=Math.min(1,(now-morph.start)/380),ease=1-Math.pow(1-t,3);for(const p of morph.points){p.node.x=p.x+(p.tx-p.x)*ease;p.node.y=p.y+(p.ty-p.y)*ease;}if(t===1)morph=null;}
   if(themeDirty){const css=win.getComputedStyle(frame);ink=css.getPropertyValue('--cl-ink').trim();muted=css.getPropertyValue('--cl-muted').trim();paper=css.getPropertyValue('--cl-bg').trim();accent=css.getPropertyValue('--cl-accent').trim();font=css.getPropertyValue('--cl-reading-font')||'sans-serif';const dark=['midnight','botanical','aurora','velvet'].includes(CiteLensThemes.resolve(CiteLensServices.state.settings.theme).id);palette=dark?['#98cbbc','#c4b6e6','#e2bd8a','#87bddf','#d7a5b1','#abc99e']:['#377c73','#846ab0','#ab7b34','#367ca5','#a36578','#6b8348'];themeDirty=false;}
   const ctx=canvas.getContext('2d'),dpr=canvas.width/dimensions.w;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,dimensions.w,dimensions.h);if(!model)return;
   const key=selected+'|'+focused+'|'+(camera.k<.9)+'|'+(model.matches||[]).join(',');if(key!==sceneKey||!scene){scene=V.scene(model,index,{selected,focused,k:camera.k});sceneKey=key;}
   const moving=pending||!!morph||now<movingUntil||!!drag?.moved,near=selected||hover?new Set([selected||hover]):null,matches=new Set(model.matches||[]),screen=n=>({x:n.x*camera.k+camera.x,y:n.y*camera.k+camera.y});
   if(near)for(const e of scene.edges){if(e.source===(selected||hover))near.add(e.target);if(e.target===(selected||hover))near.add(e.source);}
   if(pointer&&!drag&&!moving){const id=hitPoint(pointer)?.id||'';if(id!==hover){hover=id;canvas.style.cursor=id?'pointer':'grab';draw();}pointer=null;}
   let edgesDrawn=0;ctx.lineCap='round';
   for(const e of scene.edges){const active=e.source===selected||e.target===selected||e.source===hover||e.target===hover;
    if(moving&&!active||scene.edges.length>180&&!active)continue;
    const a=screen(index.byID.get(e.source)),b=screen(index.byID.get(e.target));if(Math.max(a.x,b.x)<0||Math.min(a.x,b.x)>dimensions.w||Math.max(a.y,b.y)<0||Math.min(a.y,b.y)>dimensions.h)continue;
    ctx.globalAlpha=active?.48:near?.05:e.kind==='cites'?.18:.1;ctx.strokeStyle=active?accent:muted;ctx.lineWidth=active?1.25:.8;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();edgesDrawn++;
    if(e.kind==='cites'&&active&&!moving){const angle=Math.atan2(b.y-a.y,b.x-a.x),x=b.x-Math.cos(angle)*9,y=b.y-Math.sin(angle)*9;ctx.beginPath();ctx.moveTo(x-Math.cos(angle-.4)*5,y-Math.sin(angle-.4)*5);ctx.lineTo(x,y);ctx.lineTo(x-Math.cos(angle+.4)*5,y-Math.sin(angle+.4)*5);ctx.stroke();}
   }
   const candidates=[];let nodesDrawn=0;
   for(const n of scene.nodes){const p=screen(n);if(p.x< -80||p.x>dimensions.w+80||p.y< -35||p.y>dimensions.h+35)continue;const picked=n.id===selected||n.id===hover,matched=matches.has(n.id),active=!near||near.has(n.id),hub=n.kind!=='paper',r=hub?Math.min(11,6+Math.log2(1+(n.members?.length||1))):Math.max(2.5,Math.min(5,4*Math.sqrt(camera.k)));
    if(picked||matched){ctx.globalAlpha=.12;ctx.fillStyle=accent;ctx.beginPath();ctx.arc(p.x,p.y,r+7,0,Math.PI*2);ctx.fill();}
    ctx.globalAlpha=active?1:.16;ctx.fillStyle=picked?accent:palette[n.color];ctx.strokeStyle=palette[n.color];ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);if(n.local===false){ctx.fillStyle=paper;ctx.fill();ctx.stroke();}else ctx.fill();nodesDrawn++;
    if(moving&&!picked&&!matched)continue;if(!picked&&!matched&&(!active||!hub&&camera.k<1.3))continue;
    const text=hub?n.title:[n.creators?.[0]?.lastName||n.author||n.title.slice(0,26),n.year].filter(Boolean).join(' · '),label=text.length>38?text.slice(0,37)+'…':text,count=hub?'  '+n.members.length:'',size=picked?12:11;
    ctx.font=(picked?'600 ':'500 ')+size+'px '+font;const width=ctx.measureText(label+count).width;
    candidates.push({id:n.id,priority:(picked?10000:matched?5000:hub?100:0)+(n.members?.length||0),rect:{x:p.x-width/2-3,y:p.y+r+4,w:width+6,h:19},p,r,label,count,size,picked});
   }
   const labels=V.labels(candidates,dimensions.w,dimensions.h);ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.lineJoin='round';
   for(const c of labels){ctx.globalAlpha=1;ctx.font=(c.picked?'600 ':'500 ')+c.size+'px '+font;ctx.strokeStyle=paper;ctx.lineWidth=4;ctx.strokeText(c.label+c.count,c.p.x,c.p.y+c.r+17);ctx.fillStyle=c.picked?accent:ink;ctx.fillText(c.label+c.count,c.p.x,c.p.y+c.r+17);}
   ctx.globalAlpha=1;frame._pnScene={aggregate:scene.aggregate,nodes:nodesDrawn,edges:edgesDrawn,labels:labels.length,moving,paintMS:win.performance.now()-started};if(pending||morph)draw();
  }
  function hitPoint(p){let closest=null,best=14;for(const n of scene?.nodes||[]){const distance=Math.hypot(p.x-(n.x*camera.k+camera.x),p.y-(n.y*camera.k+camera.y));if(distance<best){closest=n;best=distance;}}return closest;}
  function hit(e){const r=canvas.getBoundingClientRect();return hitPoint({x:e.clientX-r.left,y:e.clientY-r.top});}
  function showSearch(){const query=search.value.trim();suggestions.replaceChildren();if(!query||!data){suggestions.hidden=true;search.setAttribute('aria-expanded','false');if(model){model.matches=[];draw();}return;}
   const norm=C.norm(query),found=[...(model?.nodes||[]).filter(n=>n.kind!=='paper'&&C.norm(n.title).includes(norm)),...NC.search(N.scope(data,library.value,collection.value),query)];const seen=new Set();for(const n of found){if(seen.has(n.id))continue;seen.add(n.id);if(seen.size>8)break;const b=U.button(doc,n.title+(n.year?' · '+n.year:''),async()=>{suggestions.hidden=true;search.setAttribute('aria-expanded','false');await choose(n.id);if(model){const target=model.nodes.find(x=>x.id===n.id);if(target)center(target);}});b.setAttribute('role','option');suggestions.append(b);}if(!found.length)suggestions.append(U.el(doc,'span','没有匹配结果'));suggestions.hidden=false;search.setAttribute('aria-expanded','true');if(model){model.matches=found.map(n=>n.id);draw();}
  }
  const record=node=>({...node,author:node.author||node.creators?.[0]?.lastName||'',authors:node.creators});
  const path=node=>(node.collections||[]).map(id=>{const names=[],seen=new Set();let c=data.collections.find(c=>c.id===id);while(c&&!seen.has(c.id)){seen.add(c.id);names.unshift(c.name);c=data.collections.find(x=>x.id===c.parentID);}return names.join(' › ');}).filter(Boolean).join(' · ');
  async function choose(id){if(selected&&selected!==id)history.push(selected);selected=data?.aliases?.get(id)||id;focusButton.disabled=false;focused=false;focusButton.setAttribute('aria-pressed','false');if(!model?.nodes.some(n=>n.id===selected)){await build(false);if(!alive)return;}showInspector();draw();}
  function showInspector(){inspector.replaceChildren();const n=model?.nodes.find(n=>n.id===selected);if(!n){inspector.hidden=true;focusButton.disabled=true;return;}inspector.hidden=false;
   const top=U.el(doc,'div',null,'pn-inspector-tools'),back=U.quiet(doc,'返回',()=>{selected=history.pop()||'';focused=false;showInspector();draw();});back.disabled=!history.length;const close=U.quiet(doc,'×',()=>{selected='';focused=false;inspector.hidden=true;focusButton.disabled=true;draw();});close.setAttribute('aria-label','关闭节点详情');top.append(back,U.quiet(doc,'聚焦关联',()=>{focused=true;focusButton.setAttribute('aria-pressed','true');fit();draw();}),close);inspector.append(top,U.title(doc,n,'h3'));
   if(n.kind==='paper'){
    inspector.append(U.el(doc,'div',[n.creators?.[0]?.lastName||n.author,n.year,n.journal,n.local?'本地论文':'扩展引文'].filter(Boolean).join(' · '),'pn-node-meta'));if(n.creators?.length)inspector.append(U.el(doc,'p',CiteLensAuthors.visible(n.creators).map(x=>[x.author.firstName,x.author.lastName].filter(Boolean).join(' ')+(x.gapAfter?' …':'')).join(' · '),'pn-authorline'));
    const actions=U.el(doc,'div',null,'cl-actions');if(n.local){actions.append(U.quiet(doc,'打开条目',async()=>{await N.openItem(n);dialog.close();}));if(n.attachments?.length)actions.append(U.quiet(doc,'阅读全文',async()=>{await N.openPDF(n);dialog.close();}));}else actions.append(U.quiet(doc,'保存文献',()=>U.saveDialog(doc,record(n),null,()=>reload())));
    actions.append(U.iconButton(doc,U.queued(record(n))?'已在清单':'稍后读',U.queued(record(n))?'bookmarked':'bookmark',async b=>{await CiteLensServices.enqueue(record(n),null);U.setButtonLabel(b,'已在清单','bookmarked');}));if(C.recordDOI(n))actions.append(U.quiet(doc,'DOI ↗',()=>Zotero.launchURL('https://doi.org/'+C.recordDOI(n))));inspector.append(actions);const loc=path(n);if(loc)inspector.append(U.el(doc,'p',loc,'pn-location'));
    if(n.copies?.length>1){const copies=U.el(doc,'details',null,'pn-copies');copies.append(U.el(doc,'summary',n.copies.length+' 个副本'));for(const c of n.copies)copies.append(U.quiet(doc,path(c)||'文献库中的条目',async()=>{await N.openItem(c);dialog.close();}));inspector.append(copies);}
    const abs=U.el(doc,'div',null,'pn-node-abstract');if(n.abstract)abs.textContent=n.abstract;else abs.textContent='本地暂无摘要';inspector.append(abs);
   }else inspector.append(U.el(doc,'p',n.kind==='author'?'完整署名相同，作者身份仍需核实。':n.kind==='references'?'来自同一篇论文的参考文献。':'题目与摘要内容相近，不代表结论一致。','pn-task-note'));
   const sections=[['cites-out','引用文献'],['cites-in','引用它的文献'],['author','作者与论文'],['topic','主题与论文'],['related','已有相关条目'],['reference-group','参考文献']];
   const incident=index.links.get(n.id)||[];
   for(const [key,label] of sections){const relations=incident.filter(e=>key==='cites-out'?e.kind==='cites'&&e.source===n.id:key==='cites-in'?e.kind==='cites'&&e.target===n.id:e.kind===key);if(!relations.length)continue;const section=U.el(doc,'section',null,'pn-node-connections');section.append(U.el(doc,'h4',label+' · '+relations.length));let shown=0;
    const more=U.quiet(doc,'更多关联',()=>append());more.classList.add('pn-relations-more');
    const append=()=>{const fragment=doc.createDocumentFragment();for(const e of relations.slice(shown,shown+16)){const target=index.byID.get(e.source===n.id?e.target:e.source);if(!target)continue;const row=U.el(doc,'div',null,'pn-node-link'),title=U.quiet(doc,target.title,()=>choose(target.id));title.dataset.clData='true';row.append(title);if(e.kind==='cites'&&e.evidence?.[0]?.attachmentID){const source=data.byID.get(e.source),proof=U.iconButton(doc,'打开引用来源','locate',async()=>{await N.openPDF(source,e.evidence[0]);dialog.close();});row.append(proof);}fragment.append(row);}shown+=16;section.insertBefore(fragment,more);more.hidden=shown>=relations.length;};
    section.append(more);append();inspector.append(section);
   }
   expand.disabled=expanding||n.local===false;size();
  }
  async function build(fitAfter=false,background=false){if(!data||!alive)return;controller?.abort();controller=new win.AbortController();const ticket=++epoch;loader.hidden=background;loadingLabel.textContent='正在排列文献网络…';progress.value=10;const scoped=N.scope(data,library.value,collection.value);const payload={nodes:scoped,edges:data.edges,references:[...data.references],mode,expanded:[...expanded],limit,externalLimit,query:search.value,selected,positions:(model?.nodes||[]).map(n=>({id:n.id,x:n.x,y:n.y,pinned:n.pinned}))};
   try{const next=await N.compute('map',payload,{signal:controller.signal,progress:value=>{if(ticket===epoch)progress.value=value;}});if(!alive||ticket!==epoch)return;const previous=index?.byID,oldSelected=previous?.get(selected);model=next;index=V.index(model);scene=null;sceneKey="";if(!model.nodes.some(n=>n.id===selected))selected=oldSelected&&C.recordDOI(oldSelected)?model.nodes.find(n=>C.recordDOI(n)===C.recordDOI(oldSelected))?.id||'':'';
    frame._pnModel=model;frame._pnSelect=choose;frame._pnBuild=build;frame._pnCamera=camera;showInspector();size();if(fitAfter)fit(!!previous);if(previous&&!reduced.matches){morph={start:win.performance.now(),points:model.nodes.filter(n=>previous.has(n.id)&&!n.pinned).map(node=>({node,x:previous.get(node.id).x,y:previous.get(node.id).y,tx:node.x,ty:node.y}))};for(const p of morph.points){p.node.x=p.x;p.node.y=p.y;}}count.textContent=model.stats.local+' / '+model.stats.total+' 篇本地 · '+model.stats.external+' 篇扩展'+(mode==='topics'?' · '+model.stats.topics+' 个主题':' · '+model.stats.authors+' 个署名');more.hidden=!model.stats.hidden;expand.disabled=expanding||model.nodes.find(n=>n.id===selected)?.local===false;U.status(status,model.nodes.length?'':'当前范围暂无文献，可选择其他文献夹。');if(!win.matchMedia('(prefers-reduced-motion: reduce)').matches)canvas.animate([{opacity:.35},{opacity:1}],{duration:240,easing:'ease-out'});draw();
   }catch(e){if(alive&&ticket===epoch&&e.message!=='已取消')U.status(status,e.message,true);}finally{if(alive&&ticket===epoch)loader.hidden=true;}
  }
  const collections=()=>{collection.replaceChildren();option(collection,'','所有文献夹');for(const c of data.collections.filter(c=>!library.value||c.libraryID===Number(library.value)))option(collection,String(c.id),'　'.repeat(c.level)+c.name);};
  async function reload(){const reloadTicket=++reloadEpoch;const currentLibrary=library.value,currentCollection=collection.value;loader.hidden=false;loadingLabel.textContent='正在读取本地文献…';progress.value=5;try{data=await N.snapshot();if(!alive||reloadTicket!==reloadEpoch)return;library.replaceChildren();option(library,'','全部文献库');for(const l of data.libraries)option(library,String(l.id),l.name);library.value=loaded?currentLibrary:String(Zotero.Items.get(reader?.itemID)?.libraryID||Zotero.getActiveZoteroPane().getSelectedLibraryID()||'');collections();collection.value=currentCollection;if(loaded)selected=data.aliases.get(selected)||selected;expanded=new Set([...expanded].map(id=>data.aliases.get(id)||id));const initial=!loaded;loaded=true;await build(initial);}catch(e){if(alive){loader.hidden=true;U.status(status,e.message,true);}}}
  async function expandReferences(){if(!model||expanding)return;const node=model.nodes.find(n=>n.id===selected),ids=node?.kind==='paper'?[node.id]:node?.members||model.nodes.filter(n=>n.local&&data.references.has(n.id)).map(n=>n.id);const sources=ids.map(id=>data.byID.get(id)).filter(Boolean);if(!sources.length){U.status(status,'请选择一篇有本地 PDF 的论文，再扩展其参考文献');return;}expanding=true;cancelExpansion=false;expand.disabled=true;let processed=0;try{
    for(const source of sources){if(!alive||cancelExpansion)break;if(!data.references.has(source.id)){const attachment=source.attachments.find(a=>a.type==='application/pdf');if(!attachment)continue;if(processed>=12)break;loader.hidden=false;loadingLabel.textContent='正在读取引文 · '+(processed+1)+' / '+Math.min(12,sources.length);progress.value=Math.round(processed/Math.min(12,sources.length)*100);const r=await Zotero.Reader.open(attachment.id);await r._initPromise;if(!alive||cancelExpansion)break;CiteLens.attach(r);const refs=await CiteLens.references(r);await N.remember(r,refs);processed++;}expanded.add(source.id);}
    if(!alive)return;externalLimit+=300;data=await N.snapshot();await build(true);if(cancelExpansion)U.status(status,'已停止扩展，已读取的引文保留');else if(!expanded.size)U.status(status,'所选论文没有可读取的本地 PDF');else if(model.stats.omittedReferences)U.status(status,'部分参考文献信息不完整、匹配不唯一或超出本次范围；可继续扩展');
   }catch(e){if(alive)U.status(status,e.message,true);}finally{expanding=false;if(alive){expand.disabled=false;loader.hidden=true;}}}
  library.addEventListener('change',()=>{collections();selected='';focused=false;expanded.clear();build(true);});collection.addEventListener('change',()=>{selected='';focused=false;expanded.clear();build(true);});search.addEventListener('input',()=>{win.clearTimeout(searchTimer);searchTimer=win.setTimeout(showSearch,120);});search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();suggestions.querySelector('button')?.click();}else if(e.key==='ArrowDown'){e.preventDefault();suggestions.querySelector('button')?.focus();}else if(e.key==='Escape'){e.stopPropagation();suggestions.hidden=true;search.setAttribute('aria-expanded','false');}});suggestions.addEventListener('keydown',e=>{const all=[...suggestions.querySelectorAll('button')],i=all.indexOf(doc.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();all[(i+(e.key==='ArrowDown'?1:all.length-1))%all.length]?.focus();}});root.addEventListener('pointerdown',e=>{if(!searchWrap.contains(e.target)){suggestions.hidden=true;search.setAttribute('aria-expanded','false');}});
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;controller?.abort();epoch++;morph=null;sync();canvas.setPointerCapture(e.pointerId);const n=hit(e);drag={n,startX:e.clientX,startY:e.clientY,x:camera.x,y:camera.y,nx:n?.x,ny:n?.y,moved:false};});
  canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(drag.n&&drag.moved){drag.n.x=drag.nx+dx/camera.k;drag.n.y=drag.ny+dy/camera.k;drag.n.pinned=true;}else if(!drag.n){camera.x=drag.x+dx;camera.y=drag.y+dy;sync();}motion();}else{const r=canvas.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top};draw();}});
  canvas.addEventListener('pointerup',e=>{if(!drag)return;const state=drag;drag=null;canvas.releasePointerCapture(e.pointerId);if(!state.moved&&state.n)choose(state.n.id);else if(!state.moved){selected='';focused=false;showInspector();}else if(state.n){build(false,true);}draw();});canvas.addEventListener('pointercancel',()=>{drag=null;draw();});canvas.addEventListener('pointerleave',()=>{hover='';pointer=null;draw();});
  canvas.addEventListener('dblclick',e=>{const n=hit(e);if(n){selected=n.id;focused=true;showInspector();fit();draw();}});
  canvas.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();if(drag)return;const r=canvas.getBoundingClientRect(),delta=V.wheel(e,dimensions.h);Object.assign(target,V.zoom(target,delta.zoom,e.clientX-r.left,e.clientY-r.top));target.x+=delta.x;target.y+=delta.y;motion();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0','Enter'].includes(e.key))return;e.preventDefault();e.stopPropagation();if(['+','='].includes(e.key))zoomAt(1.2);else if(e.key==='-')zoomAt(.8);else if(e.key==='0'){focused=false;fit();draw();}else if(e.key==='Enter'){if(selected)showInspector();else if(model?.nodes.length)choose(model.nodes[0].id);}else{target.x+=e.key==='ArrowLeft'?35:e.key==='ArrowRight'?-35:0;target.y+=e.key==='ArrowUp'?35:e.key==='ArrowDown'?-35:0;motion();}});
  unsubscribe=N.subscribe(()=>{if(!alive||expanding)return;win.clearTimeout(reloadTimer);reloadTimer=win.setTimeout(()=>reload(),500);});reload();return frame;
 }
};
