/* Network-first local research canvas. The worker owns expensive layout; the UI owns navigation. */
var CiteLensNetworkUI={
 open(reader=null,{doc=Zotero.getMainWindow().document,onClose=null}={}){
  const existing=doc.querySelector('.pn-network');if(existing){existing.focus();return existing;}
  const U=CiteLensUI,N=CiteLensNetwork,C=CiteLensCore,NC=CiteLensNetworkCore,V=CiteLensNetworkView,win=doc.defaultView;
  let egoModel=null,egoIndex=null,egoDepth=1,egoTicket=0,egoLimit=600;let viewCommunity='',viewAnchor='',overviewCamera=null;let searchSession=null,searchEpoch=0;let forceRebuild=false,reloadEpoch=0;let alive=true,data,scopeData={libraries:[],collections:[]},model=null,selected='',hover='',mode='topics',focused=false,limit=Number.MAX_SAFE_INTEGER,openEntities=new Set(),building=false,queuedReload=false,controller=null,epoch=0,unsubscribe=()=>{},reloadTimer,searchTimer,raf=0,animation=null,drag=null,history=[],loaded=false;
  const viewCache=new Map();let activeJob=null,warmTimer=0,blankTimer=0;const navigation=[];
  function rememberView(){const view=viewCache.get(activeJob);if(view){view.camera={...camera};view.dimensions={...dimensions};}}
  const dialog=U.dialog(doc,'Paper Nexus',{className:'pn-network pn-map-window',onClose:()=>{alive=false;win.clearTimeout(warmTimer);for(const view of viewCache.values())view.searchSession?.close();viewCache.clear();epoch++;egoTicket++;searchEpoch++;searchSession?.close();unsubscribe();win.clearTimeout(reloadTimer);win.clearTimeout(searchTimer);win.cancelAnimationFrame(raf);win.clearTimeout(settleTimer);resize.disconnect();themeObserver.disconnect();N.views.delete(dialog.close);N.setForeground();win.clearTimeout(blankTimer);onClose?.();}}),{frame,root,footer}=dialog;N.views.add(dialog.close);N.setForeground();root.classList.add('pn-map-body');frame.dataset.paperNexus='network';
  const header=frame.querySelector('.cl-dialog-header');header.insertBefore(U.iconButton(doc,'设置','settings',()=>U.settingsDialog(doc)),header.querySelector('.cl-dismiss'));
  const bar=U.el(doc,'div',null,'pn-map-controls'),library=U.el(doc,'select'),collection=U.el(doc,'select'),searchWrap=U.el(doc,'div',null,'pn-map-search'),search=U.el(doc,'input'),suggestions=U.el(doc,'div',null,'pn-search-results'),views=U.el(doc,'div',null,'pn-map-views');
  library.setAttribute('aria-label','文献库');collection.setAttribute('aria-label','文献夹');search.type='search';search.placeholder='定位文献或作者';search.setAttribute('aria-label','定位文献或作者');search.setAttribute('role','combobox');search.setAttribute('aria-autocomplete','list');search.setAttribute('aria-expanded','false');suggestions.hidden=true;suggestions.id='pn-search-'+(++U.sequence);suggestions.setAttribute('role','listbox');search.setAttribute('aria-controls',suggestions.id);searchWrap.append(search,suggestions);
  const option=(el,value,label)=>{const o=U.el(doc,'option',label);o.value=value;el.append(o);};option(library,'','全部文献库');option(collection,'','所有文献夹');
  for(const [value,label] of [['authors','作者'],['topics','主题']]){const b=U.iconButton(doc,label,value,()=>{if(mode===value)return;rememberView();mode=value;navigation.length=0;egoModel=null;egoIndex=null;egoTicket++;depthTools.hidden=true;viewCommunity='';viewAnchor='';overviewCamera=null;selected='';hover='';history=[];openEntities.clear();focused=false;for(const child of views.children)child.setAttribute('aria-pressed',String(child===b));build(true);});b.dataset.groupMode=value;b.setAttribute('aria-pressed',String(mode===value));views.append(b);}views.setAttribute('aria-label','聚类方式');
  bar.append(library,collection,searchWrap);
  const clearSearch=U.iconButton(doc,'清除搜索','clear',()=>{search.value='';searchEpoch++;win.clearTimeout(searchTimer);showSearch();search.focus();});clearSearch.classList.add('pn-search-clear');clearSearch.disabled=true;clearSearch.removeAttribute('title');clearSearch.addEventListener('pointerdown',e=>e.preventDefault());searchWrap.append(clearSearch);
  const status=U.el(doc,'div','','cl-status'),workspace=U.el(doc,'div',null,'pn-map-workspace'),stage=U.el(doc,'div',null,'pn-map-stage'),canvas=U.el(doc,'canvas',null,'pn-map-canvas'),inspector=U.el(doc,'aside',null,'pn-map-inspector'),loader=U.el(doc,'div',null,'pn-map-loading'),cancel=U.quiet(doc,'取消',()=>{egoTicket++;controller?.abort();building=false;queuedReload=false;epoch++;reloadEpoch++;loader.hidden=true;stage.setAttribute('aria-busy','false');U.status(status,'已取消，现有网络保留');});
  const steps=U.el(doc,'div',null,'pn-progress-steps');let stepRows=[];
  const stepLabels={metadata:'读取文献',encoding:'计算语义',neighbors:'关联论文',naming:'提炼主题',hierarchy:'聚合主题',authors:'关联作者',layout:'排列网络',model:'准备模型',relations:'读取合作关系'};
  const networkSteps=(value=mode)=>value==='topics'?['metadata','model','encoding','neighbors','naming','hierarchy','layout']:['metadata','authors','layout'];
  function setSteps(keys){steps.replaceChildren();stepRows=keys.map(key=>{const row=U.quiet(doc,'',()=>U.status(status,'正在进行中，请稍后'));row.classList.add('pn-progress-step','pn-progress-detail');row.dataset.step=key;row.dataset.state='pending';const mark=U.el(doc,'span','○','pn-step-mark'),label=U.el(doc,'span',stepLabels[key]),bar=U.el(doc,'progress'),value=U.el(doc,'span','','pn-step-value');bar.max=100;bar.value=0;bar.setAttribute('aria-label',stepLabels[key]);row.append(mark,label,bar,value);steps.append(row);return{key,row,mark,bar,value};});}
  function stepProgress(key,ratio=0){const index=stepRows.findIndex(x=>x.key===key);if(index<0)return;for(let i=0;i<stepRows.length;i++){const entry=stepRows[i];if(i<index){entry.row.dataset.state='complete';entry.mark.textContent='✓';entry.value.textContent='';entry.bar.value=100;}else if(i===index){const complete=ratio>=1;entry.row.dataset.state=complete?'complete':'active';entry.mark.textContent=complete?'✓':'◌';entry.bar.value=Math.max(0,Math.min(100,Math.round(ratio*100)));entry.value.textContent=complete?'':entry.bar.value+'%';}else{entry.row.dataset.state='pending';entry.mark.textContent='○';entry.value.textContent='';entry.bar.value=0;}}}
  function finishSteps(failed=''){for(const entry of stepRows){entry.row.dataset.state=entry.key===failed?'error':'complete';entry.mark.textContent=entry.key===failed?'!':'✓';entry.value.textContent='';entry.bar.value=entry.key===failed?0:100;}}
  setSteps(networkSteps());stepProgress('metadata');frame._pnProgress={set:setSteps,update:stepProgress};
  canvas.tabIndex=0;canvas.setAttribute('role','application');canvas.setAttribute('aria-label','本地文献网络；可搜索定位，方向键平移，加减号缩放，Enter 查看当前节点');inspector.hidden=true;const progressTitle=U.el(doc,'div','','pn-progress-title');loader.append(progressTitle,steps,cancel);loader.setAttribute('role','status');const modeTools=U.el(doc,'div',null,'pn-map-mode-tools');modeTools.setAttribute('role','toolbar');modeTools.setAttribute('aria-label','网络视图');modeTools.append(views);stage.append(canvas,modeTools,loader);workspace.append(stage,inspector);root.append(bar,workspace);
  const tools=U.el(doc,'div',null,'pn-map-tools'),fitButton=U.iconButton(doc,'适应当前视图','fit',()=>{fit();draw();}),focusButton=U.iconButton(doc,'聚焦关联','focus',()=>{if(selected){focused=true;fit();draw();}});focusButton.disabled=true;
  const backCommunity=U.iconButton(doc,'返回上一级','back',()=>goBack());backCommunity.hidden=true;
  const depthTools=U.el(doc,'div',null,'pn-ego-depth');depthTools.hidden=true;for(const depth of [1,2]){const b=U.quiet(doc,depth===1?'一级':'二级',()=>openAuthorEgo(egoModel?.selected||selected,depth));b.dataset.egoDepth=String(depth);b.setAttribute('aria-pressed',String(depth===1));depthTools.append(b);}tools.append(depthTools);
  tools.append(U.iconButton(doc,'放大','plus',()=>zoomAt(1.25)),U.iconButton(doc,'缩小','minus',()=>zoomAt(.8)),fitButton);stage.append(tools);
  const count=U.el(doc,'span','','pn-map-count'),more=U.quiet(doc,'再载入 240 篇',()=>{if(egoModel){egoLimit+=600;openAuthorEgo(egoModel.selected,egoDepth);}else{limit+=240;build(false);}});more.hidden=true;const installModel=U.quiet(doc,'安装模型',()=>U.settingsDialog(doc));installModel.hidden=true;installModel.dataset.installModel='true';status.classList.add('pn-map-status');status.setAttribute('role','status');const retry=U.quiet(doc,'重试',()=>{retry.hidden=true;forceRebuild=true;N.clearGraphJobs(mode);reload();});retry.hidden=true;retry.dataset.networkRetry='true';stage.append(count);footer.append(status,retry,installModel,more);
  const camera={x:0,y:0,k:1},target={...camera};let dimensions={w:800,h:500},palette=[],ink='',muted='',paper='',accent='',font='sans-serif',index=null,scene=null,sceneKey='',themeDirty=true,movingUntil=0,settleTimer=0,lastFrame=0,pointer=null,morph=null;
  const magnet=new Map(),nodeOpacity=new Map(),edgeOpacity=new Map();let feedbackPending=false,labelHits=[];
  const reduced=win.matchMedia('(prefers-reduced-motion: reduce)');
  const related=id=>index?.detail?.id===id?index.detail.near:index?.adj.get(id)||new Set([id]);
  const visible=()=>!model?[]:V.scene(egoModel||model,egoIndex||index,{selected,focused,k:camera.k,community:egoModel?'':viewCommunity}).nodes;
  const sync=()=>Object.assign(target,camera);
  const motion=()=>{movingUntil=win.performance.now()+100;win.clearTimeout(settleTimer);settleTimer=win.setTimeout(draw,110);draw();};
  const fit=(animated=true)=>{const nodes=visible();if(!nodes.length)return;const xs=nodes.map(n=>n.x),ys=nodes.map(n=>n.y),left=Math.min(...xs)-55,right=Math.max(...xs)+55,top=Math.min(...ys)-55,bottom=Math.max(...ys)+55,k=Math.min(2.2,Math.max(.08,Math.min((dimensions.w-55)/(right-left),(dimensions.h-90)/(bottom-top))));Object.assign(target,{k,x:dimensions.w/2-(left+right)/2*k,y:(dimensions.h-25)/2-(top+bottom)/2*k});if(!animated||reduced.matches)Object.assign(camera,target);motion();};
  const center=node=>{target.x=dimensions.w/2-node.x*target.k;target.y=dimensions.h/2-node.y*target.k;motion();};
  const zoomAt=(factor,x=dimensions.w/2,y=dimensions.h/2)=>{Object.assign(target,V.zoom(target,factor,x,y));motion();};
  const size=()=>{const r=stage.getBoundingClientRect();if(r.width<1||r.height<1)return;const old=dimensions;dimensions={w:r.width,h:r.height};const dpr=Math.min(2,win.devicePixelRatio||1),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;camera.x+=(r.width-old.w)/2;camera.y+=(r.height-old.h)/2;target.x+=(r.width-old.w)/2;target.y+=(r.height-old.h)/2;draw();};
  const resize=new win.ResizeObserver(size);resize.observe(stage);const themeObserver=new win.MutationObserver(()=>{themeDirty=true;draw();});themeObserver.observe(doc.documentElement,{attributes:true,attributeFilter:['style','data-cl-theme']});
  function draw(){if(raf||!alive)return;raf=win.requestAnimationFrame(paint);}
  function paint(now){raf=0;if(!alive)return;const started=win.performance.now(),dt=lastFrame?now-lastFrame:16,pending=V.step(camera,target,dt,reduced.matches);lastFrame=now;feedbackPending=false;
   if(morph){const t=Math.min(1,(now-morph.start)/380),ease=1-Math.pow(1-t,3);for(const p of morph.points){p.node.x=p.x+(p.tx-p.x)*ease;p.node.y=p.y+(p.ty-p.y)*ease;}if(t===1)morph=null;}
   if(themeDirty){const css=win.getComputedStyle(frame);ink=css.getPropertyValue('--cl-ink').trim();muted=css.getPropertyValue('--cl-muted').trim();paper=css.getPropertyValue('--cl-bg').trim();accent=css.getPropertyValue('--cl-accent').trim();font=css.getPropertyValue('--cl-reading-font')||'sans-serif';const dark=['midnight','botanical','aurora','velvet'].includes(CiteLensThemes.resolve(CiteLensServices.state.settings.theme).id);palette=dark?['#98cbbc','#c4b6e6','#e2bd8a','#87bddf','#d7a5b1','#abc99e','#889ca4']:['#377c73','#846ab0','#ab7b34','#367ca5','#a36578','#6b8348','#8798a5'];themeDirty=false;}
   const ctx=canvas.getContext('2d'),dpr=canvas.width/dimensions.w;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,dimensions.w,dimensions.h);if(!model)return;
   const key=(egoModel?'ego:'+egoModel.selected+':'+egoDepth:viewCommunity)+'|'+selected+'|'+focused+'|'+(camera.k<.9)+'|'+(model.matches||[]).join(',');if(key!==sceneKey||!scene){scene=V.scene(egoModel||model,egoIndex||index,{selected,focused,k:camera.k,community:egoModel?'':viewCommunity});sceneKey=key;}
   const moving=pending||!!morph||now<movingUntil||!!drag?.moved;
   if(!drag&&!moving){const id=hitPoint(pointer)?.id||'';if(id!==hover){hover=id;canvas.style.cursor=id?'pointer':'grab';}}
   const visualIndex=scene.index||egoIndex||index,emphasis=V.emphasis({...model,matches:scene.matches||model.matches,searchGroups:mode==='topics'&&!viewCommunity},visualIndex,{selected:egoModel?egoModel.selected:selected,hover}),near=emphasis.near,matches=new Set(scene.matches||model.matches||[]),targets=new Map();
   if(pointer&&hover&&!drag&&!moving&&!reduced.matches){const n=visualIndex.byID.get(hover);if(n){const dx=pointer.x-(n.x*camera.k+camera.x),dy=pointer.y-(n.y*camera.k+camera.y),scale=Math.min(.24,9/Math.max(1,Math.hypot(dx,dy))),offset={x:dx*scale,y:dy*scale};targets.set(n.id,offset);let count=0;for(const id of visualIndex.adj.get(n.id)||[]){if(id===n.id)continue;if(++count>10)break;targets.set(id,{x:offset.x*.2,y:offset.y*.2});}}}
   feedbackPending=V.magnetic(magnet,targets,dt,reduced.matches);
   const screen=n=>({x:n.x*camera.k+camera.x+(magnet.get(n.id)?.x||0),y:n.y*camera.k+camera.y+(magnet.get(n.id)?.y||0)});
   let edgesDrawn=0;const citationBundles=new Set();ctx.lineCap='round';
   for(const e of scene.edges){const active=emphasis.roots.has(e.source)||emphasis.roots.has(e.target);if(scene.aggregate&&!focused&&e.kind==='cites'){const a=(scene.index||egoIndex||index).byID.get(e.source),b=(scene.index||egoIndex||index).byID.get(e.target),key=a.community+'|'+b.community;if(citationBundles.has(key))continue;citationBundles.add(key);}
    if(!active&&edgesDrawn>=360)continue;
    const a=screen((scene.index||egoIndex||index).byID.get(e.source)),b=screen((scene.index||egoIndex||index).byID.get(e.target));if(Math.max(a.x,b.x)<0||Math.min(a.x,b.x)>dimensions.w||Math.max(a.y,b.y)<0||Math.min(a.y,b.y)>dimensions.h)continue;
    const edgeKey=e.source+'|'+e.target,edgeTarget=active?.42:near?.08:e.kind==='cites'?.18:e.kind==='similarity'?.12:.15,edgeAlpha=V.opacity(edgeOpacity.get(edgeKey)??edgeTarget,edgeTarget,dt,reduced.matches);edgeOpacity.set(edgeKey,edgeAlpha);if(edgeAlpha!==edgeTarget)feedbackPending=true;ctx.globalAlpha=edgeAlpha;ctx.strokeStyle=active?accent:muted;ctx.lineWidth=V.lineWidth(e.count,active);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();edgesDrawn++;
    if(e.kinds.includes('cites')&&active&&!moving)for(const direction of e.directions){const from=direction==='forward'?a:b,to=direction==='forward'?b:a,angle=Math.atan2(to.y-from.y,to.x-from.x),x=to.x-Math.cos(angle)*9,y=to.y-Math.sin(angle)*9;ctx.beginPath();ctx.moveTo(x-Math.cos(angle-.4)*5,y-Math.sin(angle-.4)*5);ctx.lineTo(x,y);ctx.lineTo(x-Math.cos(angle+.4)*5,y-Math.sin(angle+.4)*5);ctx.stroke();}
   }
   const candidates=[];let nodesDrawn=0;


   for(const n of scene.nodes){const p=screen(n);if(p.x< -80||p.x>dimensions.w+80||p.y< -35||p.y>dimensions.h+35)continue;const picked=n.id===selected||n.id===hover,matched=matches.has(n.id),active=!near||near.has(n.id),hub=n.kind!=='paper',r=Math.max(2.4,Math.min(8,(3+Math.log2(1+(n.degree||0))*.6)*Math.sqrt(camera.k)));
    if(picked||matched){ctx.globalAlpha=.12;ctx.fillStyle=accent;ctx.beginPath();ctx.arc(p.x,p.y,r+7,0,Math.PI*2);ctx.fill();}
    const alphaTarget=active?(egoModel&&n.depth===2?.72:1):.32,alpha=V.opacity(nodeOpacity.get(n.id)??1,alphaTarget,dt,reduced.matches);nodeOpacity.set(n.id,alpha);if(alpha!==alphaTarget)feedbackPending=true;ctx.globalAlpha=alpha;ctx.fillStyle=picked?accent:palette[n.color];ctx.strokeStyle=palette[n.color];ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(p.x,p.y,r+(picked?1:0),0,Math.PI*2);ctx.fill();nodesDrawn++;
    if(moving&&!picked&&!matched)continue;if(!picked&&!matched&&!hub&&camera.k<.75)continue;
    const label=V.nodeLabel(n,mode,picked?76:52),count='',size=n.id===selected?15:picked?13:11;
    ctx.font=(picked?'600 ':'500 ')+size+'px '+font;const width=ctx.measureText(label+count).width;
    candidates.push({id:n.id,priority:(picked?10000:matched?5000:hub?100:0)+(active?50:0)+(n.members?.length||0),rect:{x:p.x-width/2-3,y:p.y+r+4,w:width+6,h:19},p,r,label,count,size,picked,alpha:active?1:Math.max(.34,alpha)});
   }
   for(const c of candidates)if(c.id===hover){const prior=labelHits.find(r=>r.id===c.id);if(prior)c.preferred=[prior.x-c.rect.x,prior.y-c.rect.y];}const labels=V.labels(candidates,dimensions.w,dimensions.h);ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.lineJoin='round';
   labelHits=labels.map(c=>({id:c.id,x:c.rect.x+(c.dx||0),y:c.rect.y+(c.dy||0),w:c.rect.w,h:c.rect.h}));frame._pnLabels=labelHits;for(const c of labels){ctx.globalAlpha=c.alpha;ctx.font=(c.picked||c.group?'600 ':'500 ')+c.size+'px '+font;ctx.strokeStyle=paper;ctx.lineWidth=4;ctx.strokeText(c.label+c.count,c.p.x+(c.dx||0),c.p.y+c.r+17+(c.dy||0));ctx.fillStyle=c.picked?accent:c.group?muted:ink;ctx.fillText(c.label+c.count,c.p.x+(c.dx||0),c.p.y+c.r+17+(c.dy||0));}
   ctx.globalAlpha=1;frame._pnScene={aggregate:scene.aggregate,nodes:nodesDrawn,edges:edgesDrawn,labels:labels.length,emphasized:near?.size??nodesDrawn,searchActive:emphasis.searching,matched:matches.size,moving,paintMS:win.performance.now()-started};frame._pnMotion={hover,offsets:[...magnet].map(([id,p])=>({id,x:p.x,y:p.y})),pending:feedbackPending};if(pending||morph||feedbackPending)draw();
  }
  function hitPoint(p){if(!p)return null;const label=labelHits.find(r=>p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h);return (label&&scene?.nodes.find(n=>n.id===label.id))||V.nearest(scene?.nodes||[],p,camera,hover);}
  function hit(e){const r=canvas.getBoundingClientRect();return hitPoint({x:e.clientX-r.left,y:e.clientY-r.top});}
  async function showSearch(){
   const ticket=++searchEpoch,query=search.value.trim();clearSearch.disabled=!search.value;suggestions.replaceChildren();if(model){model.searchActive=!!query;model.matches=[];sceneKey='';}
   if(!query&&(egoModel||viewCommunity||selected)){goBack(true);showInspector();}if(model)draw();
   if(!query||!data){suggestions.hidden=true;search.setAttribute('aria-expanded','false');return;}
   if(!searchSession){suggestions.hidden=false;suggestions.append(U.el(doc,'span','正在进行中，请稍后'));return;}
   try{const found=await searchSession.query(query);if(!alive||ticket!==searchEpoch||search.value.trim()!==query)return;
    suggestions.replaceChildren();for(const n of found.results){const b=U.button(doc,n.title+(n.year?' · '+n.year:''),async()=>{suggestions.hidden=true;search.setAttribute('aria-expanded','false');await choose(n.id);const target=(egoModel||model)?.nodes.find(x=>x.id===n.id);if(target)center(target);});b.setAttribute('role','option');suggestions.append(b);}
    if(!found.results.length)suggestions.append(U.el(doc,'span','没有匹配结果'));suggestions.hidden=false;search.setAttribute('aria-expanded','true');if(model){model.matches=found.matches;model.searchActive=true;sceneKey='';draw();}
   }catch(e){if(alive&&ticket===searchEpoch&&e.message!=='已取消')U.status(status,e.message,true);}
  }
  const record=node=>({...node,author:node.author||node.creators?.[0]?.lastName||'',authors:node.creators});
  const path=node=>(node.collections||[]).map(id=>{const names=[],seen=new Set();let c=data.collections.find(c=>c.id===id);while(c&&!seen.has(c.id)){seen.add(c.id);names.unshift(c.name);c=data.collections.find(x=>x.id===c.parentID);}return names.join(' › ');}).filter(Boolean).join(' · ');
  function rememberNavigation(){if(!model)return;navigation.push({activeJob,searchSession,model,index,egoModel,egoIndex,egoDepth,viewCommunity,viewAnchor,selected,focused,openEntities:new Set(openEntities),camera:{...camera}});if(navigation.length>30)navigation.splice(1,1);}
  function goBack(all=false){
   const saved=all?navigation[0]:navigation.pop();if(all)navigation.length=0;
   if(!saved){leaveCommunity();return;}egoTicket++;Object.assign(camera,saved.camera);sync();({activeJob,searchSession,model,index,egoModel,egoIndex,egoDepth,viewCommunity,viewAnchor,selected,focused}=saved);openEntities=new Set(saved.openEntities);if(searchSession?.closed)searchSession=N.searchSession(model);hover='';pointer=null;scene=null;sceneKey='';depthTools.hidden=!egoModel;for(const b of depthTools.children)b.setAttribute('aria-pressed',String(Number(b.dataset.egoDepth)===egoDepth));frame._pnModel=model;frame._pnCommunity=viewCommunity;frame._pnEgo=egoModel?{id:egoModel.selected,depth:egoDepth}:null;showInspector();size();fit();draw();
  }
  frame._pnBack=goBack;
  function enterCommunity(id,anchor=''){
   const group=model?.communities.find(g=>g.id===id);if(!group)return;egoModel=null;egoIndex=null;egoTicket++;depthTools.hidden=true;if(!viewCommunity)overviewCamera={...camera};viewCommunity=id;viewAnchor=anchor||group.members.find(id=>index.byID.get(id)?.kind!=='paper')||group.members[0];selected='';hover='';focused=false;backCommunity.hidden=false;inspector.hidden=true;focusButton.disabled=true;scene=null;sceneKey='';frame._pnCommunity=id;size();fit();draw();
  }
  function leaveCommunity(){egoModel=null;egoIndex=null;egoTicket++;frame._pnEgo=null;depthTools.hidden=true;more.hidden=!model?.stats.hidden;more.textContent='再载入 240 篇';if(!building){loader.hidden=true;U.status(status,'');}viewCommunity='';viewAnchor='';selected='';hover='';focused=false;backCommunity.hidden=true;inspector.hidden=true;focusButton.disabled=true;scene=null;sceneKey='';frame._pnCommunity='';size();overviewCamera=null;fit();draw();}
  frame.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.defaultPrevented&&(viewCommunity||egoModel)){e.preventDefault();e.stopPropagation();goBack();}});
  frame._pnEnterCommunity=enterCommunity;frame._pnBackCommunity=leaveCommunity;frame._pnOpenAuthor=openAuthorEgo;
  async function openAuthorEgo(id,depth=1){
   if(!id||!searchSession)return;const ticket=++egoTicket;if(!viewCommunity&&!egoModel)overviewCamera={...camera};loader.hidden=false;loader.classList.add('pn-inline-loading');setSteps(['relations']);stepProgress('relations');
   try{const graph=await searchSession.neighborhood(id,depth,egoLimit);if(!alive||ticket!==egoTicket)return;egoModel=graph;egoIndex=V.index(graph);egoDepth=depth;viewCommunity='';selected=id;hover='';focused=false;backCommunity.hidden=false;depthTools.hidden=false;for(const b of depthTools.children)b.setAttribute('aria-pressed',String(Number(b.dataset.egoDepth)===depth));scene=null;sceneKey='';frame._pnEgo={id,depth,nodes:graph.nodes.length,available:graph.stats.available};size();
    const root=egoIndex.byID.get(id),radius=Math.max(80,...graph.nodes.map(n=>Math.max(Math.abs(n.x-root.x),Math.abs(n.y-root.y)))),k=Math.min(1.8,Math.max(.06,Math.min(dimensions.w-80,dimensions.h-90)/(2*radius)));Object.assign(target,{k,x:dimensions.w/2-root.x*k,y:(dimensions.h-30)/2-root.y*k});motion();more.hidden=graph.nodes.length>=graph.stats.available;more.textContent='展开更多';U.status(status,more.hidden?'':graph.nodes.length+' / '+graph.stats.available+' 位合作作者');draw();
   }catch(e){if(alive&&ticket===egoTicket&&e.message!=='已取消')U.status(status,e.message,true);}finally{if(alive&&ticket===egoTicket)loader.hidden=true;}
  }
  async function choose(id){suggestions.hidden=true;search.setAttribute('aria-expanded','false');if(selected!==id)rememberNavigation();if(id.startsWith('community:')){enterCommunity(id);return;}const location=model?.nodes.find(n=>n.id===id)||model?.nodes.find(n=>n.members?.includes(id));if(mode!=='authors'&&location?.community&&location.community!==viewCommunity)enterCommunity(location.community,location.id);if(mode==='topics'&&!loader.hidden&&!model?.semantic){U.status(status,'正在进行中，请稍后');return;}if(selected&&selected!==id)history.push(selected);selected=data?.aliases?.get(id)||id;const owner=model?.nodes.find(n=>n.members?.includes(selected));if(owner&&!model.nodes.some(n=>n.id===selected))openEntities.add(owner.id);focusButton.disabled=false;focused=false;focusButton.setAttribute('aria-pressed','false');if(!model?.nodes.some(n=>n.id===selected)){await build(false,true);if(!alive)return;}const entity=model?.nodes.find(n=>n.id===selected);if(entity?.kind==='author'&&searchSession){try{const edges=await searchSession.relations(entity.id);if(!alive||selected!==entity.id||!index.byID.has(entity.id))return;V.scene(model,index);V.detail(index,entity.id,edges);await openAuthorEgo(entity.id,egoDepth);scene=null;sceneKey='';}catch(e){if(e.message!=='已取消')U.status(status,e.message,true);}}else if(index)index.detail=null;if(entity?.kind==='topic'&&!openEntities.has(entity.id)){openEntities.add(entity.id);await build(false,true);}showInspector();size();const focusNode=(egoModel||model)?.nodes.find(n=>n.id===selected);if(focusNode)center(focusNode);draw();}
  function paperButton(paper){const row=U.quiet(doc,'',()=>choose(paper.id));row.classList.add('pn-member-paper');row.append(U.el(doc,'span',paper.title,'pn-member-title'));const meta=C.publicationLine(paper);if(meta)row.append(U.el(doc,'span',meta,'pn-member-meta'));return row;}
  function showInspector(){inspector.replaceChildren();const n=model?.nodes.find(n=>n.id===selected);if(!n){inspector.hidden=true;focusButton.disabled=true;return;}inspector.hidden=false;
   const top=U.el(doc,'div',null,'pn-inspector-tools'),back=U.iconButton(doc,'返回上一级','back',()=>goBack());back.disabled=!navigation.length;const close=U.iconButton(doc,'关闭节点详情','clear',()=>{inspector.hidden=true;size();draw();});top.append(back,close);inspector.append(top,U.title(doc,n,'h3'));
   if(n.kind==='paper'){
    inspector.append(U.el(doc,'div',C.publicationLine(n),'pn-node-meta'));if(n.creators?.length){const authors=U.el(doc,'div',null,'pn-authorline'),track=U.el(doc,'span',n.creators.map(a=>a.name||[a.firstName,a.lastName].filter(Boolean).join(' ')).join('; '),'pn-author-track'),full=U.el(doc,'div',null,'pn-author-full');authors.tabIndex=0;authors.setAttribute('aria-label','完整作者列表');authors.setAttribute('aria-expanded','false');const expandAuthors=()=>{authors.dataset.expanded='true';authors.setAttribute('aria-expanded','true');},collapseAuthors=()=>{delete authors.dataset.expanded;authors.setAttribute('aria-expanded','false');};authors.addEventListener('pointerenter',expandAuthors);authors.addEventListener('pointerleave',()=>{if(!authors.contains(doc.activeElement))collapseAuthors();});authors.addEventListener('focusin',expandAuthors);authors.addEventListener('focusout',e=>{if(!authors.contains(e.relatedTarget))collapseAuthors();});for(const a of n.creators){const name=a.name||[a.firstName,a.lastName].filter(Boolean).join(' '),row=U.el(doc,'p',name),details=[a.ORCID||a.orcid,...(a.affiliations||[]),a.affiliation].filter(Boolean);if(details.length)row.append(U.el(doc,'small',details.join('; ')));full.append(row);}const viewport=U.el(doc,'span',null,'pn-author-viewport');viewport.append(track);authors.append(viewport,full);inspector.append(authors);win.requestAnimationFrame(()=>{if(!authors.isConnected)return;const distance=track.scrollWidth-authors.clientWidth;if(distance>0){authors.style.setProperty('--pn-author-distance',-distance+'px');authors.style.setProperty('--pn-author-duration',Math.max(12,distance/18)+'s');authors.classList.add('pn-author-overflow');}});}
    const actions=U.el(doc,'div',null,'cl-actions');if(n.local){actions.append(U.iconButton(doc,'打开条目','folder',async()=>{await N.openItem(n);dialog.close();}));if(n.attachments?.length)actions.append(U.iconButton(doc,'阅读全文','references',async()=>{await N.openPDF(n);dialog.close();}));}
    actions.append(U.iconButton(doc,U.queued(record(n))?'已在清单':'稍后读',U.queued(record(n))?'bookmarked':'bookmark',async b=>{await CiteLensServices.enqueue(record(n),null);U.setButtonLabel(b,'已在清单','bookmarked');}));if(C.recordDOI(n))actions.append(U.iconButton(doc,'打开 DOI','doi',()=>Zotero.launchURL('https://doi.org/'+C.recordDOI(n))));inspector.append(actions);
    if(n.copies?.length>1){const copies=U.el(doc,'details',null,'pn-copies');copies.append(U.el(doc,'summary',n.copies.length+' 个副本'));for(const c of n.copies)copies.append(U.quiet(doc,path(c)||'文献库中的条目',async()=>{await N.openItem(c);dialog.close();}));inspector.append(copies);}
    renderAbstract(n,actions);
   }else{
    const members=n.members.map(id=>model.paperNodes.find(p=>p.id===id)).filter(Boolean),section=U.el(doc,'section',null,'pn-node-connections');section.append(U.el(doc,'h4',members.length+' 篇论文'));
    const toggle=U.quiet(doc,openEntities.has(n.id)?'收起论文':'展开论文',async()=>{openEntities.has(n.id)?openEntities.delete(n.id):openEntities.add(n.id);await build(false,true);});section.append(toggle);
    let shown=0;const more=U.quiet(doc,'更多论文',()=>append());const append=()=>{for(const paper of members.slice(shown,shown+16)){const row=paperButton(paper);section.insertBefore(row,more);}shown+=16;more.hidden=shown>=members.length;};section.append(more);append();inspector.append(section);
   }
   const sections=[['coauthor','合作作者'],['topic-relation','关联主题'],['cites-out','引用文献'],['cites-in','引用它的文献'],['author','共同作者的文献'],['topic','主题与论文'],['similarity','主题相近的文献'],['related','已有相关条目'],['reference-group','参考文献']];
   const incident=index.detail?.id===n.id?index.detail.relations:index.links.get(n.id)||[];
   for(const [key,label] of sections){const relations=incident.filter(e=>key==='cites-out'?e.kind==='cites'&&e.source===n.id:key==='cites-in'?e.kind==='cites'&&e.target===n.id:e.kind===key);if(!relations.length)continue;const section=U.el(doc,'section',null,'pn-node-connections');section.append(U.el(doc,'h4',label+' · '+relations.length));let shown=0;
    const more=U.quiet(doc,'更多关联',()=>append());more.classList.add('pn-relations-more');
    const append=()=>{const fragment=doc.createDocumentFragment();for(const e of relations.slice(shown,shown+16)){const target=index.byID.get(e.source===n.id?e.target:e.source);if(!target)continue;const row=U.el(doc,'div',null,'pn-node-link'),title=target.kind==='paper'?paperButton(target):U.quiet(doc,target.title,()=>choose(target.id));title.dataset.clData='true';row.append(title);if(['coauthor','topic-relation'].includes(e.kind)){const proof=U.quiet(doc,String(new Set((e.evidence||[]).map(x=>x.paperID||[x.sourcePaper,x.targetPaper].sort().join('|'))).size),()=>{const ids=[...new Set((e.evidence||[]).flatMap(x=>x.paperID?[x.paperID]:[x.sourcePaper,x.targetPaper]))];const list=U.el(doc,'div',null,'pn-link-evidence');for(const id of ids){const p=model.paperNodes.find(n=>n.id===id);if(p)list.append(paperButton(p));}row.after(list);proof.disabled=true;});proof.setAttribute('aria-label','查看关联论文');row.append(proof);}if(e.kind==='cites'&&e.evidence?.[0]?.attachmentID){const source=data.byID.get(e.source),proof=U.iconButton(doc,'打开引用来源','locate',async()=>{await N.openPDF(source,e.evidence[0]);dialog.close();});row.append(proof);}fragment.append(row);}shown+=16;section.insertBefore(fragment,more);more.hidden=shown>=relations.length;};
    section.append(more);append();inspector.append(section);
   }
   size();
  }
  function renderAbstract(n,actions){
   const modes=U.el(doc,'div',null,'cl-summary-modes'),abs=U.el(doc,'div',null,'pn-node-abstract'),state=U.el(doc,'span','','pn-translation-status');let ticket=0;
   const raw=C.abstractBody(n.abstractMarkup||n.abstract||'',n),text=raw.replace(/<\/?(?:p|div|section|h[1-6])[^>]*>|<br\s*\/?\s*>/gi,'\n\n');
   const plain=text.split(/\n+/).map(p=>C.plainTitle(p)).filter(Boolean).join('\n\n');
   const render=value=>{abs.replaceChildren();for(const part of value.split(/\n\s*\n/).filter(Boolean)){const p=U.el(doc,'p');for(const token of C.titleParts(part)){let child=doc.createTextNode(token.text);for(const style of token.styles){const el=U.el(doc,style);el.append(child);child=el;}p.append(child);}abs.append(p);}};
   const select=async mode=>{const id=++ticket,current=()=>alive&&abs.isConnected&&selected===n.id&&id===ticket;for(const b of modes.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));state.textContent='';if(mode==='original'){render(text||'本地暂无摘要');return;}state.textContent='正在翻译';
    const show=(value,pairs)=>{if(!current())return;if(mode==='bilingual'&&pairs){abs.replaceChildren();for(const pair of pairs){const row=U.el(doc,'div',null,'cl-bilingual-pair');row.append(U.el(doc,'p',pair.original,'cl-original-line'),U.el(doc,'p',pair.translated,'cl-translated-line'));abs.append(row);}}else render(value);};
    try{const result=await CiteLensTranslation.abstract(plain,{paired:mode==='bilingual',cancelled:()=>!current(),onPartial:show});if(current()){show(result.text,result.pairs);state.textContent='';}}catch(e){if(current()){render(text);state.textContent=e.message;for(const b of modes.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.mode==='original'));}}
   };
   for(const [mode,label] of [['original','原文'],['translation','译文'],['bilingual','双语']]){const b=U.iconButton(doc,label,mode==='translation'?'translate':mode,()=>select(mode));b.dataset.mode=mode;b.setAttribute('aria-pressed',String(mode==='original'));b.disabled=!plain;modes.append(b);}actions.classList.add('pn-paper-actions');actions.append(state,modes);inspector.append(abs);render(text||'本地暂无摘要');
  }
  function reportProgress(value){if(typeof value==='number')stepProgress('layout',value/100);else stepProgress(value.phase,value.completed/Math.max(1,value.total));}
  function warmOther(payload,snapshot,ticket){
   win.clearTimeout(warmTimer);warmTimer=win.setTimeout(async()=>{
    if(!alive||ticket!==epoch||snapshot!==data)return;const other=payload.mode==='authors'?'topics':'authors',job=N.graphJob(snapshot,{...payload,mode:other,openEntities:[],selected:'',positions:[]});if(job.value)return;
    const report=value=>{if(alive&&ticket===epoch&&!building){loader.hidden=false;progressTitle.textContent=other==='topics'?'主题分组':'朋友圈';setWarmSteps();reportProgress(value);}};
    let initialized=false;function setWarmSteps(){if(!initialized){setSteps(networkSteps(other));initialized=true;}}
    controller=job.controller;job.listeners.add(report);report(job.progress||{phase:other==='topics'?'model':'authors',completed:0,total:1});frame._pnBackgroundMode=other;
    try{await N.presentation(job);}catch(_){}finally{job.listeners.delete(report);if(alive&&ticket===epoch&&!building){loader.hidden=true;frame._pnBackgroundMode='';}}
   },180);
  }
  async function build(fitAfter=false,background=false,prefix=[]){
   if(!data||!alive)return;win.clearTimeout(warmTimer);rememberView();const ticket=++epoch,requestMode=mode;let job,report,failed=false;
   building=true;retry.hidden=true;installModel.hidden=true;progressTitle.textContent=mode==='topics'?'主题分组':'朋友圈';stage.setAttribute('aria-busy','true');
   if(model&&model.mode!==mode){count.textContent='';model=null;index=null;scene=null;morph=null;egoModel=null;egoIndex=null;egoTicket++;depthTools.hidden=true;viewCommunity='';viewAnchor='';backCommunity.hidden=true;searchEpoch++;searchSession=null;frame._pnModel=null;showInspector();draw();}
   // Yield before collecting payloads so the selected mode and progress can paint.
   loader.hidden=background;if(!background){setSteps([...prefix,...networkSteps()]);stepProgress(mode==='topics'?'model':'authors');}
   const snapshot=data,scoped=N.scope(data,library.value,collection.value),scopedIDs=new Set(scoped.map(n=>n.id));
   const payload={nodes:scoped,edges:data.edges.filter(e=>scopedIDs.has(e.source)&&scopedIDs.has(e.target)),mode:requestMode,cacheKey:library.value+':'+collection.value,openEntities:[...openEntities],limit,query:'',selected:openEntities.size?selected:'',positions:(model?.nodes||[]).map(n=>({id:n.id,x:n.x,y:n.y,pinned:n.pinned}))};
   try{
    job=N.graphJob(snapshot,payload);activeJob=job;controller=job.controller;loader.hidden=background||!!job.value;
    report=value=>{if(alive&&ticket===epoch&&!background)reportProgress(value);};job.listeners.add(report);if(job.progress)report(job.progress);
    let view=viewCache.get(job);
    if(!view){const prepared=await N.presentation(job);view={next:prepared.graph,index:prepared.index,searchSession:null};viewCache.set(job,view);while(viewCache.size>4){const key=viewCache.keys().next().value;viewCache.get(key).searchSession?.close();viewCache.delete(key);}}
    if(!alive||ticket!==epoch)return;
    const previous=index?.byID,oldSelected=previous?.get(selected);model=view.next;magnet.clear();nodeOpacity.clear();edgeOpacity.clear();hover='';pointer=null;model.matches=[];model.searchActive=false;index=view.index;scene=null;sceneKey='';
    if(!view.searchSession)view.searchSession=N.searchSession(model);searchSession=view.searchSession;
    if(viewAnchor){viewCommunity=model.nodes.find(n=>n.id===viewAnchor)?.community||'';frame._pnCommunity=viewCommunity;backCommunity.hidden=!viewCommunity;}
    searchEpoch++;if(egoModel)openAuthorEgo(egoModel.selected,egoDepth);if(search.value.trim())showSearch();
    if(!model.nodes.some(n=>n.id===selected))selected=oldSelected&&C.recordDOI(oldSelected)?model.nodes.find(n=>C.recordDOI(n)===C.recordDOI(oldSelected))?.id||'':'';
    frame._pnModel=model;frame._pnSelect=choose;frame._pnBuild=build;frame._pnCamera=camera;frame._pnJob=job;showInspector();size();
    if(view.camera){Object.assign(camera,view.camera);camera.x+=(dimensions.w-view.dimensions.w)/2;camera.y+=(dimensions.h-view.dimensions.h)/2;sync();}else if(fitAfter)fit(false);
    if(!background&&previous&&previous!==index.byID&&!reduced.matches){morph={start:win.performance.now(),points:model.nodes.filter(n=>previous.has(n.id)&&!n.pinned).map(node=>({node,x:previous.get(node.id).x,y:previous.get(node.id).y,tx:node.x,ty:node.y}))};for(const p of morph.points){p.node.x=p.x;p.node.y=p.y;}}
    count.textContent=model.stats.local+' / '+model.stats.total+' 篇本地'+(mode==='topics'?' · '+model.stats.topics+' 个主题':' · '+model.stats.authors+' 个署名');more.hidden=!model.stats.hidden;U.status(status,model.nodes.length?'':'当前范围暂无文献，可选择其他文献夹。');draw();if(!background)warmOther(payload,snapshot,ticket);
   }catch(e){failed=true;if(alive&&ticket===epoch&&e.message!=='已取消'){retry.hidden=false;Zotero.logError(e);U.status(status,e.message,true);installModel.hidden=CiteLensModels.installed.has(CiteLensModels.selected());}}
   finally{job?.listeners.delete(report);if(alive&&ticket===epoch){building=false;loader.hidden=true;stage.setAttribute('aria-busy','false');if(queuedReload||!failed&&N.dirty){queuedReload=false;win.clearTimeout(reloadTimer);reloadTimer=win.setTimeout(()=>reload(),100);}}}
  }
  const collections=()=>{collection.replaceChildren();option(collection,'','所有文献夹');for(const c of scopeData.collections.filter(c=>!library.value||c.libraryID===Number(library.value)))option(collection,String(c.id),'　'.repeat(c.level)+c.name);};
  function populateScopes(){
   const currentLibrary=library.dataset.scopesReady?library.value:String(Zotero.Items.get(reader?.itemID)?.libraryID||Zotero.getActiveZoteroPane()?.getSelectedLibraryID()||''),currentCollection=collection.value;
   library.dataset.scopesReady='true';
   scopeData={libraries:Zotero.Libraries.getAll().filter(l=>['user','group'].includes(l.libraryType)).map(l=>({id:l.libraryID,name:l.name})),collections:[]};
   for(const l of scopeData.libraries)for(const c of Zotero.Collections.getByLibrary(l.id,true).filter(c=>!c.deleted))scopeData.collections.push({id:c.id,name:c.name,libraryID:l.id,level:c.level||0});
   library.replaceChildren();option(library,'','全部文献库');for(const l of scopeData.libraries)option(library,String(l.id),l.name);library.value=[...library.options].some(o=>o.value===currentLibrary)?currentLibrary:'';
   collections();collection.value=[...collection.options].some(o=>o.value===currentCollection)?currentCollection:'';
  }
  async function reload(){if(building){queuedReload=true;return;}const reloadTicket=++reloadEpoch;retry.hidden=true;loader.hidden=false;stage.setAttribute('aria-busy','true');loader.classList.toggle('pn-inline-loading',!!model);setSteps(networkSteps());stepProgress('metadata');try{
   populateScopes();const previousData=data;data=await U.waitFor(N.snapshot({progress:p=>{if(alive&&reloadTicket===reloadEpoch)stepProgress('metadata',p.completed/Math.max(1,p.total));}}),win,45000,'文献库仍在读取，请稍后重试');
   if(!alive||reloadTicket!==reloadEpoch)return;if(loaded&&model&&data===previousData&&!forceRebuild){loader.hidden=true;stage.setAttribute('aria-busy','false');return;}
   if(loaded)selected=data.aliases.get(selected)||selected;const initial=!loaded;loaded=true;forceRebuild=false;await build(initial);
  }catch(e){if(alive&&reloadTicket===reloadEpoch){loader.hidden=true;stage.setAttribute('aria-busy','false');retry.hidden=false;Zotero.logError(e);U.status(status,e.message,true);}}}
  library.addEventListener('change',()=>{navigation.length=0;collections();selected='';focused=false;openEntities.clear();if(data)build(true);else reload();});collection.addEventListener('change',()=>{navigation.length=0;selected='';focused=false;openEntities.clear();if(data)build(true);else reload();});search.addEventListener('input',()=>{clearSearch.disabled=!search.value;searchEpoch++;win.clearTimeout(searchTimer);if(!search.value.trim())showSearch();else searchTimer=win.setTimeout(showSearch,90);});search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();suggestions.querySelector('button')?.click();}else if(e.key==='ArrowDown'){e.preventDefault();suggestions.querySelector('button')?.focus();}else if(e.key==='Escape'){e.stopPropagation();suggestions.hidden=true;search.setAttribute('aria-expanded','false');}});suggestions.addEventListener('keydown',e=>{const all=[...suggestions.querySelectorAll('button')],i=all.indexOf(doc.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();all[(i+(e.key==='ArrowDown'?1:all.length-1))%all.length]?.focus();}});root.addEventListener('pointerdown',e=>{if(!searchWrap.contains(e.target)){suggestions.hidden=true;search.setAttribute('aria-expanded','false');}});
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(!loader.hidden&&!model)return;morph=null;sync();canvas.setPointerCapture(e.pointerId);const n=hit(e);drag={n,members:n?.kind==='community'?n.members.map(id=>index.byID.get(id)).filter(Boolean).map(node=>({node,x:node.x,y:node.y})):null,startX:e.clientX,startY:e.clientY,x:camera.x,y:camera.y,nx:n?.x,ny:n?.y,moved:false};});
  canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(drag.n&&drag.moved){drag.n.x=drag.nx+dx/camera.k;drag.n.y=drag.ny+dy/camera.k;drag.n.pinned=true;if(drag.members){for(const p of drag.members){p.node.x=p.x+dx/camera.k;p.node.y=p.y+dy/camera.k;p.node.pinned=true;}const group=model.communities.find(g=>g.id===drag.n.id);if(group){group.x=drag.n.x;group.y=drag.n.y;}}}else if(!drag.n){camera.x=drag.x+dx;camera.y=drag.y+dy;sync();}motion();}else{const r=canvas.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top};draw();}});
  canvas.addEventListener('pointerup',e=>{if(!drag)return;const state=drag;drag=null;canvas.releasePointerCapture(e.pointerId);if(!state.moved&&state.n)choose(state.n.id);else if(!state.moved){win.clearTimeout(blankTimer);blankTimer=win.setTimeout(()=>goBack(),240);}else if(state.n&&!egoModel){const group=model.communities.find(g=>g.id===state.n.community);if(group){const members=group.members.map(id=>index.byID.get(id));group.x=members.reduce((s,n)=>s+n.x,0)/members.length;group.y=members.reduce((s,n)=>s+n.y,0)/members.length;}}draw();});canvas.addEventListener('pointercancel',()=>{drag=null;draw();});canvas.addEventListener('pointerleave',()=>{hover='';pointer=null;draw();});
  canvas.addEventListener('dblclick',e=>{win.clearTimeout(blankTimer);if(!hit(e)){goBack(true);return;}if(mode==='topics'&&!loader.hidden&&!model?.semantic){U.status(status,'正在进行中，请稍后');return;}const n=hit(e);if(n?.kind==='community'){enterCommunity(n.id);}else if(n){selected=n.id;focused=true;showInspector();fit();draw();}});
  canvas.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();if(drag)return;const r=canvas.getBoundingClientRect(),delta=V.wheel(e,dimensions.h);Object.assign(target,V.zoom(target,delta.zoom,e.clientX-r.left,e.clientY-r.top));target.x+=delta.x;target.y+=delta.y;motion();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0','Enter','Escape'].includes(e.key))return;e.preventDefault();e.stopPropagation();if(e.key==='Escape'){goBack();return;}if(['+','='].includes(e.key))zoomAt(1.2);else if(e.key==='-')zoomAt(.8);else if(e.key==='0'){focused=false;fit();draw();}else if(e.key==='Enter'){if(selected)showInspector();else if(model?.nodes.length)choose(model.nodes[0].id);}else{target.x+=e.key==='ArrowLeft'?35:e.key==='ArrowRight'?-35:0;target.y+=e.key==='ArrowUp'?35:e.key==='ArrowDown'?-35:0;motion();}});
  unsubscribe=N.subscribe(reason=>{if(!alive)return;if(reason==='model'){forceRebuild=true;N.clearGraphJobs('topics');}if(building){queuedReload=true;return;}win.clearTimeout(reloadTimer);reloadTimer=win.setTimeout(()=>reload(),500);});reload();return frame;
 }
};
