/* Append-only vector chunks plus an atomically replaced small index. */
var CiteLensVectorStore=class {
 constructor(root,version,dimension=384){this.root=PathUtils.join(root,'semantic-index',version);this.version=version;this.dimension=dimension;this.entries=new Map();this.topics=new Map();this.chain=Promise.resolve();}
 async load(){await IOUtils.makeDirectory(this.root,{ignoreExisting:true});const path=PathUtils.join(this.root,'index.json');try{if(await IOUtils.exists(path)&&(await IOUtils.stat(path)).size<3*1024*1024){const d=JSON.parse(await IOUtils.readUTF8(path));if(d.schema===1&&d.version===this.version&&d.dimension===this.dimension){for(const [key,file,offset] of d.entries||[])if(/^[a-f0-9]{64}$/.test(key)&&/^chunk-[a-z0-9-]+\.bin$/.test(file)&&Number.isInteger(offset)&&offset>=0&&offset<96)this.entries.set(key,{file,offset});this.topics=new Map((d.topics||[]).filter(([k,v])=>typeof k==='string'&&typeof v?.topic==='string'));}}}catch(e){Zotero.logError(e);}return this;}
 async getMany(keys,{signal}={}){const groups=new Map(),out=new Map();for(const key of keys){const r=this.entries.get(key);if(!r)continue;if(!groups.has(r.file))groups.set(r.file,[]);groups.get(r.file).push({key,offset:r.offset});}
  for(const [file,rows] of groups){if(signal?.aborted)throw Error('已取消');try{const path=PathUtils.join(this.root,file);if((await IOUtils.stat(path)).size>96*this.dimension*4)continue;const bytes=await IOUtils.read(path),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(const r of rows){if((r.offset+1)*this.dimension*4>bytes.length)continue;const v=Array.from({length:this.dimension},(_,i)=>view.getFloat32((r.offset*this.dimension+i)*4,true));if(v.every(Number.isFinite))out.set(r.key,v);}}catch(e){Zotero.logError(e);}await Zotero.Promise.delay(0);}return out;
 }
 put(pairs,topics){const copy=[...pairs],names=[...topics];this.chain=this.chain.catch(()=>{}).then(async()=>{const entries=new Map(this.entries);for(let at=0;at<copy.length;at+=96){const batch=copy.slice(at,at+96),name='chunk-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)+'.bin',bytes=new Uint8Array(batch.length*this.dimension*4),view=new DataView(bytes.buffer);batch.forEach(([key,v],j)=>{if(v.length!==this.dimension||!v.every(Number.isFinite))throw Error('无效的本地向量');v.forEach((x,i)=>view.setFloat32((j*this.dimension+i)*4,x,true));});await IOUtils.write(PathUtils.join(this.root,name),bytes);batch.forEach(([key],offset)=>{entries.delete(key);entries.set(key,{file:name,offset});});}
   while(entries.size>12000)entries.delete(entries.keys().next().value);const topics=new Map(names.slice(-12000));const path=PathUtils.join(this.root,'index.json');await IOUtils.writeUTF8(path,JSON.stringify({schema:1,version:this.version,dimension:this.dimension,entries:[...entries].map(([key,r])=>[key,r.file,r.offset]),topics:[...topics]}),{tmpPath:path+'.tmp'});this.entries=entries;this.topics=topics;
   if(copy.length){const used=new Set([...this.entries.values()].map(r=>r.file));for(const path of await IOUtils.getChildren(this.root)){const name=PathUtils.filename(path);if(/^chunk-[a-z0-9-]+\.bin$/.test(name)&&!used.has(name))await IOUtils.remove(path,{ignoreAbsent:true});}}
  });return this.chain;}
};
