/* Bundled WASM and weights only. No metadata is sent over the network. */
importScripts('semantic-core.js','vendor/onnx/ort.wasm.min.js');
let session,tokenizer,pooling='mean',maxTokens=256;
onmessage=async event=>{const {id,texts,init}=event.data;try{
 if(init){ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;pooling=init.pooling||'mean';maxTokens=init.maxTokens||256;ort.env.wasm.wasmPaths=init.wasm?{wasm:init.wasm,mjs:new URL('vendor/onnx/ort-wasm-simd-threaded.mjs',location.href).href}:new URL('vendor/onnx/',location.href).href;tokenizer=init.tokenizer||await (await fetch(init.tokenizerURL||new URL('models/minilm/tokenizer.json',location.href))).json();session=await ort.InferenceSession.create(init.model||new URL('models/minilm/model_quantized.onnx',location.href).href,{executionProviders:['wasm'],graphOptimizationLevel:'all'});postMessage({id,ready:true});return;}
 if(!session)throw Error('本地模型尚未加载');const output=new Array(texts.length),encoded=texts.map((text,index)=>({index,tokens:CiteLensSemanticCore.tokenize(text,tokenizer,maxTokens)})).sort((a,b)=>a.tokens.length-b.tokens.length||a.index-b.index);
 for(let start=0;start<texts.length;start+=4){const began=Date.now(),entries=encoded.slice(start,start+4),batch=entries.map(x=>x.tokens),length=Math.max(...batch.map(t=>t.length)),size=batch.length*length,ids=new BigInt64Array(size),mask=new BigInt64Array(size),types=new BigInt64Array(size);
 for(let b=0;b<batch.length;b++)for(let t=0;t<batch[b].length;t++){ids[b*length+t]=BigInt(batch[b][t]);mask[b*length+t]=1n;}
 const shape=[batch.length,length],feed={input_ids:new ort.Tensor('int64',ids,shape),attention_mask:new ort.Tensor('int64',mask,shape),token_type_ids:new ort.Tensor('int64',types,shape)},result=await session.run(feed),hidden=result.last_hidden_state;if(pooling==='sentence'){const tensor=result.sentence_embedding||Object.values(result)[0],d=tensor.dims.at(-1);for(let i=0;i<batch.length;i++)output[entries[i].index]=CiteLensSemanticCore.normalize(Array.from(tensor.data.slice(i*d,(i+1)*d)));}else {const rows=CiteLensSemanticCore.pool(hidden.data,hidden.dims,mask);rows.forEach((v,i)=>output[entries[i].index]=v);}for(const tensor of Object.values(feed))tensor.dispose();for(const tensor of Object.values(result))tensor.dispose();postMessage({id,progress:Math.min(texts.length,start+batch.length),total:texts.length});
 // Keep inference on one core and yield between batches for other desktop work.
 if(start+batch.length<texts.length)await new Promise(resolve=>setTimeout(resolve,Math.min(40,Math.max(8,(Date.now()-began)*.2))));}
 postMessage({id,vectors:output});
}catch(error){postMessage({id,error:String(error.message||error)});}};
